from enum import Enum


class FinderState(Enum):
    CREATE_CASE_MOBILE = "FINDER_CREATE_CASE_MOBILE"
    MOBILE_MANAGEMENT = "FINDER_MOBILE_MANAGEMENT"
    CREATE_CASE_TAC = "FINDER_CREATE_CASE_TAC"
    FINDER_DISCLAIMER = "FINDER_DISCLAIMER"
    CHOOSE_COUNTRY = "FINDER_CHOOSE_COUNTRY"
    CHOOSE_PROVINCE = "FINDER_CHOOSE_PROVINCE"
    VIEW_COMPLAINTS = "FINDER_VIEW_COMPLAINTS"
    END = "END"