from enum import Enum


class ListingState(Enum):
    CASE_DETAILS = "CASE_DETAILS"
    ENTER_COUNTRY = "ENTER_COUNTRY"
    ENTER_CITY = "ENTER_CITY"
    EDIT_FIELD = "EDIT_FIELD"
    CONFIRM_EXTEND = "CONFIRM_EXTEND"
    SELECT_WALLET_FOR_EXTEND = "SELECT_WALLET_FOR_EXTEND"
    REWARD_TRANSFER_PROCESS = "REWARD_TRANSFER_PROCESS"
    CHOOSE_COUNTRY = "CHOOSE_COUNTRY"
    CHOOSE_CITY = "CHOOSE_CITY"
    CONFIRM_REWARD = "CONFIRM_REWARD"
    CHOOSE_WALLET_TYPE = "CHOOSE_WALLET_TYPE"
    NAME_WALLET = "NAME_WALLET"