from enum import Enum


class SettingsState(Enum):
    SETTINGS_MENU = "SETTINGS_MENU"
    WAITING_FOR_MOBILE = "WAITING_FOR_MOBILE"
    SETTINGS_MOBILE_MANAGEMENT = "SETTINGS_MOBILE_MANAGEMENT"
    MOBILE_VERIFICATION = "MOBILE_VERIFICATION"
    SETTINGS_CREATE_CASE_TAC = "SETTINGS_CREATE_CASE_TAC"
    END = "END"