from enum import Enum


class StatsState(Enum):
    SHOW_STATS_MENU = "SHOW_STATS_MENU"
    SHOW_UNSOLVED_COUNTRIES = "SHOW_UNSOLVED_COUNTRIES"
    SHOW_MY_CASES = "SHOW_MY_CASES"
    ASK_LOCAL_PROVINCE_CITY = "ASK_LOCAL_PROVINCE_CITY"