from enum import Enum


class WalletState(Enum):
    WALLET_MENU = "WALLET_MENU"
    SOL_WALLET_DETAIL = "SOL_WALLET_DETAIL"
    SOL_WALLET_ACTIONS = "SOL_WALLET_ACTIONS"
    USDT_WALLET_DETAIL = "USDT_WALLET_DETAIL"
    USDT_WALLET_ACTIONS = "USDT_WALLET_ACTIONS"
    CONFIRM_PRIVATE_KEY = "CONFIRM_PRIVATE_KEY"
    SHOW_ADDRESS = "SHOW_ADDRESS"
    VIEW_HISTORY = "VIEW_HISTORY"
    SELECT_WALLET_TYPE = "SELECT_WALLET_TYPE"
    ENTER_WALLET_NAME = "ENTER_WALLET_NAME"
    CONFIRM_DELETE_WALLET = "CONFIRM_DELETE_WALLET"
    DELETE_WALLET = "DELETE_WALLET"
    END = "END"