FINDER_CONSTANT = {
    "en": {
        "choose_province": "Please select a province:",
        "more_provinces": "More provinces...",
        "case_list": "Available cases:",
        "case_details": "Case Details:",
        "save_case": "Save Case",
        "found_case": "Found Case",
        "upload_proof": "Please upload a photo or video as proof.",
        "invalid_proof": "Invalid proof. Please upload a photo or video.",
        "enter_location": "Enter the location where the person was found:",
        "notify_advertiser": "The advertiser has been notified. Thank you!",
        "province_not_found": "No matching provinces found. Please try again:",
        "province_multi": "Multiple provinces found (Page {page} of {total}):",
        "province_selected": "You have selected",
        "missing_information": "❌ Missing information. Please start over.",
        "notification_text": (
            "🚨 Potential Match Alert! 🚨\n\n"
            "Case #{case_no}: {person_name}\n"
            "📍 Reported Location: {location}\n"
            "🔗 Proof File: {proof_path}"
        ),
        "reply_to_advertiser": "✅ The case owner has been notified!\n\n"
        "Thank you for your contribution. We'll contact you if more information is needed.",
        "error_sending_notification": "❌ Error sending notification. Please try again later.",
        "proof_upload": "Please upload photo/video proof:",
        "error_processing_proof": "❌ Error processing your proof. Please try again.",
        "case_not_found": "❌ Case not found.",
        "proof_received": "✅ Proof received. \n \n  Please enter the location where you found this person:",
        "error_upload_proof": "❌ Please upload a photo or video.",
        "no_case_selected": "Error: No case selected. Please start over.",
        "error_loading_case": "Error loading case details, Please try again.",
        "mark_as_found": "✅ Mark as Found",
        "back_to_list": "🔙 Back to List",
        "case_not_found_in_province": "No cases found in this province.",
        "select_province": "Please select a province first.",
        "no_case_found_in_province": "No cases found for {province}.",
        "province_not_exist": "Province does not exist.",
        "choose_number_or_add_new": "Choose a number or add a new one:",
        "add_new_number": "Add New Number",
        "enter_new_number": "Please enter a new number:",
        "number_already_exists": "The number <b>{number}</b> already exists.",
        "otp_sent": "An OTP has been sent to <b>{number}</b>. Please enter the OTP to verify.",
        "number_added": "The number <b>{number}</b> has been added successfully.",
        "invalid_otp": "Invalid OTP. Please try again.",
    },
    "zh": {
        "choose_province": "请选择一个省份：",
        "more_provinces": "更多省份...",
        "case_list": "可用案件：",
        "case_details": "案件详情：",
        "save_case": "保存案件",
        "found_case": "已找到",
        "upload_proof": "请上传照片或视频作为证据：",
        "invalid_proof": "无效的证据。请上传照片或视频。",
        "enter_location": "请输入发现此人的地点：",
        "notify_advertiser": "广告发布者已收到通知。谢谢！",
        "province_not_found": "未找到匹配的省份。请重试：",
        "province_multi": "找到多个省份（第 {page} 页 / 共 {total} 页）：",
        "province_selected": "您已选择",
        "missing_information": "❌ 缺少信息。请重新开始。",
        "notification_text": (
            "🚨 潜在匹配警报！ 🚨\n\n"
            "案件 #{case_no}: {person_name}\n"
            "📍 报告地点: {location}\n"
            "🔗 证据文件: {proof_path}"
        ),
        "reply_to_advertiser": "✅ 案件拥有者已收到通知！\n\n"
        "感谢您的贡献。如需更多信息，我们会与您联系。",
        "error_sending_notification": "❌ 发送通知时出错。请稍后再试。",
        "proof_upload": "请上传照片/视频作为证明：",
        "error_processing_proof": "❌ 处理您的证据时出错。请重试。",
        "case_not_found": "❌ 案件未找到。",
        "proof_received": "✅ 已收到证据。\n\n请输入您发现此人所在的地点：",
        "error_upload_proof": "❌ 请上传照片或视频。",
        "no_case_selected": "错误：未选择案件。请重新开始。",
        "error_loading_case": "加载案件详情时出错，请重试。",
        "mark_as_found": "✅ 标记为已找到",
        "back_to_list": "🔙 返回列表",
        "case_not_found_in_province": "该省没有案件。",
        "select_province": "请先选择一个省份。",
        "no_case_found_in_province": "{province} 中未找到任何案件。",
        "province_not_exist": "省份不存在。",
        "choose_number_or_add_new": "选择号码或添加新号码：",
        "add_new_number": "添加新号码",
        "enter_new_number": "请输入新号码：",
        "number_already_exists": "号码 <b>{number}</b> 已存在。",
        "otp_sent": "验证码已发送至 <b>{number}</b>。请输入验证码进行验证。",
        "number_added": "号码 <b>{number}</b> 已成功添加。",
        "invalid_otp": "无效的验证码。请重试。",
    },
    "ms": {
        "choose_province": "Sila pilih negeri:",
        "more_provinces": "Lebih banyak negeri...",
        "case_list": "Kes tersedia:",
        "case_details": "Butiran Kes:",
        "save_case": "Simpan Kes",
        "found_case": "Kes Dijumpai",
        "upload_proof": "Sila muat naik gambar atau video sebagai bukti:",
        "invalid_proof": "Bukti tidak sah. Sila muat naik gambar atau video.",
        "enter_location": "Masukkan lokasi di mana orang tersebut dijumpai:",
        "notify_advertiser": "Pengiklan telah diberitahu. Terima kasih!",
        "province_not_found": "Tiada negeri yang sepadan dijumpai. Sila cuba lagi:",
        "province_multi": "Beberapa negeri dijumpai (Muka surat {page} daripada {total}):",
        "province_selected": "Anda telah memilih",
        "missing_information": "❌ Maklumat tidak lengkap. Sila mulakan semula.",
        "notification_text": (
            "🚨 Awas! Kejayaan Berpotensi! 🚨\n\n"
            "Kes #{case_no}: {person_name}\n"
            "📍 Lokasi Dilaporkan: {location}\n"
            "🔗 Fail Bukti: {proof_path}"
        ),
        "reply_to_advertiser": "✅ Pemilik kes telah diberitahu!\n\n"
        "Terima kasih atas sumbangan anda. Kami akan hubungi anda jika maklumat tambahan diperlukan.",
        "error_sending_notification": "❌ Ralat menghantar notifikasi. Sila cuba lagi kemudian.",
        "proof_upload": "Sila muat naik bukti foto/video:",
        "error_processing_proof": "❌ Ralat memproses bukti anda. Sila cuba lagi.",
        "case_not_found": "❌ Kes tidak dijumpai.",
        "proof_received": "✅ Bukti telah diterima.\n\nSila masukkan lokasi di mana anda menjumpai individu ini:",
        "error_upload_proof": "❌ Sila muat naik gambar atau video.",
        "no_case_selected": "Ralat: Tiada kes dipilih. Sila mulakan semula.",
        "error_loading_case": "Ralat memuatkan butiran kes. Sila cuba lagi.",
        "mark_as_found": "✅ Tandakan Sebagai Dijumpai",
        "back_to_list": "🔙 Kembali ke Senarai",
        "case_not_found_in_province": "Tiada kes dijumpai di negeri ini.",
        "select_province": "Sila pilih negeri dahulu.",
        "no_case_found_in_province": "Tiada kes dijumpai untuk {province}.",
        "province_not_exist": "Negeri tidak wujud.",
        "choose_number_or_add_new": "Pilih nombor atau tambah nombor baru:",
        "add_new_number": "Tambah Nombor Baru",
        "enter_new_number": "Sila masukkan nombor baru:",
        "number_already_exists": "Nombor <b>{number}</b> sudah wujud.",
        "otp_sent": "OTP telah dihantar ke <b>{number}</b>. Sila masukkan OTP untuk pengesahan.",
        "number_added": "Nombor <b>{number}</b> telah berjaya ditambah.",
        "invalid_otp": "OTP tidak sah. Sila cuba lagi.",
    },
    "th": {
        "choose_province": "กรุณาเลือกจังหวัด:",
        "more_provinces": "จังหวัดเพิ่มเติม...",
        "case_list": "รายการเคสที่พร้อมใช้งาน:",
        "case_details": "รายละเอียดเคส:",
        "save_case": "บันทึกเคส",
        "found_case": "พบเคสแล้ว",
        "upload_proof": "กรุณาอัปโหลดรูปภาพหรือวิดีโอเป็นหลักฐาน:",
        "invalid_proof": "หลักฐานไม่ถูกต้อง กรุณาอัปโหลดรูปภาพหรือวิดีโอ",
        "enter_location": "กรุณากรอกสถานที่ที่คุณพบบุคคลนี้:",
        "notify_advertiser": "ผู้ลงประกาศได้รับการแจ้งเรียบร้อยแล้ว ขอบคุณ!",
        "province_not_found": "ไม่มีจังหวัดตรงกัน กรุณาลองใหม่:",
        "province_multi": "พบหลายจังหวัด (หน้า {page} จาก {total}):",
        "province_selected": "คุณเลือกจังหวัด",
        "missing_information": "❌ ข้อมูลไม่ครบ กรุณาเริ่มใหม่",
        "notification_text": (
            "🚨 การแจ้งเตือนความสำเร็จที่อาจเกิดขึ้น! 🚨\n\n"
            "เคส #{case_no}: {person_name}\n"
            "📍 พื้นที่รายงาน: {location}\n"
            "🔗 ไฟล์หลักฐาน: {proof_path}"
        ),
        "reply_to_advertiser": "✅ เจ้าของเคสได้รับการแจ้งแล้ว!\n\n"
        "ขอบคุณที่ช่วยเหลือ เราจะติดต่อคุณหากต้องการข้อมูลเพิ่มเติม",
        "error_sending_notification": "❌ เกิดข้อผิดพลาดในการส่งการแจ้งเตือน กรุณาลองใหม่ภายหลัง",
        "proof_upload": "กรุณาอัปโหลดหลักฐานรูปภาพ/วิดีโอ:",
        "error_processing_proof": "❌ เกิดข้อผิดพลาดขณะประมวลผลหลักฐานของคุณ กรุณาลองใหม่",
        "case_not_found": "❌ ไม่พบเคส",
        "proof_received": "✅ ได้รับหลักฐานแล้ว \n\nกรุณากรอกสถานที่ที่คุณพบบุคคลนี้:",
        "error_upload_proof": "❌ กรุณาอัปโหลดรูปภาพหรือวิดีโอ",
        "no_case_selected": "ข้อผิดพลาด: ไม่ได้เลือกเคส กรุณาเริ่มใหม่",
        "error_loading_case": "เกิดข้อผิดพลาดขณะโหลดข้อมูลเคส กรุณาลองใหม่",
        "mark_as_found": "✅ ทำเครื่องหมายว่าพบแล้ว",
        "back_to_list": "🔙 กลับไปที่รายการ",
        "case_not_found_in_province": "ไม่มีเคสในจังหวัดนี้",
        "select_province": "กรุณาเลือกจังหวัดก่อน",
        "no_case_found_in_province": "ไม่มีเคสใน {province}",
        "province_not_exist": "จังหวัดไม่มีอยู่จริง",
        "choose_number_or_add_new": "เลือกเบอร์โทรศัพท์ หรือเพิ่มเบอร์ใหม่:",
        "add_new_number": "เพิ่มเบอร์ใหม่",
        "enter_new_number": "กรุณากรอกเบอร์ใหม่:",
        "number_already_exists": "เบอร์ <b>{number}</b> มีอยู่แล้ว",
        "otp_sent": "รหัส OTP ถูกส่งไปยัง <b>{number}</b> กรุณากรอกรหัส OTP เพื่อยืนยัน",
        "number_added": "เบอร์ <b>{number}</b> ถูกเพิ่มเรียบร้อยแล้ว",
        "invalid_otp": "OTP ไม่ถูกต้อง กรุณาลองใหม่",
    },
    "vi": {
        "choose_province": "Vui lòng chọn tỉnh:",
        "more_provinces": "Thêm tỉnh...",
        "case_list": "Danh sách trường hợp:",
        "case_details": "Chi tiết trường hợp:",
        "save_case": "Lưu trường hợp",
        "found_case": "Tìm thấy người",
        "upload_proof": "Vui lòng tải lên ảnh hoặc video làm bằng chứng:",
        "invalid_proof": "Bằng chứng không hợp lệ. Vui lòng tải lên ảnh hoặc video.",
        "enter_location": "Nhập vị trí nơi bạn tìm thấy người này:",
        "notify_advertiser": "Người đăng tin đã được thông báo. Cảm ơn bạn!",
        "province_not_found": "Không tìm thấy tỉnh phù hợp. Vui lòng thử lại:",
        "province_multi": "Tìm thấy nhiều tỉnh (Trang {page}/{total}):",
        "province_selected": "Bạn đã chọn",
        "missing_information": "❌ Thiếu thông tin. Vui lòng bắt đầu lại.",
        "notification_text": (
            "🚨 Cảnh báo kết quả tiềm năng! 🚨\n\n"
            "Trường hợp #{case_no}: {person_name}\n"
            "📍 Nơi báo cáo: {location}\n"
            "🔗 Tệp bằng chứng: {proof_path}"
        ),
        "reply_to_advertiser": "✅ Người tạo bài đăng đã nhận được thông báo!\n\n"
        "Cảm ơn đóng góp của bạn. Chúng tôi sẽ liên hệ nếu cần thêm thông tin.",
        "error_sending_notification": "❌ Lỗi gửi thông báo. Vui lòng thử lại sau.",
        "proof_upload": "Vui lòng tải lên ảnh/chứng cứ video:",
        "error_processing_proof": "❌ Lỗi xử lý bằng chứng. Vui lòng thử lại.",
        "case_not_found": "❌ Không tìm thấy trường hợp nào.",
        "proof_received": "✅ Đã nhận được bằng chứng. \n\nVui lòng nhập vị trí bạn tìm thấy người này:",
        "error_upload_proof": "❌ Vui lòng tải lên ảnh hoặc video.",
        "no_case_selected": "Lỗi: Chưa chọn trường hợp nào. Vui lòng bắt đầu lại.",
        "error_loading_case": "Lỗi khi tải chi tiết trường hợp, vui lòng thử lại.",
        "mark_as_found": "✅ Đánh dấu là đã tìm thấy",
        "back_to_list": "🔙 Quay lại danh sách",
        "case_not_found_in_province": "Không có trường hợp nào trong tỉnh này.",
        "select_province": "Vui lòng chọn tỉnh trước tiên.",
        "no_case_found_in_province": "Không tìm thấy trường hợp nào ở {province}.",
        "province_not_exist": "Tỉnh không tồn tại.",
        "choose_number_or_add_new": "Chọn số điện thoại hoặc thêm số mới:",
        "add_new_number": "Thêm số mới",
        "enter_new_number": "Vui lòng nhập số mới:",
        "number_already_exists": "Số <b>{number}</b> đã tồn tại.",
        "otp_sent": "Một mã OTP đã được gửi đến <b>{number}</b>. Vui lòng nhập mã OTP để xác thực.",
        "number_added": "Số <b>{number}</b> đã được thêm thành công.",
        "invalid_otp": "Mã OTP không hợp lệ. Vui lòng thử lại.",
    },
    "ur": {
        "choose_province": "براہ کرم صوبہ منتخب کریں:",
        "more_provinces": "مزید صوبے...",
        "case_list": "دستیاب معاملات:",
        "case_details": "معاملے کی تفصیل:",
        "save_case": "کیس محفوظ کریں",
        "found_case": "کیس مل گیا",
        "upload_proof": "براہ کرم ثبوت کے طور پر تصویر یا ویڈیو اپ لوڈ کریں:",
        "invalid_proof": "غیر درست ثبوت۔ براہ کرم تصویر یا ویڈیو اپ لوڈ کریں۔",
        "enter_location": "وہ مقام درج کریں جہاں آپ نے شخص کو پایا:",
        "notify_advertiser": "معلن کو آگاہ کر دیا گیا ہے۔ شکریہ!",
        "province_not_found": "کوئی مطابقت رکھنے والا صوبہ نہیں ملا۔ دوبارہ کوشش کریں:",
        "province_multi": "متعدد صوبے ملے (صفحہ {page} منہ {total}):",
        "province_selected": "آپ نے منتخب کیا ہے",
        "missing_information": "❌ معلومات ناقص ہیں۔ براہ کرم دوبارہ شروع کریں۔",
        "notification_text": (
            "🚨 ممکنہ مماثلت کی خبرداری! 🚨\n\n"
            "کیس نمبر#{case_no}: {person_name}\n"
            "📍 رپورٹ کیا ہوا مقام: {location}\n"
            "🔗 ثبوت فائل: {proof_path}"
        ),
        "reply_to_advertiser": "✅ کیس کے مالک کو آگاہ کر دیا گیا!\n\n"
        "ہماری مدد کے لیے شکریہ۔ اضافی معلومات کی ضرورت پڑنے پر ہم آپ سے رابطہ کریں گے۔",
        "error_sending_notification": "❌ نوٹیفیکیشن بھیجنے میں خرابی۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
        "proof_upload": "براہ کرم تصویر/ویڈیو ثبوت اپ لوڈ کریں:",
        "error_processing_proof": "❌ آپ کے ثبوت کی پروسیسنگ میں خرابی۔ دوبارہ کوشش کریں۔",
        "case_not_found": "❌ کیس نہیں ملا۔",
        "proof_received": "✅ ثبوت موصول ہو گیا۔ \n\nبراہ کرم وہ مقام درج کریں جہاں آپ نے یہ شخص تلاش کیا:",
        "error_upload_proof": "❌ براہ کرم تصویر یا ویڈیو اپ لوڈ کریں۔",
        "no_case_selected": "غلطی: کوئی کیس منتخب نہیں کیا گیا۔ براہ کرم دوبارہ شروع کریں۔",
        "error_loading_case": "کیس کی تفصیل لود کرتے وقت غلطی، دوبارہ کوشش کریں۔",
        "mark_as_found": "✅ مل گیا کے طور پر نشان زد کریں",
        "back_to_list": "🔙 فہرست میں واپس جائیں",
        "case_not_found_in_province": "اس صوبہ میں کوئی کیس نہیں ملا۔",
        "select_province": "براہ کرم پہلے صوبہ منتخب کریں۔",
        "no_case_found_in_province": "{province} میں کوئی کیس نہیں ملا۔",
        "province_not_exist": "صوبہ موجود نہیں ہے۔",
        "choose_number_or_add_new": "نمبر منتخب کریں یا نیا شامل کریں:",
        "add_new_number": "نیا نمبر شامل کریں",
        "enter_new_number": "براہ کرم ایک نیا نمبر درج کریں:",
        "number_already_exists": "نمبر <b>{number}</b> پہلے سے موجود ہے۔",
        "otp_sent": "OTP <b>{number}</b> پر بھیج دیا گیا ہے۔ براہ کرم تصدیق کے لیے OTP درج کریں۔",
        "number_added": "نمبر <b>{number}</b> کامیابی سے شامل کر لیا گیا ہے۔",
        "invalid_otp": "غیر درست OTP۔ براہ کرم دوبارہ کوشش کریں۔",
    },
    "ja": {
        "choose_province": "都道府県を選択してください:",
        "more_provinces": "他の都道府県...",
        "case_list": "利用可能なケース一覧:",
        "case_details": "ケース詳細:",
        "save_case": "ケースを保存",
        "found_case": "発見済み",
        "upload_proof": "証拠として画像または動画をアップロードしてください:",
        "invalid_proof": "無効な証拠です。画像または動画をアップロードしてください。",
        "enter_location": "人が見つかった場所を入力してください:",
        "notify_advertiser": "掲載者が通知されました。ありがとうございます！",
        "province_not_found": "一致する都道府県がありません。再度試してください:",
        "province_multi": "複数の都道府県が見つかりました（ページ {page}/{total}):",
        "province_selected": "選択しました:",
        "missing_information": "❌ 情報が不足しています。最初からやり直してください。",
        "notification_text": (
            "🚨 可能性のあるマッチング検出！ 🚨\n\n"
            "ケース #{case_no}: {person_name}\n"
            "📍 報告された場所: {location}\n"
            "🔗 証拠ファイル: {proof_path}"
        ),
        "reply_to_advertiser": "✅ ケース所有者に通知しました！\n\n"
        "ご協力ありがとうございます。追加情報が必要な場合はご連絡いたします。",
        "error_sending_notification": "❌ 通知の送信中にエラーが発生しました。後で再試行してください。",
        "proof_upload": "画像/動画の証拠をアップロードしてください:",
        "error_processing_proof": "❌ 証拠の処理中にエラーが発生しました。再試行してください。",
        "case_not_found": "❌ ケースが見つかりません。",
        "proof_received": "✅ 証拠を受け取りました。\n\nこの人物を見つけた場所を入力してください:",
        "error_upload_proof": "❌ 画像または動画をアップロードしてください。",
        "no_case_selected": "エラー：ケースが選択されていません。最初からやり直してください。",
        "error_loading_case": "ケース詳細の読み込み中にエラーが発生しました。再試行してください。",
        "mark_as_found": "✅ 発見済みとしてマーク",
        "back_to_list": "🔙 一覧に戻る",
        "case_not_found_in_province": "この都道府県にはケースがありません。",
        "select_province": "まず都道府県を選択してください。",
        "no_case_found_in_province": "{province} にはケースがありません。",
        "province_not_exist": "その都道府県は存在しません。",
        "choose_number_or_add_new": "番号を選択するか、新規に追加してください:",
        "add_new_number": "新しい番号を追加",
        "enter_new_number": "新しい番号を入力してください:",
        "number_already_exists": "番号 <b>{number}</b> はすでに存在しています。",
        "otp_sent": "OTPが <b>{number}</b> に送信されました。確認のためにOTPを入力してください。",
        "number_added": "番号 <b>{number}</b> を正常に追加しました。",
        "invalid_otp": "無効なOTPです。再試行してください。",
    },
    "ko": {
        "choose_province": "시/도를 선택해 주세요:",
        "more_provinces": "추가 시/도...",
        "case_list": "사용 가능한 사건 목록:",
        "case_details": "사건 상세 정보:",
        "save_case": "사건 저장",
        "found_case": "발견됨",
        "upload_proof": "증거로 사진 또는 동영상을 업로드해 주세요:",
        "invalid_proof": "유효하지 않은 증거입니다. 사진 또는 동영상을 업로드해 주세요.",
        "enter_location": "발견한 장소를 입력하세요:",
        "notify_advertiser": "광고주는 알림을 받았습니다. 감사합니다!",
        "province_not_found": "일치하는 시/도가 없습니다. 다시 시도해 주세요:",
        "province_multi": "다중 시/도 발견됨 (페이지 {page}/{total}):",
        "province_selected": "선택하신 시/도는",
        "missing_information": "❌ 정보 누락됨. 처음부터 다시 시작해 주세요.",
        "notification_text": (
            "🚨 잠재적 일치 알림! 🚨\n\n"
            "케이스 #{case_no}: {person_name}\n"
            "📍 보고된 위치: {location}\n"
            "🔗 증거 파일: {proof_path}"
        ),
        "reply_to_advertiser": "✅ 사건 소유자가 알림을 받았습니다!\n\n"
        "기여해 주셔서 감사합니다. 추가 정보가 필요할 경우 연락드리겠습니다.",
        "error_sending_notification": "❌ 알림 전송 오류. 나중에 다시 시도해 주세요.",
        "proof_upload": "사진/동영상 증거를 업로드해 주세요:",
        "error_processing_proof": "❌ 증거 처리 중 오류 발생. 다시 시도해 주세요.",
        "case_not_found": "❌ 케이스를 찾을 수 없습니다.",
        "proof_received": "✅ 증거를 수신했습니다.\n\n발견한 사람의 위치를 입력해 주세요:",
        "error_upload_proof": "❌ 사진 또는 동영상을 업로드해 주세요.",
        "no_case_selected": "오류: 케이스가 선택되지 않았습니다. 처음부터 다시 시작해 주세요.",
        "error_loading_case": "케이스 세부 정보 로딩 오류. 다시 시도해 주세요.",
        "mark_as_found": "✅ 발견됨으로 표시",
        "back_to_list": "🔙 목록으로 돌아가기",
        "case_not_found_in_province": "이 시/도에는 사건이 없습니다.",
        "select_province": "먼저 시/도를 선택해 주세요.",
        "no_case_found_in_province": "{province} 에는 사건이 없습니다.",
        "province_not_exist": "시/도가 존재하지 않습니다.",
        "choose_number_or_add_new": "번호를 선택하거나 새 번호를 추가하세요:",
        "add_new_number": "새 번호 추가",
        "enter_new_number": "새 번호를 입력해 주세요:",
        "number_already_exists": "번호 <b>{number}</b> 은(는) 이미 존재합니다.",
        "otp_sent": "OTP가 <b>{number}</b> 으로 전송되었습니다. 확인을 위해 OTP를 입력해 주세요.",
        "number_added": "번호 <b>{number}</b> 이(가) 성공적으로 추가되었습니다.",
        "invalid_otp": "잘못된 OTP입니다. 다시 시도해 주세요.",
    },
    "id": {
        "choose_province": "Silakan pilih provinsi:",
        "more_provinces": "Provinsi lainnya...",
        "case_list": "Daftar kasus:",
        "case_details": "Detail Kasus:",
        "save_case": "Simpan Kasus",
        "found_case": "Kasus Ditemukan",
        "upload_proof": "Silakan unggah foto atau video sebagai bukti:",
        "invalid_proof": "Bukti tidak valid. Silakan unggah foto atau video.",
        "enter_location": "Masukkan lokasi tempat orang ini ditemukan:",
        "notify_advertiser": "Pengiklan telah diberi tahu. Terima kasih!",
        "province_not_found": "Tidak ada provinsi yang cocok. Silakan coba lagi:",
        "province_multi": "Beberapa provinsi ditemukan (Halaman {page} dari {total}):",
        "province_selected": "Anda telah memilih",
        "missing_information": "❌ Informasi tidak lengkap. Silakan mulai ulang.",
        "notification_text": (
            "🚨 Peringatan Keberhasilan Potensial! 🚨\n\n"
            "Kasus #{case_no}: {person_name}\n"
            "📍 Lokasi Laporan: {location}\n"
            "🔗 File Bukti: {proof_path}"
        ),
        "reply_to_advertiser": "✅ Pemilik kasus telah diberitahu!\n\n"
        "Terima kasih atas kontribusi Anda. Kami akan menghubungi Anda jika informasi tambahan dibutuhkan.",
        "error_sending_notification": "❌ Kesalahan mengirim notifikasi. Silakan coba lagi nanti.",
        "proof_upload": "Silakan unggah bukti foto/video:",
        "error_processing_proof": "❌ Kesalahan saat memproses bukti Anda. Silakan coba lagi.",
        "case_not_found": "❌ Kasus tidak ditemukan.",
        "proof_received": "✅ Bukti diterima.\n\nSilakan masukkan lokasi tempat Anda menemukan orang ini:",
        "error_upload_proof": "❌ Silakan unggah foto atau video.",
        "no_case_selected": "Kesalahan: Tidak ada kasus yang dipilih. Silakan mulai ulang.",
        "error_loading_case": "Kesalahan memuat detail kasus. Silakan coba lagi.",
        "mark_as_found": "✅ Tandai Sebagai Ditemukan",
        "back_to_list": "🔙 Kembali ke Daftar",
        "case_not_found_in_province": "Tidak ada kasus ditemukan di provinsi ini.",
        "select_province": "Silakan pilih provinsi terlebih dahulu.",
        "no_case_found_in_province": "Tidak ada kasus ditemukan untuk {province}.",
        "province_not_exist": "Provinsi tidak ditemukan.",
        "choose_number_or_add_new": "Pilih nomor atau tambah nomor baru:",
        "add_new_number": "Tambah Nomor Baru",
        "enter_new_number": "Silakan masukkan nomor baru:",
        "number_already_exists": "Nomor <b>{number}</b> sudah ada.",
        "otp_sent": "OTP telah dikirim ke <b>{number}</b>. Silakan masukkan OTP untuk verifikasi.",
        "number_added": "Nomor <b>{number}</b> berhasil ditambahkan.",
        "invalid_otp": "OTP tidak valid. Silakan coba lagi.",
    },
    "km": {
        "choose_province": "សូមជ្រើសរើសខេត្ត:",
        "more_provinces": "ខេត្តបន្ថែម...",
        "case_list": "បញ្ជីករណី:",
        "case_details": "ព័ត៌មានលម្អិតអំពីករណី:",
        "save_case": "រក្សាទុកករណី",
        "found_case": "រកឃើញករណី",
        "upload_proof": "សូមផ្ទុកឡើងវីដេអូ ឬ រូបថតជាភស្តុតាង:",
        "invalid_proof": "ភស្តុតាងមិនត្រឹមត្រូវ។ សូមផ្ទុករូបថត ឬវីដេអូឡើងវិញ។",
        "enter_location": "សូមបញ្ចូលទីតាំងដែលអ្នករកឃើញបុគ្គលនោះ:",
        "notify_advertiser": "អ្នកបង្ហោះបានទទួលការជូនដំណឹងហើយ។ សូមអរគុណ!",
        "province_not_found": "គ្មានខេត្តណាដែលត្រូវគ្នាឡើយ។ សូមព្យាយាមម្តងទៀត:",
        "province_multi": "រកឃើញខេត្តច្រើន (ទំព័រ {page} នៃ {total}):",
        "province_selected": "អ្នកបានជ្រើសរើស",
        "missing_information": "❌ ខ្វះព័ត៌មាន។ សូមចាប់ផ្តើមឡើងវិញ។",
        "notification_text": (
            "🚨 ការជូនដំណឹងពីការរកឃើញដែលអាចកើតឡើង! 🚨\n\n"
            "ករណីលេខ#{case_no}: {person_name}\n"
            "📍 ទីតាំងរាយការណ៍: {location}\n"
            "🔗 ឯកសារភស្តុតាង: {proof_path}"
        ),
        "reply_to_advertiser": "✅ ម្ចាស់ករណីបានទទួលការជូនដំណឹងហើយ!\n\n"
        "សូមអរគុណចំពោះការចូលរួមរបស់អ្នក។ យើងនឹងទាក់ទងអ្នកប្រសិនបើចាំបាច់ត្រូវការព័ត៌មានបន្ថែម។",
        "error_sending_notification": "❌ កំហុសក្នុងការផ្ញើការជូនដំណឹង។ សូមព្យាយាមម្តងទៀត។",
        "proof_upload": "សូមផ្ទុកភស្តុតាងរូបភាព/វីដេអូឡើងវិញ:",
        "error_processing_proof": "❌ កំហុសក្នុងការដំណើរការភស្តុតាងរបស់អ្នក។ សូមព្យាយាមម្តងទៀត។",
        "case_not_found": "❌ គ្មានករណីនោះទេ។",
        "proof_received": "✅ ទទួលភស្តុតាងហើយ។ \n\nសូមបញ្ចូលទីតាំងដែលអ្នករកឃើញបុគ្គលនោះ:",
        "error_upload_proof": "❌ សូមផ្ទុករូបថត ឬវីដេអូឡើងវិញ។",
        "no_case_selected": "កំហុស: មិនបានជ្រើសរើសករណីណាមួយទេ។ សូមចាប់ផ្តើមឡើងវិញ។",
        "error_loading_case": "កំហុសក្នុងការផ្ទុកព័ត៌មានករណី។ សូមព្យាយាមម្តងទៀត។",
        "mark_as_found": "✅ សម្គាល់ថារកឃើញ",
        "back_to_list": "🔙 ត្រលប់ទៅបញ្ជី",
        "case_not_found_in_province": "គ្មានករណីនៅខេត្តនេះទេ។",
        "select_province": "សូមជ្រើសរើសខេត្តសិន។",
        "no_case_found_in_province": "គ្មានករណីណាមួយនៅខេត្ត {province} ទេ។",
        "province_not_exist": "ខេត្តមិនមានទេ។",
        "choose_number_or_add_new": "ជ្រើសរើសលេខ ឬបន្ថែមលេខថ្មី:",
        "add_new_number": "បន្ថែមលេខថ្មី",
        "enter_new_number": "សូមបញ្ចូលលេខថ្មី:",
        "number_already_exists": "លេខ <b>{number}</b> មានស្រាប់រួចហើយ។",
        "otp_sent": "លេខកូដ OTP ត្រូវបានផ្ញើទៅកាន់ <b>{number}</b>។ សូមបញ្ចូលលេខកូដ OTP ដើម្បីផ្ទៀងផ្ទាត់។",
        "number_added": "លេខ <b>{number}</b> ត្រូវបានបន្ថែមដោយជោគជ័យ។",
        "invalid_otp": "លេខកូដ OTP មិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។",
    },
}


# Count:
