FINDER_CONSTANT = {
    "english": {
        "choose_province": "Please select a province:",
        "more_provinces": "More provinces...",
        "case_list": "Available cases:",
        "case_details": "Case Details:",
        "save_case": "Save Case",
        "found_case": "Found Case",
        "upload_proof": "Please upload a photo or video as proof.",
        "invalid_proof": "Invalid proof. Please upload a photo or video.",
        "enter_location": "Enter the location where the person was found:",
        "notify_advertiser": "The advertiser has been notified. Thank you!",
        "province_not_found": "No matching provinces found. Please try again:",
        "province_multi": "Multiple provinces found (Page {page} of {total}):",
        "province_selected": "✅ Selected: ",
        "missing_information": "❌ Missing information. Please start over.",
        "notification_text": (
            "🚨 Potential Match Alert! 🚨\n\n"
            "Case #{case_no}: {person_name}\n"
            "📍 Reported Location: {location}\n"
            "🔗 Proof File: {proof_path}"
        ),
        "reply_to_advertiser": "✅ The case owner has been notified!\n\n"
        "Thank you for your contribution. We'll contact you if more information is needed.",
        "error_sending_notification": "❌ Error sending notification. Please try again later.",
        "proof_upload": "Please upload photo/video proof:",
        "error_processing_proof": "❌ Error processing your proof. Please try again.",
        "case_not_found": "❌ Case not found.",
        "proof_received": "✅ Proof received. \n \n  Please enter the location where you found this person:",
        "error_upload_proof": "❌ Please upload a photo or video.",
        "no_case_selected": "Error: No case selected. Please start over.",
        "error_loading_case": "Error loading case details, Please try again.",
        "mark_as_found": "✅ Mark as Found",
        "back_to_list": "🔙 Back to List",
        "case_not_found_in_province": "No cases found in this province.",
        "select_province": "Please select a province first.",
        "no_case_found_in_province": "No cases found for {province}.",
        "province_not_exist": "Province does not exist.",
        "choose_number_or_add_new": "Choose a number or add a new one:",
        "add_new_number": "Add New Number",
        "enter_new_number": "Please enter a new number:",
        "number_already_exists": "The number <b>{number}</b> already exists.",
        "otp_sent": "An OTP has been sent to <b>{number}</b>. Please enter the OTP to verify.",
        "number_added": "The number <b>{number}</b> has been added successfully.",
        "invalid_otp": "Invalid OTP. Please try again.",
    },
    "chinese": {
        "choose_province": "请选择一个省份：",
        "more_provinces": "更多省份...",
        "case_list": "可用案件：",
        "case_details": "案件详情：",
        "save_case": "保存案件",
        "found_case": "已找到",
        "upload_proof": "请上传照片或视频作为证据：",
        "invalid_proof": "无效的证据。请上传照片或视频。",
        "enter_location": "请输入发现此人的地点：",
        "notify_advertiser": "广告发布者已收到通知。谢谢！",
        "province_not_found": "未找到匹配的省份。请重试：",
        "province_multi": "找到多个省份（第 {page} 页 / 共 {total} 页）：",
        "province_selected": "✅ 已选择: ",
        "missing_information": "❌ 缺少信息。请重新开始。",
        "notification_text": (
            "🚨 潜在匹配警报！ 🚨\n\n"
            "案件 #{case_no}: {person_name}\n"
            "📍 报告地点: {location}\n"
            "🔗 证据文件: {proof_path}"
        ),
        "reply_to_advertiser": "✅ 案件拥有者已收到通知！\n\n"
        "感谢您的贡献。如需更多信息，我们会与您联系。",
        "error_sending_notification": "❌ 发送通知时出错。请稍后再试。",
        "proof_upload": "请上传照片/视频作为证明：",
        "error_processing_proof": "❌ 处理您的证据时出错。请重试。",
        "case_not_found": "❌ 案件未找到。",
        "proof_received": "✅ 已收到证据。\n\n请输入您发现此人所在的地点：",
        "error_upload_proof": "❌ 请上传照片或视频。",
        "no_case_selected": "错误：未选择案件。请重新开始。",
        "error_loading_case": "加载案件详情时出错，请重试。",
        "mark_as_found": "✅ 标记为已找到",
        "back_to_list": "🔙 返回列表",
        "case_not_found_in_province": "该省没有案件。",
        "select_province": "请先选择一个省份。",
        "no_case_found_in_province": "{province} 中未找到任何案件。",
        "province_not_exist": "省份不存在。",
        "choose_number_or_add_new": "选择号码或添加新号码：",
        "add_new_number": "添加新号码",
        "enter_new_number": "请输入新号码：",
        "number_already_exists": "号码 <b>{number}</b> 已存在。",
        "otp_sent": "验证码已发送至 <b>{number}</b>。请输入验证码进行验证。",
        "number_added": "号码 <b>{number}</b> 已成功添加。",
        "invalid_otp": "无效的验证码。请重试。",
    },
    "malay": {
        "choose_province": "Sila pilih negeri:",
        "more_provinces": "Lebih banyak negeri...",
        "case_list": "Kes tersedia:",
        "case_details": "Butiran Kes:",
        "save_case": "Simpan Kes",
        "found_case": "Kes Dijumpai",
        "upload_proof": "Sila muat naik gambar atau video sebagai bukti:",
        "invalid_proof": "Bukti tidak sah. Sila muat naik gambar atau video.",
        "enter_location": "Masukkan lokasi di mana orang tersebut dijumpai:",
        "notify_advertiser": "Pengiklan telah diberitahu. Terima kasih!",
        "province_not_found": "Tiada negeri yang sepadan dijumpai. Sila cuba lagi:",
        "province_multi": "Beberapa negeri dijumpai (Muka surat {page} daripada {total}):",
        "province_selected": "✅ Dipilih: ",
        "missing_information": "❌ Maklumat tidak lengkap. Sila mulakan semula.",
        "notification_text": (
            "🚨 Awas! Kejayaan Berpotensi! 🚨\n\n"
            "Kes #{case_no}: {person_name}\n"
            "📍 Lokasi Dilaporkan: {location}\n"
            "🔗 Fail Bukti: {proof_path}"
        ),
        "reply_to_advertiser": "✅ Pemilik kes telah diberitahu!\n\n"
        "Terima kasih atas sumbangan anda. Kami akan hubungi anda jika maklumat tambahan diperlukan.",
        "error_sending_notification": "❌ Ralat menghantar notifikasi. Sila cuba lagi kemudian.",
        "proof_upload": "Sila muat naik bukti foto/video:",
        "error_processing_proof": "❌ Ralat memproses bukti anda. Sila cuba lagi.",
        "case_not_found": "❌ Kes tidak dijumpai.",
        "proof_received": "✅ Bukti telah diterima.\n\nSila masukkan lokasi di mana anda menjumpai individu ini:",
        "error_upload_proof": "❌ Sila muat naik gambar atau video.",
        "no_case_selected": "Ralat: Tiada kes dipilih. Sila mulakan semula.",
        "error_loading_case": "Ralat memuatkan butiran kes. Sila cuba lagi.",
        "mark_as_found": "✅ Tandakan Sebagai Dijumpai",
        "back_to_list": "🔙 Kembali ke Senarai",
        "case_not_found_in_province": "Tiada kes dijumpai di negeri ini.",
        "select_province": "Sila pilih negeri dahulu.",
        "no_case_found_in_province": "Tiada kes dijumpai untuk {province}.",
        "province_not_exist": "Negeri tidak wujud.",
        "choose_number_or_add_new": "Pilih nombor atau tambah nombor baru:",
        "add_new_number": "Tambah Nombor Baru",
        "enter_new_number": "Sila masukkan nombor baru:",
        "number_already_exists": "Nombor <b>{number}</b> sudah wujud.",
        "otp_sent": "OTP telah dihantar ke <b>{number}</b>. Sila masukkan OTP untuk pengesahan.",
        "number_added": "Nombor <b>{number}</b> telah berjaya ditambah.",
        "invalid_otp": "OTP tidak sah. Sila cuba lagi.",
    },
    "thai": {
        "choose_province": "กรุณาเลือกจังหวัด:",
        "more_provinces": "จังหวัดเพิ่มเติม...",
        "case_list": "รายการเคสที่พร้อมใช้งาน:",
        "case_details": "รายละเอียดเคส:",
        "save_case": "บันทึกเคส",
        "found_case": "พบเคสแล้ว",
        "upload_proof": "กรุณาอัปโหลดรูปภาพหรือวิดีโอเป็นหลักฐาน:",
        "invalid_proof": "หลักฐานไม่ถูกต้อง กรุณาอัปโหลดรูปภาพหรือวิดีโอ",
        "enter_location": "กรุณากรอกสถานที่ที่คุณพบบุคคลนี้:",
        "notify_advertiser": "ผู้ลงประกาศได้รับการแจ้งเรียบร้อยแล้ว ขอบคุณ!",
        "province_not_found": "ไม่มีจังหวัดตรงกัน กรุณาลองใหม่:",
        "province_multi": "พบหลายจังหวัด (หน้า {page} จาก {total}):",
        "province_selected": "✅ ที่เลือก: ",
        "missing_information": "❌ ข้อมูลไม่ครบ กรุณาเริ่มใหม่",
        "notification_text": (
            "🚨 การแจ้งเตือนความสำเร็จที่อาจเกิดขึ้น! 🚨\n\n"
            "เคส #{case_no}: {person_name}\n"
            "📍 พื้นที่รายงาน: {location}\n"
            "🔗 ไฟล์หลักฐาน: {proof_path}"
        ),
        "reply_to_advertiser": "✅ เจ้าของเคสได้รับการแจ้งแล้ว!\n\n"
        "ขอบคุณที่ช่วยเหลือ เราจะติดต่อคุณหากต้องการข้อมูลเพิ่มเติม",
        "error_sending_notification": "❌ เกิดข้อผิดพลาดในการส่งการแจ้งเตือน กรุณาลองใหม่ภายหลัง",
        "proof_upload": "กรุณาอัปโหลดหลักฐานรูปภาพ/วิดีโอ:",
        "error_processing_proof": "❌ เกิดข้อผิดพลาดขณะประมวลผลหลักฐานของคุณ กรุณาลองใหม่",
        "case_not_found": "❌ ไม่พบเคส",
        "proof_received": "✅ ได้รับหลักฐานแล้ว \n\nกรุณากรอกสถานที่ที่คุณพบบุคคลนี้:",
        "error_upload_proof": "❌ กรุณาอัปโหลดรูปภาพหรือวิดีโอ",
        "no_case_selected": "ข้อผิดพลาด: ไม่ได้เลือกเคส กรุณาเริ่มใหม่",
        "error_loading_case": "เกิดข้อผิดพลาดขณะโหลดข้อมูลเคส กรุณาลองใหม่",
        "mark_as_found": "✅ ทำเครื่องหมายว่าพบแล้ว",
        "back_to_list": "🔙 กลับไปที่รายการ",
        "case_not_found_in_province": "ไม่มีเคสในจังหวัดนี้",
        "select_province": "กรุณาเลือกจังหวัดก่อน",
        "no_case_found_in_province": "ไม่มีเคสใน {province}",
        "province_not_exist": "จังหวัดไม่มีอยู่จริง",
        "choose_number_or_add_new": "เลือกเบอร์โทรศัพท์ หรือเพิ่มเบอร์ใหม่:",
        "add_new_number": "เพิ่มเบอร์ใหม่",
        "enter_new_number": "กรุณากรอกเบอร์ใหม่:",
        "number_already_exists": "เบอร์ <b>{number}</b> มีอยู่แล้ว",
        "otp_sent": "OTP <b>{number}</b> ถูกส่งไปยัง กรุณากรอก OTP เพื่อยืนยัน",
        "number_added": "เบอร์ <b>{number}</b> ถูกเพิ่มเรียบร้อยแล้ว",
        "invalid_otp": "OTP ไม่ถูกต้อง กรุณาลองใหม่",
    },
    "vietnamese": {
        "choose_province": "Vui lòng chọn tỉnh:",
        "more_provinces": "Thêm tỉnh...",
        "case_list": "Danh sách trường hợp:",
        "case_details": "Chi tiết trường hợp:",
        "save_case": "Lưu trường hợp",
        "found_case": "Tìm thấy người",
        "upload_proof": "Vui lòng tải lên ảnh hoặc video làm bằng chứng:",
        "invalid_proof": "Bằng chứng không hợp lệ. Vui lòng tải lên ảnh hoặc video.",
        "enter_location": "Nhập vị trí nơi bạn tìm thấy người này:",
        "notify_advertiser": "Người đăng tin đã được thông báo. Cảm ơn bạn!",
        "province_not_found": "Không tìm thấy tỉnh phù hợp. Vui lòng thử lại:",
        "province_multi": "Tìm thấy nhiều tỉnh (Trang {page}/{total}):",
        "province_selected": "✅ Đã chọn: ",
        "missing_information": "❌ Thiếu thông tin. Vui lòng bắt đầu lại.",
        "notification_text": (
            "🚨 Cảnh báo kết quả tiềm năng! 🚨\n\n"
            "Trường hợp #{case_no}: {person_name}\n"
            "📍 Nơi báo cáo: {location}\n"
            "🔗 Bằng chứng: {proof_path}"
        ),
        "reply_to_advertiser": "✅ Chủ sở hữu trường hợp đã được thông báo!\n\n"
        "Cảm ơn sự đóng góp của bạn. Chúng tôi sẽ liên hệ lại nếu cần thêm thông tin.",
        "error_sending_notification": "❌ Lỗi khi gửi thông báo. Vui lòng thử lại sau.",
        "proof_upload": "Vui lòng tải lên bằng chứng ảnh/video:",
        "error_processing_proof": "❌ Lỗi xử lý bằng chứng của bạn. Vui lòng thử lại.",
        "case_not_found": "❌ Không tìm thấy trường hợp.",
        "proof_received": "✅ Đã nhận được bằng chứng. \n\nVui lòng nhập vị trí bạn tìm thấy người này:",
        "error_upload_proof": "❌ Vui lòng tải lên ảnh hoặc video.",
        "no_case_selected": "Lỗi: Chưa chọn trường hợp. Vui lòng bắt đầu lại.",
        "error_loading_case": "Lỗi khi tải chi tiết trường hợp. Vui lòng thử lại.",
        "mark_as_found": "✅ Đánh dấu là đã tìm thấy",
        "back_to_list": "🔙 Quay lại danh sách",
        "case_not_found_in_province": "Không tìm thấy trường hợp nào trong tỉnh này.",
        "select_province": "Vui lòng chọn tỉnh trước.",
        "no_case_found_in_province": "Không tìm thấy trường hợp nào cho {province}.",
        "province_not_exist": "Tỉnh không tồn tại.",
        "choose_number_or_add_new": "Chọn số điện thoại hoặc thêm số mới:",
        "add_new_number": "Thêm số mới",
        "enter_new_number": "Vui lòng nhập số điện thoại mới:",
        "number_already_exists": "Số điện thoại <b>{number}</b> đã tồn tại.",
        "otp_sent": "OTP đã được gửi đến <b>{number}</b>. Vui lòng nhập OTP để xác minh.",
        "number_added": "Số điện thoại <b>{number}</b> đã được thêm thành công.",
        "invalid_otp": "OTP không hợp lệ. Vui lòng thử lại.",
    },
    "urdu": {
        "choose_province": "براہ کرم ایک صوبہ منتخب کریں:",
        "more_provinces": "مزید صوبے...",
        "case_list": "دستیاب کیسز:",
        "case_details": "کیس کی تفصیلات:",
        "save_case": "کیس محفوظ کریں",
        "found_case": "کیس مل گیا",
        "upload_proof": "براہ کرم ثبوت کے طور پر ایک تصویر یا ویڈیو اپ لوڈ کریں:",
        "invalid_proof": "غلط ثبوت۔ براہ کرم ایک تصویر یا ویڈیو اپ لوڈ کریں۔",
        "enter_location": "براہ کرم وہ جگہ درج کریں جہاں شخص پایا گیا تھا:",
        "notify_advertiser": "اشتہار دہندہ کو مطلع کر دیا گیا ہے۔ شکریہ!",
        "province_not_found": "کوئی مماثل صوبہ نہیں ملا۔ براہ کرم دوبارہ کوشش کریں:",
        "province_multi": "کئی صوبے ملے (صفحہ {page} از {total})៖",
        "province_selected": "✅ منتخب کردہ: ",
        "missing_information": "❌ معلومات غائب ہے۔ براہ کرم دوبارہ شروع کریں۔",
        "notification_text": (
            "🚨 ممکنہ میچ الرٹ! 🚨\n\n"
            "کیس #{case_no}: {person_name}\n"
            "📍 رپورٹ شدہ مقام: {location}\n"
            "🔗 ثبوت فائل: {proof_path}"
        ),
        "reply_to_advertiser": "✅ کیس کے مالک کو مطلع کر دیا گیا ہے!\n\n"
        "آپ کے تعاون کا شکریہ۔ مزید معلومات درکار ہونے پر ہم آپ سے رابطہ کریں گے۔",
        "error_sending_notification": "❌ اطلاع بھیجنے میں خرابی۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
        "proof_upload": "براہ کرم تصویر/ویڈیو کا ثبوت اپ لوڈ کریں:",
        "error_processing_proof": "❌ آپ کے ثبوت پر کارروائی میں خرابی۔ براہ کرم دوبارہ کوشش کریں۔",
        "case_not_found": "❌ کیس نہیں ملا۔",
        "proof_received": "✅ ثبوت موصول ہو گیا ہے۔ \n \n براہ کرم وہ جگہ درج کریں جہاں آپ کو یہ شخص ملا ہے:",
        "error_upload_proof": "❌ براہ کرم ایک تصویر یا ویڈیو اپ لوڈ کریں۔",
        "no_case_selected": "خرابی: کوئی کیس منتخب نہیں ہوا۔ براہ کرم دوبارہ شروع کریں۔",
        "error_loading_case": "کیس کی تفصیلات لوڈ کرنے میں خرابی، براہ کرم دوبارہ کوشش کریں۔",
        "mark_as_found": "✅ ملا ہوا نشان زد کریں",
        "back_to_list": "🔙 فہرست پر واپس جائیں",
        "case_not_found_in_province": "اس صوبے میں کوئی کیس نہیں ملا۔",
        "select_province": "براہ کرم پہلے ایک صوبہ منتخب کریں۔",
        "no_case_found_in_province": "{province} میں کوئی کیس نہیں ملا۔",
        "province_not_exist": "صوبہ موجود نہیں ہے۔",
        "choose_number_or_add_new": "نمبر منتخب کریں یا نیا شامل کریں:",
        "add_new_number": "نیا نمبر شامل کریں",
        "enter_new_number": "براہ کرم ایک نیا نمبر درج کریں:",
        "number_already_exists": "نمبر <b>{number}</b> پہلے سے موجود ہے۔",
        "otp_sent": "ایک OTP <b>{number}</b> کو بھیجا گیا ہے۔ براہ کرم تصدیق کے لیے OTP درج کریں۔",
        "number_added": "نمبر <b>{number}</b> کامیابی سے شامل کر دیا گیا ہے۔",
        "invalid_otp": "غلط OTP۔ براہ کرم دوبارہ کوشش کریں۔",
    },
    "japanese": {
        "choose_province": "都道府県を選択してください：",
        "more_provinces": "その他の都道府県...",
        "case_list": "利用可能なケース：",
        "case_details": "ケース詳細：",
        "save_case": "ケースを保存",
        "found_case": "ケースを発見",
        "upload_proof": "証拠として写真またはビデオをアップロードしてください：",
        "invalid_proof": "無効な証拠です。写真またはビデオをアップロードしてください。",
        "enter_location": "人物が発見された場所を入力してください：",
        "notify_advertiser": "広告主には通知済みです。ありがとうございます！",
        "province_not_found": "一致する都道府県が見つかりません。もう一度お試しください：",
        "province_multi": "複数の都道府県が見つかりました（{total}件中{page}ページ）：",
        "province_selected": "✅ 選択済み: ",
        "missing_information": "❌ 情報が不足しています。最初からやり直してください。",
        "notification_text": (
            "🚨 潜在的な一致アラート！ 🚨\n\n"
            "ケース #{case_no}: {person_name}\n"
            "📍 報告された場所: {location}\n"
            "🔗 証拠ファイル: {proof_path}"
        ),
        "reply_to_advertiser": "✅ ケースの所有者に通知されました！\n\n"
        "ご協力ありがとうございます。追加情報が必要な場合はご連絡いたします。",
        "error_sending_notification": "❌ 通知の送信中にエラーが発生しました。後でもう一度お試しください。",
        "proof_upload": "写真/ビデオの証拠をアップロードしてください：",
        "error_processing_proof": "❌ 証拠の処理中にエラーが発生しました。もう一度お試しください。",
        "case_not_found": "❌ ケースが見つかりません。",
        "proof_received": "✅ 証拠を受信しました。\n\nこの人物を発見した場所を入力してください：",
        "error_upload_proof": "❌ 写真またはビデオをアップロードしてください。",
        "no_case_selected": "エラー：ケースが選択されていません。最初からやり直してください。",
        "error_loading_case": "ケース詳細の読み込み中にエラーが発生しました。もう一度お試しください。",
        "mark_as_found": "✅ 発見済みとしてマーク",
        "back_to_list": "🔙 リストに戻る",
        "case_not_found_in_province": "この都道府県にはケースがありません。",
        "select_province": "まず都道府県を選択してください。",
        "no_case_found_in_province": "{province}でケースが見つかりませんでした。",
        "province_not_exist": "都道府県は存在しません。",
        "choose_number_or_add_new": "電話番号を選択するか、新しい電話番号を追加してください：",
        "add_new_number": "新しい電話番号を追加",
        "enter_new_number": "新しい電話番号を入力してください：",
        "number_already_exists": "電話番号 <b>{number}</b> はすでに存在します。",
        "otp_sent": "OTPが<b>{number}</b>に送信されました。確認のためOTPを入力してください。",
        "number_added": "電話番号<b>{number}</b>が正常に追加されました。",
        "invalid_otp": "無効なOTPです。もう一度お試しください。",
    },
    "korean": {
        "choose_province": "도를 선택하세요:",
        "more_provinces": "더 많은 도...",
        "case_list": "사용 가능한 사례:",
        "case_details": "사례 세부 정보:",
        "save_case": "사례 저장",
        "found_case": "사례 발견",
        "upload_proof": "증거로 사진 또는 비디오를 업로드하십시오:",
        "invalid_proof": "잘못된 증거입니다. 사진 또는 비디오를 업로드하십시오.",
        "enter_location": "이 사람이 발견된 위치를 입력하십시오:",
        "notify_advertiser": "광고주에게 통보되었습니다. 감사합니다!",
        "province_not_found": "일치하는 도를 찾을 수 없습니다. 다시 시도하십시오:",
        "province_multi": "여러 도를 찾았습니다 ({total} 중 {page} 페이지):",
        "province_selected": "✅ 선택됨: ",
        "missing_information": "❌ 정보가 누락되었습니다. 다시 시작하십시오.",
        "notification_text": (
            "🚨 잠재적 일치 알림! 🚨\n\n"
            "사례 #{case_no}: {person_name}\n"
            "📍 보고된 위치: {location}\n"
            "🔗 증거 파일: {proof_path}"
        ),
        "reply_to_advertiser": "✅ 사례 소유자에게 통보되었습니다!\n\n"
        "귀하의 기여에 감사드립니다. 추가 정보가 필요한 경우 연락드리겠습니다.",
        "error_sending_notification": "❌ 알림 전송 중 오류가 발생했습니다. 나중에 다시 시도하십시오.",
        "proof_upload": "사진/비디오 증거를 업로드하십시오:",
        "error_processing_proof": "❌ 증거 처리 중 오류가 발생했습니다. 다시 시도하십시오.",
        "case_not_found": "❌ 사례를 찾을 수 없습니다.",
        "proof_received": "✅ 증거가 접수되었습니다. \n \n 이 사람을 찾은 위치를 입력하십시오:",
        "error_upload_proof": "❌ 사진 또는 비디오를 업로드하십시오.",
        "no_case_selected": "오류: 선택된 사례가 없습니다. 다시 시작하십시오.",
        "error_loading_case": "사례 세부 정보 로드 중 오류가 발생했습니다. 다시 시도하십시오.",
        "mark_as_found": "✅ 발견으로 표시",
        "back_to_list": "🔙 목록으로 돌아가기",
        "case_not_found_in_province": "이 도에서 발견된 사례가 없습니다.",
        "select_province": "먼저 도를 선택하십시오.",
        "no_case_found_in_province": "{province}에서 발견된 사례가 없습니다.",
        "province_not_exist": "도가 존재하지 않습니다.",
        "choose_number_or_add_new": "번호를 선택하거나 새 번호를 추가하십시오:",
        "add_new_number": "새 번호 추가",
        "enter_new_number": "새 번호를 입력하십시오:",
        "number_already_exists": "번호 <b>{number}</b>가 이미 존재합니다.",
        "otp_sent": "OTP가 <b>{number}</b>로 전송되었습니다. 확인을 위해 OTP를 입력하십시오.",
        "number_added": "번호 <b>{number}</b>가 성공적으로 추가되었습니다.",
        "invalid_otp": "유효하지 않은 OTP입니다. 다시 시도하십시오.",
    },
    "khmer": {
        "choose_province": "សូមជ្រើសរើសខេត្ត៖",
        "more_provinces": "ខេត្តបន្ថែមទៀត...",
        "case_list": "ករណីដែលមាន៖",
        "case_details": "ព័ត៌មានលម្អិតករណី៖",
        "save_case": "រក្សាទុកករណី",
        "found_case": "រកឃើញករណី",
        "upload_proof": "សូមបញ្ចូលរូបភាព ឬវីដេអូជាភស្តុតាង៖",
        "invalid_proof": "ភស្តុតាងមិនត្រឹមត្រូវ។ សូមបញ្ចូលរូបភាព ឬវីដេអូ។",
        "enter_location": "បញ្ចូលទីតាំងដែលរកឃើញបុគ្គលនោះ៖",
        "notify_advertiser": "អ្នកផ្សាយពាណិជ្ជកម្មត្រូវបានជូនដំណឹងហើយ។ សូមអរគុណ!",
        "province_not_found": "មិនឃើញខេត្តដែលត្រូវគ្នាទេ។ សូមព្យាយាមម្តងទៀត៖",
        "province_multi": "រកឃើញខេត្តជាច្រើន (ទំព័រ {page} នៃ {total})៖",
        "province_selected": "✅ បានជ្រើសរើស: ",
        "missing_information": "❌ ព័ត៌មានមិនគ្រប់គ្រាន់។ សូមចាប់ផ្តើមឡើងវិញ។",
        "notification_text": (
            "🚨 ការជូនដំណឹងអំពីលទ្ធផល! 🚨\n\n"
            "ករណី #{case_no}: {person_name}\n"
            "📍 ទីតាំងរាយការណ៍: {location}\n"
            "🔗 ឯកសារភស្តុតាង: {proof_path}"
        ),
        "reply_to_advertiser": "✅ ម្ចាស់ករណីត្រូវបានជូនដំណឹងហើយ!\n\n"
        "សូមអរគុណចំពោះការរួមចំណែករបស់អ្នក។ យើងនឹងទាក់ទងអ្នកប្រសិនបើត្រូវការព័ត៌មានបន្ថែម។",
        "error_sending_notification": "❌ មានបញ្ហាក្នុងការផ្ញើការជូនដំណឹង។ សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។",
        "proof_upload": "សូមបញ្ចូលភស្តុតាងរូបថត/វីដេអូ៖",
        "error_processing_proof": "❌ មានបញ្ហាក្នុងការដំណើរការភស្តុតាងរបស់អ្នក។ សូមព្យាយាមម្តងទៀត។",
        "case_not_found": "❌ មិនឃើញករណី។",
        "proof_received": "✅ ទទួលបានភស្តុតាងហើយ។ \n \n សូមបញ្ចូលទីតាំងដែលអ្នកបានរកឃើញបុគ្គលនេះ៖",
        "error_upload_proof": "❌ សូមបញ្ចូលរូបភាព ឬវីដេអូ។",
        "no_case_selected": "កំហុស៖ មិនបានជ្រើសរើសករណី។ សូមចាប់ផ្តើមឡើងវិញ។",
        "error_loading_case": "មានបញ្ហាក្នុងការផ្ទុកព័ត៌មានលម្អិតករណី សូមព្យាយាមម្តងទៀត។",
        "mark_as_found": "✅ សម្គាល់ថាបានរកឃើញ",
        "back_to_list": "🔙 ត្រឡប់ទៅបញ្ជី",
        "case_not_found_in_province": "មិនមានករណីនៅក្នុងខេត្តនេះទេ។",
        "select_province": "សូមជ្រើសរើសខេត្តជាមុនសិន។",
        "no_case_found_in_province": "មិនមានករណីណាមួយនៅក្នុង {province} ទេ។។",
        "province_not_exist": "ខេត្តមិនមានទេ។",
        "choose_number_or_add_new": "ជ្រើសរើសលេខ ឬបន្ថែមលេខថ្មី៖",
        "add_new_number": "បន្ថែមលេខថ្មី",
        "enter_new_number": "សូមបញ្ចូលលេខថ្មី៖",
        "number_already_exists": "លេខ <b>{number}</b> មានរួចហើយ។",
        "otp_sent": "លេខ OTP ត្រូវបានផ្ញើទៅ <b>{number}</b>។ សូមបញ្ចូល OTP ដើម្បីផ្ទៀងផ្ទាត់។",
        "number_added": "លេខ <b>{number}</b> ត្រូវបានបន្ថែមដោយជោគជ័យ។",
        "invalid_otp": "លេខ OTP មិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។",
    },
    "indonesian": {
        "choose_province": "Silakan pilih provinsi:",
        "more_provinces": "Provinsi lainnya...",
        "case_list": "Daftar kasus:",
        "case_details": "Detail Kasus:",
        "save_case": "Simpan Kasus",
        "found_case": "Kasus Ditemukan",
        "upload_proof": "Mohon unggah foto atau video sebagai bukti:",
        "invalid_proof": "Bukti tidak valid. Mohon unggah foto atau video.",
        "enter_location": "Masukkan lokasi di mana orang tersebut ditemukan:",
        "notify_advertiser": "Pengiklan telah diberitahu. Terima kasih!",
        "province_not_found": "Tidak ada provinsi yang cocok ditemukan. Silakan coba lagi:",
        "province_multi": "Beberapa provinsi ditemukan (Halaman {page} dari {total}):",
        "province_selected": "✅ Dipilih: ",
        "missing_information": "❌ Informasi tidak lengkap. Mohon mulai lagi.",
        "notification_text": (
            "🚨 Peringatan Potensi Kecocokan! 🚨\n\n"
            "Kasus #{case_no}: {person_name}\n"
            "📍 Lokasi Dilaporkan: {location}\n"
            "🔗 File Bukti: {proof_path}"
        ),
        "reply_to_advertiser": "✅ Pemilik kasus telah diberitahu!\n\n"
        "Terima kasih atas kontribusi Anda. Kami akan menghubungi Anda jika informasi lebih lanjut diperlukan.",
        "error_sending_notification": "❌ Kesalahan saat mengirim notifikasi. Mohon coba lagi nanti.",
        "proof_upload": "Mohon unggah bukti foto/video:",
        "error_processing_proof": "❌ Kesalahan saat memproses bukti Anda. Mohon coba lagi.",
        "case_not_found": "❌ Kasus tidak ditemukan.",
        "proof_received": "✅ Bukti diterima. \n \n Mohon masukkan lokasi di mana Anda menemukan orang ini:",
        "error_upload_proof": "❌ Mohon unggah foto atau video.",
        "no_case_selected": "Kesalahan: Tidak ada kasus yang dipilih. Mohon mulai lagi.",
        "error_loading_case": "Kesalahan memuat detail kasus. Mohon coba lagi.",
        "mark_as_found": "✅ Tandai sebagai Ditemukan",
        "back_to_list": "🔙 Kembali ke Daftar",
        "case_not_found_in_province": "Tidak ada kasus yang ditemukan di provinsi ini.",
        "select_province": "Mohon pilih provinsi terlebih dahulu.",
        "no_case_found_in_province": "Tidak ada kasus yang ditemukan untuk {province}.",
        "province_not_exist": "Provinsi tidak ada.",
        "choose_number_or_add_new": "Pilih nomor atau tambahkan yang baru:",
        "add_new_number": "Tambahkan Nomor Baru",
        "enter_new_number": "Mohon masukkan nomor baru:",
        "number_already_exists": "Nomor <b>{number}</b> sudah ada.",
        "otp_sent": "OTP telah dikirim ke <b>{number}</b>. Mohon masukkan OTP untuk verifikasi.",
        "number_added": "Nomor <b>{number}</b> telah berhasil ditambahkan.",
        "invalid_otp": "OTP tidak valid. Mohon coba lagi.",
    }
}


# Count:
