FINDER_CONSTANT = {
    "en": {
        "choose_province": "Please select a province:",
        "more_provinces": "More provinces...",
        "case_list": "Available cases:",
        "case_details": "Case Details:",
        "save_case": "Save Case",
        "found_case": "Found Case",
        "upload_proof": "Please upload a photo or video as proof.",
        "invalid_proof": "Invalid proof. Please upload a photo or video.",
        "enter_location": "Enter the location where the person was found:",
        "notify_advertiser": "The advertiser has been notified. Thank you!",
        "province_not_found": "No matching provinces found. Please try again:",
        "province_multi": "Multiple provinces found (Page {page} of {total}):",
        "province_selected": "You have selected",
        "missing_information": "❌ Missing information. Please start over.",
        "notification_text": (
            "🚨 Potential Match Alert! 🚨\n\n"
            "Case #{case_no}: {person_name}\n"
            "📍 Reported Location: {location}\n"
            "🔗 Proof File: {proof_path}"
        ),
        "reply_to_advertiser": "✅ The case owner has been notified!\n\n"
        "Thank you for your contribution. We'll contact you if more information is needed.",
        "error_sending_notification": "❌ Error sending notification. Please try again later.",
        "proof_upload": "Please upload photo/video proof:",
        "error_processing_proof": "❌ Error processing your proof. Please try again.",
        "case_not_found": "❌ Case not found.",
        "proof_received": "✅ Proof received. \n \n  Please enter the location where you found this person:",
        "error_upload_proof": "❌ Please upload a photo or video.",
        "no_case_selected": "Error: No case selected. Please start over.",
        "error_loading_case": "Error loading case details, Please try again.",
        "mark_as_found": "✅ Mark as Found",
        "back_to_list": "🔙 Back to List",
        "case_not_found_in_province": "No cases found in this province.",
        "select_province": "Please select a province first.",
        "no_case_found_in_province": "No cases found for {province}.",
        # Remaining messages
        "choose_number_or_add_new": "Choose a number or add a new one:",
        "add_new_number": "Add New Number",
        "enter_new_number": "Please enter a new number:",
        "number_already_exists": "The number <b>{number}</b> already exists.",
        "otp_sent": "An OTP has been sent to <b>{number}</b>. Please enter the OTP to verify.",
        "number_added": "The number <b>{number}</b> has been added successfully.",
        "invalid_otp": "Invalid OTP. Please try again.",
    },
    "zh": {
        "choose_province": "请选择省份：",
        "more_provinces": "更多省份...",
        "case_list": "可用案件：",
        "case_details": "案件详情：",
        "save_case": "保存案件",
        "found_case": "找到案件",
        "upload_proof": "请上传照片/视频证据：",
        "invalid_proof": "无效证据。请上传照片/视频。",
        "enter_location": "请输入发现该人的地点：",
        "notify_advertiser": "已通知广告主。谢谢！",
        "province_not_found": "未找到匹配的省份。请重试：",
        "province_multi": "找到多个省份 (第 {page} 页，共 {total} 页)：",
        "province_selected": "已记录省份：",
        "missing_information": "❌ 缺少信息。请重新开始。",
        "notification_text": (
            "🚨 潜在匹配警报！🚨\n\n"
            "案件 #{case_no}: {person_name}\n"
            "📍 报告位置: {location}\n"
            "🔗 证据文件: {proof_path}"
        ),
        "reply_to_advertiser": "✅ 案件所有者已收到通知！\n\n"
        "感谢您的贡献。如果需要更多信息，我们会联系您。",
        "error_sending_notification": "❌ 发送通知时出错。请稍后再试。",
        "proof_upload": "请上传照片/视频证据：",
        "error_processing_proof": "❌ 处理您的证据时出错。请重试。",
        "case_not_found": "❌ 未找到案件。",
        "proof_received": "✅ 证据已收到。\n\n请输入您发现此人的位置：",
        "error_upload_proof": "❌ 请上传照片或视频。",
        "no_case_selected": "错误: 未选择案件。请重新开始。",
        "error_loading_case": "加载案件详情时出错，请重试。",
        "mark_as_found": "✅ 标记为已找到",
        "back_to_list": "🔙 返回列表",
        "case_not_found_in_province": "该省份未找到案件。",
        "select_province": "请先选择一个省份。",
        "no_case_found_in_province": "在 {province} 没有找到相关案件。",
        "choose_number_or_add_new": "选择一个号码或添加新号码：",
        "add_new_number": "添加新号码",
        "enter_new_number": "请输入一个新号码：",
        "number_already_exists": "号码 <b>{number}</b> 已存在。",
        "otp_sent": "已向 <b>{number}</b> 发送验证码。请输入验证码以验证。",
        "number_added": "号码 <b>{number}</b> 已成功添加。",
        "invalid_otp": "无效的验证码。请重试。",
    },
    "ms": {
        "choose_province": "Sila pilih sebuah negeri:",
        "more_provinces": "Negeri lain...",
        "case_list": "Kes yang tersedia:",
        "case_details": "Butiran Kes:",
        "save_case": "Simpan Kes",
        "found_case": "Kes Ditemui",
        "upload_proof": "Sila muat naik gambar atau video sebagai bukti.",
        "invalid_proof": "Bukti tidak sah. Sila muat naik gambar atau video.",
        "enter_location": "Masukkan lokasi di mana orang tersebut ditemui:",
        "notify_advertiser": "Pengiklan telah dimaklumkan. Terima kasih!",
        "province_not_found": "Tiada negeri yang sepadan ditemui. Sila cuba lagi:",
        "province_multi": "Beberapa negeri ditemui (Halaman {page} daripada {total}):",
        "province_selected": "Anda telah memilih",
        "missing_information": "❌ Maklumat tidak lengkap. Sila mulakan semula.",
        "notification_text": (
            "🚨 Notifikasi Padanan Berpotensi! 🚨\n\n"
            "Kes #{case_no}: {person_name}\n"
            "📍 Lokasi Dilaporkan: {location}\n"
            "🔗 Fail Bukti: {proof_path}"
        ),
        "reply_to_advertiser": "✅ Pemilik kes telah dimaklumkan!\n\n"
        "Terima kasih atas sumbangan anda. Kami akan menghubungi anda jika memerlukan maklumat tambahan.",
        "error_sending_notification": "❌ Ralat menghantar notifikasi. Sila cuba lagi kemudian.",
        "proof_upload": "Sila muat naik bukti dalam bentuk gambar/video:",
        "error_processing_proof": "❌ Ralat memproses bukti anda. Sila cuba lagi.",
        "case_not_found": "❌ Kes tidak ditemui.",
        "proof_received": "✅ Bukti diterima. \n \n Sila masukkan lokasi di mana anda menemui orang ini:",
        "error_upload_proof": "❌ Sila muat naik gambar atau video.",
        "no_case_selected": "Ralat: Tiada kes dipilih. Sila mulakan semula.",
        "error_loading_case": "Ralat memuatkan butiran kes, sila cuba lagi.",
        "mark_as_found": "✅ Tandakan Sebagai Ditemui",
        "back_to_list": "🔙 Kembali ke Senarai",
        "case_not_found_in_province": "Tiada kes ditemui di negeri ini.",
        "select_province": "Sila pilih sebuah negeri terlebih dahulu.",
        "no_case_found_in_province": "Tiada kes ditemui untuk {province}.",
        "choose_number_or_add_new": "Pilih nombor atau tambah nombor baru:",
        "add_new_number": "Tambah Nombor Baru",
        "enter_new_number": "Sila masukkan nombor baru:",
        "number_already_exists": "Nombor <b>{number}</b> sudah wujud.",
        "otp_sent": "OTP telah dihantar ke <b>{number}</b>. Sila masukkan OTP untuk pengesahan.",
        "number_added": "Nombor <b>{number}</b> telah berjaya ditambah.",
        "invalid_otp": "OTP tidak sah. Sila cuba lagi.",
    },
}
