GLOBAL_CONSTANT = {
    "english": {
        "lang_button": "🇬🇧 English",
        "invalid_choice": "❌ Invalid choice. Please try again.",
        "invalid_choice_conversation_ended": "Invalid choice. Conversation ended.",
        "prev": "⬅️ Previous",
        "next": "➡️ Next",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Tron Network)",
        "back_to_wallet": "⬅️ Back to Wallets",
        "agree_btn": "✅ I Agree",
        "disagree_btn": "❌ I Disagree",
        "disagree_end": "You did not agree. Conversation ended.",
        "selected": "✅ Selected: ",
        "understood_and_agree": "✅ I Understand and Agree",
        "confirm_button": "✅ Confirm",
        "cancel_button": "❌ Cancel",
        "create_wallet": "➕ Create Wallet",
        "use_existing_wallet": "📂 Use Existing Wallet",
        "continue_case": "➡️ Continue to Case Posting",
        "refresh_wallet": "🔄 Refresh Wallet",
        "cancel_edit_button": "❌ Cancel / Edit",
    },
    "chinese": {
        "lang_button": "🇨🇳 简体中文",
        "invalid_choice": "❌ 无效选择。请再试一次。",
        "invalid_choice_conversation_ended": "无效选择。对话已结束。",
        "prev": "⬅️ 上一页",
        "next": "➡️ 下一页",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - 波场网络)",
        "back_to_wallet": "⬅️ 返回钱包",
        "agree_btn": "✅ 我同意",
        "disagree_btn": "❌ 我不同意",
        "disagree_end": "您未同意。对话已结束。",
        "selected": "✅ 已选择：",
        "understood_and_agree": "✅ 我已理解并同意",
        "confirm_button": "✅ 确认",
        "cancel_button": "❌ 取消",
        "create_wallet": "➕ 创建钱包",
        "use_existing_wallet": "📂 使用现有钱包",
        "continue_case": "➡️ 继续发布寻人信息",
        "refresh_wallet": "🔄 刷新钱包",
        "cancel_edit_button": "❌ 取消 / 编辑",
    },
    "malay": {
        "lang_button": "🇲🇾 Bahasa Malaysia",
        "invalid_choice": "❌ Pilihan tidak sah. Sila cuba lagi.",
        "invalid_choice_conversation_ended": "Pilihan tidak sah. Perbualan tamat.",
        "prev": "⬅️ Sebelumnya",
        "next": "➡️ Seterusnya",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Rangkaian Tron)",
        "back_to_wallet": "⬅️ Kembali ke Dompet",
        "agree_btn": "✅ Saya Setuju",
        "disagree_btn": "❌ Saya Tidak Setuju",
        "disagree_end": "Anda tidak bersetuju. Perbualan tamat.",
        "selected": "✅ Dipilih: ",
        "understood_and_agree": "✅ Saya Faham dan Bersetuju",
        "confirm_button": "✅ Sahkan",
        "cancel_button": "❌ Batal",
        "create_wallet": "➕ Cipta Dompet",
        "use_existing_wallet": "📂 Guna Dompet Sedia Ada",
        "continue_case": "➡️ Teruskan ke Penghantaran Kes",
        "refresh_wallet": "🔄 Segarkan Dompet",
        "cancel_edit_button": "❌ Batal / Edit",
    },
    "thai": {
        "lang_button": "🇹🇭 ภาษาไทย",
        "invalid_choice": "❌ ตัวเลือกไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง",
        "invalid_choice_conversation_ended": "ตัวเลือกไม่ถูกต้อง การสนทนาสิ้นสุดลง",
        "prev": "⬅️ ก่อนหน้า",
        "next": "➡️ ถัดไป",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - เครือข่าย Tron)",
        "back_to_wallet": "⬅️ กลับไปที่กระเป๋าเงิน",
        "agree_btn": "✅ ฉันยอมรับ",
        "disagree_btn": "❌ ฉันไม่ยอมรับ",
        "disagree_end": "คุณไม่ได้ยอมรับ การสนทนาสิ้นสุดลง",
        "selected": "✅ เลือกแล้ว: ",
        "understood_and_agree": "✅ ฉันเข้าใจและยอมรับ",
        "confirm_button": "✅ ยืนยัน",
        "cancel_button": "❌ ยกเลิก",
        "create_wallet": "➕ สร้างกระเป๋าเงิน",
        "use_existing_wallet": "📂 ใช้กระเป๋าเงินที่มีอยู่",
        "continue_case": "➡️ ดำเนินการต่อไปยังการโพสต์กรณี",
        "refresh_wallet": "🔄 รีเฟรชกระเป๋าเงิน",
        "cancel_edit_button": "❌ ยกเลิก / แก้ไข",
    },
    "vietnamese": {
        "lang_button": "🇻🇳 Tiếng Việt",
        "invalid_choice": "❌ Lựa chọn không hợp lệ. Vui lòng thử lại.",
        "invalid_choice_conversation_ended": "Lựa chọn không hợp lệ. Cuộc trò chuyện kết thúc.",
        "prev": "⬅️ Trước",
        "next": "➡️ Tiếp",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Mạng Tron)",
        "back_to_wallet": "⬅️ Quay lại Ví",
        "agree_btn": "✅ Tôi Đồng Ý",
        "disagree_btn": "❌ Tôi Không Đồng Ý",
        "disagree_end": "Bạn không đồng ý. Cuộc trò chuyện kết thúc.",
        "selected": "✅ Đã chọn: ",
        "understood_and_agree": "✅ Tôi Hiểu và Đồng Ý",
        "confirm_button": "✅ Xác Nhận",
        "cancel_button": "❌ Hủy",
        "create_wallet": "➕ Tạo Ví",
        "use_existing_wallet": "📂 Dùng Ví Hiện Có",
        "continue_case": "➡️ Tiếp Tục Đăng Trường Hợp",
        "refresh_wallet": "🔄 Làm Mới Ví",
        "cancel_edit_button": "❌ Hủy / Sửa",
    },
    "urdu": {
        "lang_button": "🇵🇰 اردو",
        "invalid_choice": "❌ غلط انتخاب۔ براہ کرم دوبارہ کوشش کریں۔",
        "invalid_choice_conversation_ended": "غلط انتخاب۔ گفتگو ختم ہو گئی۔",
        "prev": "⬅️ پچھلا",
        "next": "➡️ اگلا",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - ٹرون نیٹ ورک)",
        "back_to_wallet": "⬅️ واپس والیٹ پر",
        "agree_btn": "✅ میں متفق ہوں",
        "disagree_btn": "❌ میں متفق نہیں ہوں",
        "disagree_end": "آپ متفق نہیں ہوئے۔ گفتگو ختم ہو گئی۔",
        "selected": "✅ منتخب: ",
        "understood_and_agree": "✅ میں سمجھتا ہوں اور متفق ہوں",
        "confirm_button": "✅ تصدیق کریں",
        "cancel_button": "❌ منسوخ کریں",
        "create_wallet": "➕ والیٹ بنائیں",
        "use_existing_wallet": "📂 موجودہ والیٹ استعمال کریں",
        "continue_case": "➡️ کیس پوسٹ کرنے کے لیے جاری رکھیں",
        "refresh_wallet": "🔄 والیٹ تازہ کاری کریں",
        "cancel_edit_button": "❌ منسوخ کریں / ترمیم کریں",
    },
    "japanese": {
        "lang_button": "🇯🇵 日本語",
        "invalid_choice": "❌ 無効な選択です。もう一度試してください。",
        "invalid_choice_conversation_ended": "無効な選択です。会話を終了します。",
        "prev": "⬅️ 前へ",
        "next": "➡️ 次へ",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Tronネットワーク)",
        "back_to_wallet": "⬅️ ウォレットに戻る",
        "agree_btn": "✅ 同意します",
        "disagree_btn": "❌ 同意しません",
        "disagree_end": "同意しませんでした。会話を終了します。",
        "selected": "✅ 選択済み: ",
        "understood_and_agree": "✅ 理解し、同意します",
        "confirm_button": "✅ 確認",
        "cancel_button": "❌ キャンセル",
        "create_wallet": "➕ ウォレットを作成",
        "use_existing_wallet": "📂 既存のウォレットを使用",
        "continue_case": "➡️ ケース投稿へ進む",
        "refresh_wallet": "🔄 ウォレットを更新",
        "cancel_edit_button": "❌ キャンセル / 編集",
    },
    "korean": {
        "lang_button": "🇰🇷 한국어",
        "invalid_choice": "❌ 잘못된 선택입니다. 다시 시도하세요.",
        "invalid_choice_conversation_ended": "잘못된 선택입니다. 대화가 종료됩니다.",
        "prev": "⬅️ 이전",
        "next": "➡️ 다음",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Tron 네트워크)",
        "back_to_wallet": "⬅️ 지갑으로 돌아가기",
        "agree_btn": "✅ 동의합니다",
        "disagree_btn": "❌ 동의하지 않습니다",
        "disagree_end": "동의하지 않았습니다. 대화가 종료됩니다.",
        "selected": "✅ 선택됨: ",
        "understood_and_agree": "✅ 이해했으며 동의합니다",
        "confirm_button": "✅ 확인",
        "cancel_button": "❌ 취소",
        "create_wallet": "➕ 지갑 생성",
        "use_existing_wallet": "📂 기존 지갑 사용",
        "continue_case": "➡️ 사례 등록 계속하기",
        "refresh_wallet": "🔄 지갑 새로고침",
        "cancel_edit_button": "❌ 취소 / 수정",
    },
    "indonesian": {
        "lang_button": "🇮🇩 Bahasa Indonesia",
        "invalid_choice": "❌ Pilihan tidak valid. Silakan coba lagi.",
        "invalid_choice_conversation_ended": "Pilihan tidak valid. Percakapan diakhiri.",
        "prev": "⬅️ Sebelumnya",
        "next": "➡️ Berikutnya",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Jaringan Tron)",
        "back_to_wallet": "⬅️ Kembali ke Dompet",
        "agree_btn": "✅ Saya Setuju",
        "disagree_btn": "❌ Saya Tidak Setuju",
        "disagree_end": "Anda tidak menyetujui. Percakapan diakhiri.",
        "selected": "✅ Terpilih: ",
        "understood_and_agree": "✅ Saya Mengerti dan Setuju",
        "confirm_button": "✅ Konfirmasi",
        "cancel_button": "❌ Batalkan",
        "create_wallet": "➕ Buat Dompet",
        "use_existing_wallet": "📂 Gunakan Dompet yang Ada",
        "continue_case": "➡️ Lanjut ke Posting Kasus",
        "refresh_wallet": "🔄 Segarkan Dompet",
        "cancel_edit_button": "❌ Batalkan / Edit",
    },
    "khmer": {
        "lang_button": "🇰🇭 ភាសាខ្មែរ",
        "invalid_choice": "❌ ជម្រើសមិនត្រឹមត្រូវទេ។ សូមព្យាយាមម្ដងទៀត។",
        "invalid_choice_conversation_ended": "ជម្រើសមិនត្រឹមត្រូវទេ។ ការសន្ទនាត្រូវបានបញ្ចប់។",
        "prev": "⬅️ មុន",
        "next": "➡️ បន្ទាប់",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - បណ្តាញ Tron)",
        "back_to_wallet": "⬅️ ត្រឡប់ទៅកាបូបវិញ",
        "agree_btn": "✅ ខ្ញុំយល់ព្រម",
        "disagree_btn": "❌ ខ្ញុំមិនយល់ព្រម",
        "disagree_end": "អ្នកមិនយល់ព្រម។ ការសន្ទនាត្រូវបានបញ្ចប់។",
        "selected": "✅ បានជ្រើសរើស៖ ",
        "understood_and_agree": "✅ ខ្ញុំយល់ និងយល់ព្រម",
        "confirm_button": "✅ បញ្ជាក់",
        "cancel_button": "❌ លុបចោល",
        "create_wallet": "➕ បង្កើតកាបូប",
        "use_existing_wallet": "📂 ប្រើកាបូបដែលមានស្រាប់",
        "continue_case": "➡️ បន្តទៅការបង្ហោះករណី",
        "refresh_wallet": "🔄 ធ្វើអាប់ដេតកាបូប",
        "cancel_edit_button": "❌ លុប / កែសម្រួល",
    },
}
