LISTING_CONSTANT = {
    "en": {
        "no_advertise_cases": "No ADVERTISE cases found.",
        "select_case_details": "📋 **Select a Case to View Details:**",
        "case_not_found": "❌ Case not found.",
        "error_fetching_cases": "An error occurred while fetching cases.",
        "error_fetching_case_details": "❌ An error occurred while fetching case details.",
        "error_paginating_cases": "❌ An error occurred while paginating cases.",
        "invalid_case_id": "❌ Invalid case ID.",
        "not_authorized_edit": "❌ You are not authorized to edit this case.",
        "not_authorized_delete": "❌ You are not authorized to delete this case.",
        "case_deleted_successfully": "✅ Case has been successfully deleted.",
        "edit_canceled": "📋 Edit canceled. Returning to case listing.",
        "enter_new_value": "✏️ Please enter the new value for **{field_name}**: ",
        "field_updated_successfully": "✅ **{field_name}** updated to: **{new_value}**",
        "invalid_value": "❌ {error_message} Please enter a valid value.",
        "edit_field_prompt": "📝 **Which field would you like to edit?**",
        "cancel_edit_button": "Cancel",
        "edit_button": "📝 Edit",
        "delete_button": "🗑 Delete",
        "previous_button": "⬅️ Previous",
        "next_button": "➡️ Next",
        "editable_fields": {
            "Name": "name",
            "Person Name": "person_name",
            "Relationship": "relationship",
            "Last Seen Location": "last_seen_location",
            "Gender": "gender",
            "Age": "age",
            "Hair Color": "hair_color",
            "Eye Color": "eye_color",
            "Height": "height",
            "Weight": "weight",
            "Distinctive Features": "distinctive_features",
            "Country": "country",
            "City": "city",
        },
        "case_details_template": (
            "📌 **Case Details**\n"
            "👤 **Person Name:** {person_name}\n"
            "📍 **Last Seen Location:** {last_seen_location}\n"
            "💰 **Reward:** {reward} {reward_type}\n"
            "💼 **Wallet:** {wallet}\n"
            "👤 **Gender:** {gender}\n"
            "🧒 **Age:** {age}\n"
            "📏 **Height:** {height} cm\n"
        ),
        "invalid_reward_amount": "❌ Invalid reward amount. Maximum reward amount is {max_amount}.",
        "reward_success": "✅ Reward successfully sent to finder {finder_id}.",
        "error_transferring_reward": "❌ An error occurred while transferring reward.",
        "case_or_finder_not_found": "❌ Case or finder not found.",
        "no_finders_for_case": "❌ No finders found for this case.",
        "finder_list_header": "👤 **Finders for this case:**",
        "reward_this_finder": "💰 Reward this finder",
        "enter_reward_amount": "✏️ Please enter the reward amount for this case (max {max_amount}): ",
        "reward_confirmation": "Are you sure you want to send {amount} reward to Finder ID {finder_id} for Case {case_no}?",
        "reward_cancelled": "Reward process cancelled",
        "confirm_button": "✅ Confirm",
        "cancel_button": "❌ Cancel",
        # ----- Delete Start ------
        "case_not_found": "⚠️ Case not found.",
        "not_authorized_delete": "🚫 You are not authorized to delete this case.",
        "case_deleted_successfully": "✅ Case has been successfully deleted.",
        "confirm_delete": "❗ Are you sure you want to delete this case?",
        "yes": "✅ Yes",
        "no": "❌ No",
        "delete_cancelled": "❌ Case deletion has been cancelled.",
        "error_deleting_case": "⚠️ An error occurred while deleting the case. Please try again.",
        # ----- Delete End ------
        # ----------- Extend Reward Constants ----------
        "extend_reward_button": "Extend Reward ➕",
        "extend_reward_not_found": "❌ No active reward extension request found.",
        "insufficient_funds": "❌ Insufficient funds in your {wallet_type} wallet. Required: {required_amount}",
        "extend_reward_confirmation": (
            "🔄 *Confirm Reward Extension*\n\n"
            "💰 Amount: {amount} {wallet_type}\n"
            "📤 From: `{from_wallet}`\n"
            "📥 To: `{to_wallet}`\n"
            "Are you sure you want to proceed?"
        ),
        "extend_success": "✅ Successfully extended {amount} {wallet_type} reward!",
        "extend_cancelled": "❌ Reward extension cancelled.",
        "transfer_failed": "❌ Transfer failed. Please check wallet balances and try again.",
        "case_or_extend_not_found": "❌ Case or extension request not found.",
        "no_wallet_found": "❌ No wallets found for the selected type.",
        "insufficient_funds_after_selection": "❌ Insufficient funds in the selected wallet.",
        "extend_already_completed": "⚠️ This extend reward request has already been completed.",
        "error_processing_extend": "❌ An error occurred while processing the extend reward request.",
        "error_approving_extend": "❌ An error occurred while approving the extend reward request.",
        "case_not_found": "❌ Case not found.",
        "extend_reward_not_found": "❌ No pending extend reward requests found for this case.",
        "select_wallet_for_extend": (
            "🔄 *Select Wallet for Reward Extension*\n\n"
            "💰 Amount: {amount} {wallet_type}\n"
            "📤 From: `{from_wallet}`\n"
            "📥 To: `{to_wallet}`\n\n"
            "Please select a wallet from the options below:"
        ),
    },
  "zh": {
    "no_advertise_cases": "未找到广告案件。",
    "select_case_details": "📋 **选择一个案件以查看详情：**",
    "case_not_found": "❌ 未找到案件。",
    "error_fetching_cases": "获取案件时发生错误。",
    "error_fetching_case_details": "❌ 获取案件详情时发生错误。",
    "error_paginating_cases": "❌ 分页获取案件时发生错误。",
    "invalid_case_id": "❌ 无效的案件ID。",
    "not_authorized_edit": "❌ 您没有权限编辑此案件。",
    "not_authorized_delete": "❌ 您没有权限删除此案件。",
    "case_deleted_successfully": "✅ 案件已成功删除。",
    "edit_canceled": "📋 编辑已取消。返回案件列表。",
    "enter_new_value": "✏️ 请输入**{field_name}**的新值：",
    "field_updated_successfully": "✅ **{field_name}**已更新为：**{new_value}**",
    "invalid_value": "❌ {error_message} 请输入有效的值。",
    "edit_field_prompt": "📝 **您想编辑哪个字段？**",
    "cancel_edit_button": "取消",
    "edit_button": "📝 编辑",
    "delete_button": "🗑 删除",
    "previous_button": "⬅️ 上一页",
    "next_button": "➡️ 下一页",
    "editable_fields": {
      "Name": "name",
      "Person Name": "person_name",
      "Relationship": "relationship",
      "Last Seen Location": "last_seen_location",
      "Gender": "gender",
      "Age": "age",
      "Hair Color": "hair_color",
      "Eye Color": "eye_color",
      "Height": "height",
      "Weight": "weight",
      "Distinctive Features": "distinctive_features",
      "Country": "country",
      "City": "city"
    },
    "case_details_template": "📌 **案件详情**\n👤 **姓名：** {person_name}\n📍 **最后见到的位置：** {last_seen_location}\n💰 **奖励：** {reward} {reward_type}\n💼 **钱包：** {wallet}\n👤 **性别：** {gender}\n🧒 **年龄：** {age}\n📏 **身高：** {height} cm\n",
    "invalid_reward_amount": "❌ 无效的奖励金额。最大奖励金额为{max_amount}。",
    "reward_success": "✅ 奖励已成功发送给寻人者{finder_id}。",
    "error_transferring_reward": "❌ 转账奖励时发生错误。",
    "case_or_finder_not_found": "❌ 未找到案件或寻人者。",
    "no_finders_for_case": "❌ 未找到该案件的寻人者。",
    "finder_list_header": "👤 **此案件的寻人者：**",
    "reward_this_finder": "💰 奖励给此寻人者",
    "enter_reward_amount": "✏️ 请输入该案件的奖励金额（最大 {max_amount}）：",
    "reward_confirmation": "您确定要将{amount}奖励发送给寻人者ID {finder_id}用于案件{case_no}吗？",
    "reward_cancelled": "奖励过程已取消。",
    "confirm_button": "✅ 确认",
    "cancel_button": "❌ 取消",
    "confirm_delete": "❗ 您确定要删除此案件吗？",
    "yes": "✅ 是",
    "no": "❌ 否",
    "delete_cancelled": "❌ 案件删除已取消。",
    "error_deleting_case": "⚠️ 删除案件时发生错误。请再试一次。",
    "extend_reward_button": "延长奖励 ➕",
    "extend_reward_not_found": "❌ 未找到活动奖励扩展请求。",
    "insufficient_funds": "❌ 您的{wallet_type}钱包余额不足。所需金额：{required_amount}",
    "extend_reward_confirmation": "🔄 *确认奖励扩展*\n\n💰 金额：{amount} {wallet_type}\n📤 从：`{from_wallet}`\n📥 到：`{to_wallet}`\n您确定要继续吗？",
    "extend_success": "✅ 成功延长了{amount} {wallet_type}奖励！",
    "extend_cancelled": "❌ 奖励延长已取消。",
    "transfer_failed": "❌ 转账失败。请检查钱包余额并再试一次。",
    "case_or_extend_not_found": "❌ 未找到案件或扩展请求。",
    "no_wallet_found": "❌ 未找到所选类型的钱包。",
    "insufficient_funds_after_selection": "❌ 选定钱包余额不足。",
    "extend_already_completed": "⚠️ 此扩展奖励请求已完成。",
    "error_processing_extend": "❌ 处理扩展奖励请求时发生错误。",
    "error_approving_extend": "❌ 批准扩展奖励请求时发生错误。",
    "case_not_found": "❌ 未找到案件。",
    "extend_reward_not_found": "❌ 未找到此案件的待处理扩展奖励请求。",
    "select_wallet_for_extend": "🔄 *选择用于奖励扩展的钱包*\n\n💰 金额：{amount} {wallet_type}\n📤 从：`{from_wallet}`\n📥 到：`{to_wallet}`\n\n请选择以下选项中的一个钱包："
  },
  "ms": {
    "no_advertise_cases": "Tiada kes IKLAN yang dijumpai.",
    "select_case_details": "📋 **Pilih Kes untuk Lihat Butiran:**",
    "case_not_found": "❌ Kes tidak dijumpai.",
    "error_fetching_cases": "Ralat berlaku semasa mengambil kes.",
    "error_fetching_case_details": "❌ Ralat berlaku semasa mengambil butiran kes.",
    "error_paginating_cases": "❌ Ralat berlaku semasa memaparkan kes.",
    "invalid_case_id": "❌ ID kes tidak sah.",
    "not_authorized_edit": "❌ Anda tidak dibenarkan untuk mengedit kes ini.",
    "not_authorized_delete": "❌ Anda tidak dibenarkan untuk memadam kes ini.",
    "case_deleted_successfully": "✅ Kes telah berjaya dipadam.",
    "edit_canceled": "📋 Pengeditan dibatalkan. Kembali ke senarai kes.",
    "enter_new_value": "✏️ Sila masukkan nilai baru untuk **{field_name}**: ",
    "field_updated_successfully": "✅ **{field_name}** dikemas kini kepada: **{new_value}**",
    "invalid_value": "❌ {error_message} Sila masukkan nilai yang sah.",
    "edit_field_prompt": "📝 **Field mana yang ingin anda edit?**",
    "cancel_edit_button": "Batal",
    "edit_button": "📝 Edit",
    "delete_button": "🗑 Padam",
    "previous_button": "⬅️ Sebelumnya",
    "next_button": "➡️ Seterusnya",
    "editable_fields": {
      "Name": "name",
      "Person Name": "person_name",
      "Relationship": "relationship",
      "Last Seen Location": "last_seen_location",
      "Gender": "gender",
      "Age": "age",
      "Hair Color": "hair_color",
      "Eye Color": "eye_color",
      "Height": "height",
      "Weight": "weight",
      "Distinctive Features": "distinctive_features",
      "Country": "country",
      "City": "city"
    },
    "case_details_template": "📌 **Butiran Kes**\n👤 **Nama Orang:** {person_name}\n📍 **Lokasi Terakhir Dilihat:** {last_seen_location}\n💰 **Ganjaran:** {reward} {reward_type}\n💼 **Dompet:** {wallet}\n👤 **Jantina:** {gender}\n🧒 **Umur:** {age}\n📏 **Tinggi:** {height} cm\n",
    "invalid_reward_amount": "❌ Jumlah ganjaran tidak sah. Jumlah ganjaran maksimum adalah {max_amount}.",
    "reward_success": "✅ Ganjaran berjaya dihantar kepada pencari {finder_id}.",
    "error_transferring_reward": "❌ Ralat berlaku semasa memindahkan ganjaran.",
    "case_or_finder_not_found": "❌ Kes atau pencari tidak dijumpai.",
    "no_finders_for_case": "❌ Tiada pencari dijumpai untuk kes ini.",
    "finder_list_header": "👤 **Pencari untuk kes ini:**",
    "reward_this_finder": "💰 Ganjaran untuk pencari ini",
    "enter_reward_amount": "✏️ Sila masukkan jumlah ganjaran untuk kes ini (maksimum {max_amount}): ",
    "reward_confirmation": "Adakah anda pasti mahu menghantar ganjaran {amount} kepada Pencari ID {finder_id} untuk Kes {case_no}?",
    "reward_cancelled": "Proses ganjaran dibatalkan",
    "confirm_button": "✅ Sahkan",
    "cancel_button": "❌ Batal",
    "confirm_delete": "❗ Adakah anda pasti mahu memadamkan kes ini?",
    "yes": "✅ Ya",
    "no": "❌ Tidak",
    "delete_cancelled": "❌ Penghapusan kes dibatalkan.",
    "error_deleting_case": "⚠️ Ralat berlaku semasa menghapuskan kes. Sila cuba lagi.",
    "extend_reward_button": "Lanjutkan Ganjaran ➕",
    "extend_reward_not_found": "❌ Tiada permintaan lanjutan ganjaran aktif dijumpai.",
    "insufficient_funds": "❌ Dana tidak mencukupi dalam dompet {wallet_type} anda. Diperlukan: {required_amount}",
    "extend_reward_confirmation": "🔄 *Sahkan Lanjutan Ganjaran*\n\n💰 Jumlah: {amount} {wallet_type}\n📤 Dari: `{from_wallet}`\n📥 Kepada: `{to_wallet}`\nAdakah anda pasti ingin meneruskan?",
    "extend_success": "✅ Ganjaran {amount} {wallet_type} berjaya dilanjutkan!",
    "extend_cancelled": "❌ Lanjutan ganjaran dibatalkan.",
    "transfer_failed": "❌ Pemindahan gagal. Sila semak baki dompet dan cuba lagi.",
    "case_or_extend_not_found": "❌ Kes atau permintaan lanjutan tidak dijumpai.",
    "no_wallet_found": "❌ Tiada dompet dijumpai untuk jenis yang dipilih.",
    "insufficient_funds_after_selection": "❌ Dana tidak mencukupi dalam dompet yang dipilih.",
    "extend_already_completed": "⚠️ Permintaan lanjutan ganjaran ini telah selesai.",
    "error_processing_extend": "❌ Ralat berlaku semasa memproses permintaan lanjutan ganjaran.",
    "error_approving_extend": "❌ Ralat berlaku semasa meluluskan permintaan lanjutan ganjaran.",
    "case_not_found": "❌ Kes tidak dijumpai.",
    "extend_reward_not_found": "❌ Tiada permintaan lanjutan ganjaran tertunda dijumpai untuk kes ini.",
    "select_wallet_for_extend": "🔄 *Pilih Dompet untuk Lanjutan Ganjaran*\n\n💰 Jumlah: {amount} {wallet_type}\n📤 Dari: `{from_wallet}`\n📥 Kepada: `{to_wallet}`\n\nSila pilih dompet dari pilihan berikut:"
  },
   "th": {
    "no_advertise_cases": "ไม่พบกรณีโฆษณา",
    "select_case_details": "📋 **เลือกกรณีเพื่อดูรายละเอียด:**",
    "case_not_found": "❌ ไม่พบกรณี",
    "error_fetching_cases": "เกิดข้อผิดพลาดขณะดึงกรณี",
    "error_fetching_case_details": "❌ เกิดข้อผิดพลาดขณะดึงรายละเอียดกรณี",
    "error_paginating_cases": "❌ เกิดข้อผิดพลาดขณะแบ่งหน้ากรณี",
    "invalid_case_id": "❌ รหัสกรณีไม่ถูกต้อง",
    "not_authorized_edit": "❌ คุณไม่มีสิทธิ์แก้ไขกรณีนี้",
    "not_authorized_delete": "❌ คุณไม่มีสิทธิ์ลบกรณีนี้",
    "case_deleted_successfully": "✅ ลบกรณีสำเร็จ",
    "edit_canceled": "📋 ยกเลิกการแก้ไข กำลังกลับไปที่รายการกรณี",
    "enter_new_value": "✏️ กรุณากรอกค่าฉบับใหม่สำหรับ **{field_name}**: ",
    "field_updated_successfully": "✅ **{field_name}** ได้รับการอัปเดตเป็น: **{new_value}**",
    "invalid_value": "❌ {error_message} กรุณากรอกค่าที่ถูกต้อง",
    "edit_field_prompt": "📝 **คุณต้องการแก้ไขฟิลด์ใด?**",
    "cancel_edit_button": "ยกเลิก",
    "edit_button": "📝 แก้ไข",
    "delete_button": "🗑 ลบ",
    "previous_button": "⬅️ ก่อนหน้า",
    "next_button": "➡️ ถัดไป",
    "editable_fields": {
      "Name": "name",
      "Person Name": "person_name",
      "Relationship": "relationship",
      "Last Seen Location": "last_seen_location",
      "Gender": "gender",
      "Age": "age",
      "Hair Color": "hair_color",
      "Eye Color": "eye_color",
      "Height": "height",
      "Weight": "weight",
      "Distinctive Features": "distinctive_features",
      "Country": "country",
      "City": "city"
    },
    "case_details_template": "📌 **รายละเอียดกรณี**\n👤 **ชื่อบุคคล:** {person_name}\n📍 **สถานที่ที่พบครั้งสุดท้าย:** {last_seen_location}\n💰 **รางวัล:** {reward} {reward_type}\n💼 **กระเป๋าสตางค์:** {wallet}\n👤 **เพศ:** {gender}\n🧒 **อายุ:** {age}\n📏 **ความสูง:** {height} ซม.\n",
    "invalid_reward_amount": "❌ จำนวนรางวัลไม่ถูกต้อง จำนวนรางวัลสูงสุดคือ {max_amount}",
    "reward_success": "✅ รางวัลถูกส่งไปยังผู้หาผลประโยชน์ {finder_id} สำเร็จ",
    "error_transferring_reward": "❌ เกิดข้อผิดพลาดขณะโอนรางวัล",
    "case_or_finder_not_found": "❌ ไม่พบกรณีหรือผู้หาผลประโยชน์",
    "no_finders_for_case": "❌ ไม่พบผู้หาผลประโยชน์สำหรับกรณีนี้",
    "finder_list_header": "👤 **ผู้หาผลประโยชน์สำหรับกรณีนี้:**",
    "reward_this_finder": "💰 มอบรางวัลให้กับผู้หาผลประโยชน์นี้",
    "enter_reward_amount": "✏️ กรุณากรอกจำนวนรางวัลสำหรับกรณีนี้ (สูงสุด {max_amount}): ",
    "reward_confirmation": "คุณแน่ใจหรือไม่ว่าต้องการส่งรางวัล {amount} ให้กับผู้หาผลประโยชน์ ID {finder_id} สำหรับกรณี {case_no}?",
    "reward_cancelled": "กระบวนการรางวัลถูกยกเลิก",
    "confirm_button": "✅ ยืนยัน",
    "cancel_button": "❌ ยกเลิก",
    "confirm_delete": "❗ คุณแน่ใจหรือไม่ว่าต้องการลบกรณีนี้?",
    "yes": "✅ ใช่",
    "no": "❌ ไม่",
    "delete_cancelled": "❌ การลบกรณีถูกยกเลิก",
    "error_deleting_case": "⚠️ เกิดข้อผิดพลาดขณะลบกรณี กรุณาลองใหม่",
    "extend_reward_button": "ขยายรางวัล ➕",
    "extend_reward_not_found": "❌ ไม่พบคำขอขยายรางวัลที่ใช้งานอยู่",
    "insufficient_funds": "❌ เงินไม่พอในกระเป๋าสตางค์ {wallet_type} ของคุณ ต้องการ: {required_amount}",
    "extend_reward_confirmation": "🔄 *ยืนยันการขยายรางวัล*\n\n💰 จำนวน: {amount} {wallet_type}\n📤 จาก: `{from_wallet}`\n📥 ถึง: `{to_wallet}`\nคุณแน่ใจหรือไม่ว่าต้องการดำเนินการ?",
    "extend_success": "✅ ขยายรางวัล {amount} {wallet_type} สำเร็จ!",
    "extend_cancelled": "❌ การขยายรางวัลถูกยกเลิก",
    "transfer_failed": "❌ การโอนล้มเหลว กรุณาตรวจสอบยอดเงินในกระเป๋าสตางค์และลองใหม่",
    "case_or_extend_not_found": "❌ ไม่พบกรณีหรือคำขอขยายรางวัล",
    "no_wallet_found": "❌ ไม่พบกระเป๋าสตางค์สำหรับประเภทที่เลือก",
    "insufficient_funds_after_selection": "❌ เงินในกระเป๋าสตางค์ที่เลือกไม่พอ",
    "extend_already_completed": "⚠️ คำขอขยายรางวัลนี้ได้รับการดำเนินการแล้ว",
    "error_processing_extend": "❌ เกิดข้อผิดพลาดขณะดำเนินการขยายรางวัล",
    "error_approving_extend": "❌ เกิดข้อผิดพลาดขณะอนุมัติคำขอขยายรางวัล",
    "case_not_found": "❌ ไม่พบกรณี",
    "extend_reward_not_found": "❌ ไม่พบคำขอขยายรางวัลที่ค้างอยู่สำหรับกรณีนี้",
    "select_wallet_for_extend": "🔄 *เลือกกระเป๋าสตางค์สำหรับการขยายรางวัล*\n\n💰 จำนวน: {amount} {wallet_type}\n📤 จาก: `{from_wallet}`\n📥 ถึง: `{to_wallet}`\n\nกรุณาเลือกกระเป๋าสตางค์จากตัวเลือกด้านล่าง:"
  },
    "vi": {
    "no_advertise_cases": "Không tìm thấy trường hợp quảng cáo.",
    "select_case_details": "📋 **Chọn một trường hợp để xem chi tiết:**",
    "case_not_found": "❌ Không tìm thấy trường hợp.",
    "error_fetching_cases": "Đã xảy ra lỗi khi lấy trường hợp.",
    "error_fetching_case_details": "❌ Đã xảy ra lỗi khi lấy chi tiết trường hợp.",
    "error_paginating_cases": "❌ Đã xảy ra lỗi khi phân trang các trường hợp.",
    "invalid_case_id": "❌ Mã trường hợp không hợp lệ.",
    "not_authorized_edit": "❌ Bạn không có quyền chỉnh sửa trường hợp này.",
    "not_authorized_delete": "❌ Bạn không có quyền xóa trường hợp này.",
    "case_deleted_successfully": "✅ Trường hợp đã được xóa thành công.",
    "edit_canceled": "📋 Chỉnh sửa đã bị hủy. Đang quay lại danh sách trường hợp.",
    "enter_new_value": "✏️ Vui lòng nhập giá trị mới cho **{field_name}**: ",
    "field_updated_successfully": "✅ **{field_name}** đã được cập nhật thành: **{new_value}**",
    "invalid_value": "❌ {error_message} Vui lòng nhập giá trị hợp lệ.",
    "edit_field_prompt": "📝 **Bạn muốn chỉnh sửa trường nào?**",
    "cancel_edit_button": "Hủy bỏ",
    "edit_button": "📝 Chỉnh sửa",
    "delete_button": "🗑 Xóa",
    "previous_button": "⬅️ Trước",
    "next_button": "➡️ Tiếp theo",
    "editable_fields": {
      "Name": "name",
      "Person Name": "person_name",
      "Relationship": "relationship",
      "Last Seen Location": "last_seen_location",
      "Gender": "gender",
      "Age": "age",
      "Hair Color": "hair_color",
      "Eye Color": "eye_color",
      "Height": "height",
      "Weight": "weight",
      "Distinctive Features": "distinctive_features",
      "Country": "country",
      "City": "city"
    },
    "case_details_template": "📌 **Chi tiết trường hợp**\n👤 **Tên người:** {person_name}\n📍 **Vị trí lần cuối nhìn thấy:** {last_seen_location}\n💰 **Phần thưởng:** {reward} {reward_type}\n💼 **Ví tiền:** {wallet}\n👤 **Giới tính:** {gender}\n🧒 **Tuổi:** {age}\n📏 **Chiều cao:** {height} cm\n",
    "invalid_reward_amount": "❌ Số tiền thưởng không hợp lệ. Số tiền thưởng tối đa là {max_amount}.",
    "reward_success": "✅ Phần thưởng đã được gửi thành công cho người tìm {finder_id}.",
    "error_transferring_reward": "❌ Đã xảy ra lỗi khi chuyển phần thưởng.",
    "case_or_finder_not_found": "❌ Không tìm thấy trường hợp hoặc người tìm.",
    "no_finders_for_case": "❌ Không tìm thấy người tìm cho trường hợp này.",
    "finder_list_header": "👤 **Người tìm cho trường hợp này:**",
    "reward_this_finder": "💰 Thưởng cho người tìm này",
    "enter_reward_amount": "✏️ Vui lòng nhập số tiền thưởng cho trường hợp này (tối đa {max_amount}): ",
    "reward_confirmation": "Bạn có chắc chắn muốn gửi phần thưởng {amount} cho Người tìm ID {finder_id} cho Trường hợp {case_no}?",
    "reward_cancelled": "Quá trình thưởng đã bị hủy.",
    "confirm_button": "✅ Xác nhận",
    "cancel_button": "❌ Hủy bỏ",
    "confirm_delete": "❗ Bạn có chắc chắn muốn xóa trường hợp này?",
    "yes": "✅ Có",
    "no": "❌ Không",
    "delete_cancelled": "❌ Quá trình xóa trường hợp đã bị hủy.",
    "error_deleting_case": "⚠️ Đã xảy ra lỗi khi xóa trường hợp. Vui lòng thử lại.",
    "extend_reward_button": "Mở rộng phần thưởng ➕",
    "extend_reward_not_found": "❌ Không tìm thấy yêu cầu mở rộng phần thưởng đang hoạt động.",
    "insufficient_funds": "❌ Không đủ tiền trong ví {wallet_type} của bạn. Cần: {required_amount}",
    "extend_reward_confirmation": "🔄 *Xác nhận mở rộng phần thưởng*\n\n💰 Số tiền: {amount} {wallet_type}\n📤 Từ: `{from_wallet}`\n📥 Đến: `{to_wallet}`\nBạn có chắc chắn muốn tiếp tục?",
    "extend_success": "✅ Đã mở rộng phần thưởng {amount} {wallet_type} thành công!",
    "extend_cancelled": "❌ Quá trình mở rộng phần thưởng đã bị hủy.",
    "transfer_failed": "❌ Chuyển tiền thất bại. Vui lòng kiểm tra số dư ví và thử lại.",
    "case_or_extend_not_found": "❌ Không tìm thấy trường hợp hoặc yêu cầu mở rộng.",
    "no_wallet_found": "❌ Không tìm thấy ví cho loại đã chọn.",
    "insufficient_funds_after_selection": "❌ Không đủ tiền trong ví đã chọn.",
    "extend_already_completed": "⚠️ Yêu cầu mở rộng phần thưởng này đã hoàn thành.",
    "error_processing_extend": "❌ Đã xảy ra lỗi khi xử lý yêu cầu mở rộng phần thưởng.",
    "error_approving_extend": "❌ Đã xảy ra lỗi khi phê duyệt yêu cầu mở rộng phần thưởng.",
    "case_not_found": "❌ Không tìm thấy trường hợp.",
    "extend_reward_not_found": "❌ Không tìm thấy yêu cầu mở rộng phần thưởng chưa hoàn thành cho trường hợp này.",
    "select_wallet_for_extend": "🔄 *Chọn ví để mở rộng phần thưởng*\n\n💰 Số tiền: {amount} {wallet_type}\n📤 Từ: `{from_wallet}`\n📥 Đến: `{to_wallet}`\n\nVui lòng chọn ví từ các tùy chọn dưới đây:"
  }
  ,
  "ur": {
  "no_advertise_cases": "کوئی اشتہار کیس نہیں ملا۔",
  "select_case_details": "📋 **تفصیل دیکھنے کے لئے کیس منتخب کریں:**",
  "case_not_found": "❌ کیس نہیں ملا۔",
  "error_fetching_cases": "کیس حاصل کرنے میں غلطی ہوئی۔",
  "error_fetching_case_details": "❌ کیس کی تفصیلات حاصل کرنے میں غلطی ہوئی۔",
  "error_paginating_cases": "❌ کیس کی صفحہ بندی میں غلطی ہوئی۔",
  "invalid_case_id": "❌ کیس کا آئی ڈی غلط ہے۔",
  "not_authorized_edit": "❌ آپ کو اس کیس میں ترمیم کرنے کی اجازت نہیں ہے۔",
  "not_authorized_delete": "❌ آپ کو اس کیس کو حذف کرنے کی اجازت نہیں ہے۔",
  "case_deleted_successfully": "✅ کیس کامیابی سے حذف کر دیا گیا۔",
  "edit_canceled": "📋 ترمیم منسوخ کر دی گئی۔ کیس کی فہرست میں واپس جا رہے ہیں۔",
  "enter_new_value": "✏️ براہ کرم **{field_name}** کے لئے نیا قدر درج کریں: ",
  "field_updated_successfully": "✅ **{field_name}** کو اپ ڈیٹ کر دیا گیا: **{new_value}**",
  "invalid_value": "❌ {error_message} براہ کرم درست قدر درج کریں۔",
  "edit_field_prompt": "📝 **آپ کون سی فیلڈ کو ایڈیٹ کرنا چاہتے ہیں؟**",
  "cancel_edit_button": "منسوخ کریں",
  "edit_button": "📝 ترمیم کریں",
  "delete_button": "🗑 حذف کریں",
  "previous_button": "⬅️ پچھلا",
  "next_button": "➡️ اگلا",
  "editable_fields": {
    "Name": "نام",
    "Person Name": "شخص کا نام",
    "Relationship": "رشتہ",
    "Last Seen Location": "آخری بار کہاں دیکھا گیا",
    "Gender": "جنس",
    "Age": "عمر",
    "Hair Color": "بالوں کا رنگ",
    "Eye Color": "آنکھوں کا رنگ",
    "Height": "قد",
    "Weight": "وزن",
    "Distinctive Features": "خصوصی خصوصیات",
    "Country": "ملک",
    "City": "شہر"
  },
  "case_details_template": "📌 **کیس کی تفصیل**\n👤 **شخص کا نام:** {person_name}\n📍 **آخری بار کہاں دیکھا گیا:** {last_seen_location}\n💰 **انعام:** {reward} {reward_type}\n💼 **والٹ:** {wallet}\n👤 **جنس:** {gender}\n🧒 **عمر:** {age}\n📏 **قد:** {height} سینٹی میٹر\n",
  "invalid_reward_amount": "❌ انعام کی رقم غلط ہے۔ زیادہ سے زیادہ انعام کی رقم {max_amount} ہے۔",
  "reward_success": "✅ انعام کامیابی سے {finder_id} کو بھیجا گیا۔",
  "error_transferring_reward": "❌ انعام منتقلی میں غلطی ہوئی۔",
  "case_or_finder_not_found": "❌ کیس یا تلاش کرنے والا نہیں ملا۔",
  "no_finders_for_case": "❌ اس کیس کے لئے تلاش کرنے والا نہیں ملا۔",
  "finder_list_header": "👤 **اس کیس کے لئے تلاش کرنے والا:**",
  "reward_this_finder": "💰 اس تلاش کرنے والے کو انعام دیں",
  "enter_reward_amount": "✏️ براہ کرم اس کیس کے لئے انعام کی رقم درج کریں (زیادہ سے زیادہ {max_amount}): ",
  "reward_confirmation": "کیا آپ کو یقین ہے کہ آپ {amount} انعام {finder_id} کو کیس {case_no} کے لئے بھیجنا چاہتے ہیں؟",
  "reward_cancelled": "انعام بھیجنے کا عمل منسوخ کر دیا گیا۔",
  "confirm_button": "✅ تصدیق کریں",
  "cancel_button": "❌ منسوخ کریں",
  "confirm_delete": "❗ کیا آپ کو یقین ہے کہ آپ اس کیس کو حذف کرنا چاہتے ہیں؟",
  "yes": "✅ ہاں",
  "no": "❌ نہیں",
  "delete_cancelled": "❌ کیس حذف کرنے کا عمل منسوخ کر دیا گیا۔",
  "error_deleting_case": "⚠️ کیس حذف کرنے میں غلطی ہوئی۔ براہ کرم دوبارہ کوشش کریں۔",
  "extend_reward_button": "انعام بڑھائیں ➕",
  "extend_reward_not_found": "❌ انعام بڑھانے کی درخواست نہیں ملی۔",
  "insufficient_funds": "❌ آپ کے {wallet_type} والیٹ میں کافی رقم نہیں ہے۔ ضرورت ہے: {required_amount}",
  "extend_reward_confirmation": "🔄 *انعام بڑھانے کی تصدیق کریں*\n\n💰 رقم: {amount} {wallet_type}\n📤 سے: `{from_wallet}`\n📥 تک: `{to_wallet}`\nکیا آپ کو یقین ہے کہ آپ آگے بڑھنا چاہتے ہیں؟",
  "extend_success": "✅ انعام {amount} {wallet_type} کامیابی سے بڑھا دیا گیا!",
  "extend_cancelled": "❌ انعام بڑھانے کا عمل منسوخ کر دیا گیا۔",
  "transfer_failed": "❌ رقم کی منتقلی ناکام ہوگئی۔ براہ کرم اپنے والیٹ کا بیلنس چیک کریں اور دوبارہ کوشش کریں۔",
  "case_or_extend_not_found": "❌ کیس یا انعام بڑھانے کی درخواست نہیں ملی۔",
  "no_wallet_found": "❌ منتخب کردہ والیٹ نہیں ملا۔",
  "insufficient_funds_after_selection": "❌ منتخب والیٹ میں کافی رقم نہیں ہے۔",
  "extend_already_completed": "⚠️ انعام بڑھانے کی درخواست پہلے ہی مکمل ہو چکی ہے۔",
  "error_processing_extend": "❌ انعام بڑھانے کی درخواست میں غلطی ہوئی۔",
  "error_approving_extend": "❌ انعام بڑھانے کی درخواست منظور کرنے میں غلطی ہوئی۔",
  "case_not_found": "❌ کیس نہیں ملا۔",
  "extend_reward_not_found": "❌ اس کیس کے لئے انعام بڑھانے کی درخواست نہیں ملی۔",
  "select_wallet_for_extend": "🔄 *انعام بڑھانے کے لئے والیٹ منتخب کریں*\n\n💰 رقم: {amount} {wallet_type}\n📤 سے: `{from_wallet}`\n📥 تک: `{to_wallet}`\n\nبراہ کرم نیچے دی گئی اختیارات میں سے کوئی والیٹ منتخب کریں:"
}
,
"ja": {
  "no_advertise_cases": "広告ケースが見つかりません。",
  "select_case_details": "📋 **詳細を見るケースを選択してください:**",
  "case_not_found": "❌ ケースが見つかりません。",
  "error_fetching_cases": "ケースの取得中にエラーが発生しました。",
  "error_fetching_case_details": "❌ ケースの詳細取得中にエラーが発生しました。",
  "error_paginating_cases": "❌ ケースのページネーション中にエラーが発生しました。",
  "invalid_case_id": "❌ ケースIDが無効です。",
  "not_authorized_edit": "❌ このケースを編集する権限がありません。",
  "not_authorized_delete": "❌ このケースを削除する権限がありません。",
  "case_deleted_successfully": "✅ ケースが正常に削除されました。",
  "edit_canceled": "📋 編集がキャンセルされました。ケース一覧に戻ります。",
  "enter_new_value": "✏️ **{field_name}** の新しい値を入力してください: ",
  "field_updated_successfully": "✅ **{field_name}** が更新されました: **{new_value}**",
  "invalid_value": "❌ {error_message} 有効な値を入力してください。",
  "edit_field_prompt": "📝 **どのフィールドを編集しますか？**",
  "cancel_edit_button": "キャンセル",
  "edit_button": "📝 編集",
  "delete_button": "🗑 削除",
  "previous_button": "⬅️ 前へ",
  "next_button": "➡️ 次へ",
  "editable_fields": {
    "Name": "名前",
    "Person Name": "人物名",
    "Relationship": "関係",
    "Last Seen Location": "最後に見た場所",
    "Gender": "性別",
    "Age": "年齢",
    "Hair Color": "髪の色",
    "Eye Color": "目の色",
    "Height": "身長",
    "Weight": "体重",
    "Distinctive Features": "特徴的な特徴",
    "Country": "国",
    "City": "都市"
  },
  "case_details_template": "📌 **ケースの詳細**\n👤 **人物名:** {person_name}\n📍 **最後に見た場所:** {last_seen_location}\n💰 **報酬:** {reward} {reward_type}\n💼 **ウォレット:** {wallet}\n👤 **性別:** {gender}\n🧒 **年齢:** {age}\n📏 **身長:** {height} cm\n",
  "invalid_reward_amount": "❌ 報酬額が無効です。最大報酬額は {max_amount} です。",
  "reward_success": "✅ {finder_id} に報酬が正常に送信されました。",
  "error_transferring_reward": "❌ 報酬の転送中にエラーが発生しました。",
  "case_or_finder_not_found": "❌ ケースまたは発見者が見つかりません。",
  "no_finders_for_case": "❌ このケースに発見者がいません。",
  "finder_list_header": "👤 **このケースの発見者:**",
  "reward_this_finder": "💰 この発見者に報酬を送る",
  "enter_reward_amount": "✏️ このケースの報酬額を入力してください（最大 {max_amount}）：",
  "reward_confirmation": "本当に報酬 {amount} を発見者 {finder_id} にケース {case_no} に送信してもよろしいですか？",
  "reward_cancelled": "報酬送信がキャンセルされました。",
  "confirm_button": "✅ 確認",
  "cancel_button": "❌ キャンセル",
  "confirm_delete": "❗ このケースを削除してもよろしいですか？",
  "yes": "✅ はい",
  "no": "❌ いいえ",
  "delete_cancelled": "❌ ケース削除がキャンセルされました。",
  "error_deleting_case": "⚠️ ケース削除中にエラーが発生しました。再度お試しください。",
  "extend_reward_button": "報酬を延長 ➕",
  "extend_reward_not_found": "❌ 延長報酬要求が見つかりません。",
  "insufficient_funds": "❌ あなたの {wallet_type} ウォレットに十分な資金がありません。必要な金額: {required_amount}",
  "extend_reward_confirmation": "🔄 *報酬延長の確認*\n\n💰 金額: {amount} {wallet_type}\n📤 から: `{from_wallet}`\n📥 へ: `{to_wallet}`\n続行してもよろしいですか？",
  "extend_success": "✅ 報酬 {amount} {wallet_type} が正常に延長されました！",
  "extend_cancelled": "❌ 報酬延長がキャンセルされました。",
  "transfer_failed": "❌ 送金に失敗しました。ウォレットの残高を確認して再度お試しください。",
  "case_or_extend_not_found": "❌ ケースまたは報酬延長の要求が見つかりません。",
  "no_wallet_found": "❌ 選択したウォレットが見つかりません。",
  "insufficient_funds_after_selection": "❌ 選択したウォレットに十分な資金がありません。",
  "extend_already_completed": "⚠️ この報酬延長要求はすでに完了しています。",
  "error_processing_extend": "❌ 報酬延長要求の処理中にエラーが発生しました。",
  "error_approving_extend": "❌ 報酬延長要求の承認中にエラーが発生しました。",
  "case_not_found": "❌ ケースが見つかりません。",
  "extend_reward_not_found": "❌ このケースに対する未完了の報酬延長要求が見つかりません。",
  "select_wallet_for_extend": "🔄 *報酬延長のためのウォレットを選択してください*\n\n💰 金額: {amount} {wallet_type}\n📤 から: `{from_wallet}`\n📥 へ: `{to_wallet}`\n\n以下のオプションからウォレットを選択してください:"
}
,
"ko": {
  "no_advertise_cases": "광고 사례를 찾을 수 없습니다.",
  "select_case_details": "📋 **상세 정보를 볼 사례를 선택하세요:**",
  "case_not_found": "❌ 사례를 찾을 수 없습니다.",
  "error_fetching_cases": "사례를 가져오는 중에 오류가 발생했습니다.",
  "error_fetching_case_details": "❌ 사례 상세 정보를 가져오는 중에 오류가 발생했습니다.",
  "error_paginating_cases": "❌ 사례 페이지를 나누는 중에 오류가 발생했습니다.",
  "invalid_case_id": "❌ 사례 ID가 유효하지 않습니다.",
  "not_authorized_edit": "❌ 이 사례를 편집할 권한이 없습니다.",
  "not_authorized_delete": "❌ 이 사례를 삭제할 권한이 없습니다.",
  "case_deleted_successfully": "✅ 사례가 성공적으로 삭제되었습니다.",
  "edit_canceled": "📋 편집이 취소되었습니다. 사례 목록으로 돌아갑니다.",
  "enter_new_value": "✏️ **{field_name}**의 새 값을 입력하세요: ",
  "field_updated_successfully": "✅ **{field_name}**이(가) 성공적으로 업데이트되었습니다: **{new_value}**",
  "invalid_value": "❌ {error_message} 유효한 값을 입력해주세요.",
  "edit_field_prompt": "📝 **어떤 필드를 편집하시겠습니까?**",
  "cancel_edit_button": "취소",
  "edit_button": "📝 편집",
  "delete_button": "🗑 삭제",
  "previous_button": "⬅️ 이전",
  "next_button": "➡️ 다음",
  "editable_fields": {
    "Name": "이름",
    "Person Name": "사람 이름",
    "Relationship": "관계",
    "Last Seen Location": "마지막으로 본 위치",
    "Gender": "성별",
    "Age": "나이",
    "Hair Color": "머리 색깔",
    "Eye Color": "눈 색깔",
    "Height": "신장",
    "Weight": "체중",
    "Distinctive Features": "특징적인 특징",
    "Country": "국가",
    "City": "도시"
  },
  "case_details_template": "📌 **사례 상세**\n👤 **사람 이름:** {person_name}\n📍 **마지막으로 본 위치:** {last_seen_location}\n💰 **보상:** {reward} {reward_type}\n💼 **지갑:** {wallet}\n👤 **성별:** {gender}\n🧒 **나이:** {age}\n📏 **신장:** {height} cm\n",
  "invalid_reward_amount": "❌ 보상 금액이 유효하지 않습니다. 최대 보상 금액은 {max_amount}입니다.",
  "reward_success": "✅ {finder_id}에게 보상이 성공적으로 지급되었습니다.",
  "error_transferring_reward": "❌ 보상 전송 중에 오류가 발생했습니다.",
  "case_or_finder_not_found": "❌ 사례나 발굴자를 찾을 수 없습니다.",
  "no_finders_for_case": "❌ 이 사례에 대한 발굴자가 없습니다.",
  "finder_list_header": "👤 **이 사례의 발굴자:**",
  "reward_this_finder": "💰 이 발굴자에게 보상 지급",
  "enter_reward_amount": "✏️ 이 사례에 대한 보상 금액을 입력하세요 (최대 {max_amount}): ",
  "reward_confirmation": "정말로 {amount}의 보상을 발굴자 ID {finder_id}에게 사례 {case_no}에 대해 보내시겠습니까?",
  "reward_cancelled": "보상 전송이 취소되었습니다.",
  "confirm_button": "✅ 확인",
  "cancel_button": "❌ 취소",
  "confirm_delete": "❗ 이 사례를 정말로 삭제하시겠습니까?",
  "yes": "✅ 예",
  "no": "❌ 아니오",
  "delete_cancelled": "❌ 사례 삭제가 취소되었습니다.",
  "error_deleting_case": "⚠️ 사례 삭제 중에 오류가 발생했습니다. 다시 시도해주세요.",
  "extend_reward_button": "보상 연장 ➕",
  "extend_reward_not_found": "❌ 활성화된 보상 연장 요청을 찾을 수 없습니다.",
  "insufficient_funds": "❌ {wallet_type} 지갑에 충분한 자금이 없습니다. 필요한 금액: {required_amount}",
  "extend_reward_confirmation": "🔄 *보상 연장 확인*\n\n💰 금액: {amount} {wallet_type}\n📤 출발지: `{from_wallet}`\n📥 도착지: `{to_wallet}`\n계속 진행하시겠습니까?",
  "extend_success": "✅ 보상 {amount} {wallet_type}이 성공적으로 연장되었습니다!",
  "extend_cancelled": "❌ 보상 연장이 취소되었습니다.",
  "transfer_failed": "❌ 송금에 실패했습니다. 지갑 잔액을 확인하고 다시 시도해주세요.",
  "case_or_extend_not_found": "❌ 사례나 연장 요청을 찾을 수 없습니다.",
  "no_wallet_found": "❌ 선택한 지갑을 찾을 수 없습니다.",
  "insufficient_funds_after_selection": "❌ 선택한 지갑에 충분한 자금이 없습니다.",
  "extend_already_completed": "⚠️ 이 보상 연장 요청은 이미 완료되었습니다.",
  "error_processing_extend": "❌ 보상 연장 요청 처리 중에 오류가 발생했습니다.",
  "error_approving_extend": "❌ 보상 연장 요청 승인 중에 오류가 발생했습니다.",
  "case_not_found": "❌ 사례를 찾을 수 없습니다.",
  "extend_reward_not_found": "❌ 이 사례에 대해 완료되지 않은 보상 연장 요청이 없습니다.",
  "select_wallet_for_extend": "🔄 *보상 연장을 위한 지갑을 선택하세요*\n\n💰 금액: {amount} {wallet_type}\n📤 출발지: `{from_wallet}`\n📥 도착지: `{to_wallet}`\n\n아래 옵션에서 지갑을 선택하세요:"
}
,
"km": {
  "no_advertise_cases": "មិនមានករណីពាណិជ្ជកម្មទេ។",
  "select_case_details": "📋 **ជ្រើសរើសករណីដើម្បីមើលព័ត៌មានលម្អិត៖**",
  "case_not_found": "❌ មិនមានករណីសម្រាប់រកឃើញ។",
  "error_fetching_cases": "មានកំហុសក្នុងការទាញយកករណី។",
  "error_fetching_case_details": "❌ មានកំហុសក្នុងការទាញយកព័ត៌មានលម្អិតករណី។",
  "error_paginating_cases": "❌ មានកំហុសក្នុងការបែងចែកករណីជំពូក។",
  "invalid_case_id": "❌ លេខសម្គាល់ករណីមិនត្រឹមត្រូវ។",
  "not_authorized_edit": "❌ អ្នកមិនមានសិទ្ធិកែសម្រួលករណីនេះទេ។",
  "not_authorized_delete": "❌ អ្នកមិនមានសិទ្ធិលុបករណីនេះទេ។",
  "case_deleted_successfully": "✅ ករណីត្រូវបានលុបចោលដោយជោគជ័យ។",
  "edit_canceled": "📋 ការកែសម្រួលត្រូវបានបោះបង់។ កំពុងត្រឡប់ទៅកាន់បញ្ជីករណី។",
  "enter_new_value": "✏️ សូមបញ្ចូលតម្លៃថ្មីសម្រាប់ **{field_name}**: ",
  "field_updated_successfully": "✅ **{field_name}** ត្រូវបានបំលែងជោគជ័យទៅជា: **{new_value}**",
  "invalid_value": "❌ {error_message} សូមបញ្ចូលតម្លៃត្រឹមត្រូវ។",
  "edit_field_prompt": "📝 **តើអ្នកចង់កែសម្រួលវិស័យណាដែរ?**",
  "cancel_edit_button": "បោះបង់",
  "edit_button": "📝 កែសម្រួល",
  "delete_button": "🗑 លុប",
  "previous_button": "⬅️ មុន",
  "next_button": "➡️ បន្ទាប់",
  "editable_fields": {
    "Name": "ឈ្មោះ",
    "Person Name": "ឈ្មោះមនុស្ស",
    "Relationship": "ទំនាក់ទំនង",
    "Last Seen Location": "ទីតាំងដែលបានមើលចុងក្រោយ",
    "Gender": "ភេទ",
    "Age": "អាយុ",
    "Hair Color": "ពណ៌សក់",
    "Eye Color": "ពណ៌ភ្នែក",
    "Height": "កម្ពស់",
    "Weight": "ទំងន់",
    "Distinctive Features": "លក្ខណៈពិសេស",
    "Country": "ប្រទេស",
    "City": "ទីក្រុង"
  },
  "case_details_template": "📌 **ព័ត៌មានលម្អិតករណី**\n👤 **ឈ្មោះមនុស្ស:** {person_name}\n📍 **ទីតាំងដែលបានមើលចុងក្រោយ:** {last_seen_location}\n💰 **រង្វាន់:** {reward} {reward_type}\n💼 **វីសាតី:** {wallet}\n👤 **ភេទ:** {gender}\n🧒 **អាយុ:** {age}\n📏 **កម្ពស់:** {height} cm\n",
  "invalid_reward_amount": "❌ ចំនួនរង្វាន់មិនត្រឹមត្រូវទេ។ ចំនួនរង្វាន់សុទ្ធគឺត្រូវតែត្រឹមត្រូវបំផុតដែលគឺ {max_amount}។",
  "reward_success": "✅ រង្វាន់ត្រូវបានផ្ញើរជោគជ័យទៅអ្នករក {finder_id}។",
  "error_transferring_reward": "❌ មានកំហុសក្នុងការផ្ញើរង្វាន់។",
  "case_or_finder_not_found": "❌ មិនមានករណីឬអ្នករកឃើញ។",
  "no_finders_for_case": "❌ មិនមានអ្នករកឃើញសម្រាប់ករណីនេះទេ។",
  "finder_list_header": "👤 **អ្នករកឃើញសម្រាប់ករណីនេះ:**",
  "reward_this_finder": "💰 ផ្តល់រង្វាន់ឱ្យអ្នករកឃើញនេះ",
  "enter_reward_amount": "✏️ សូមបញ្ចូលចំនួនរង្វាន់សម្រាប់ករណីនេះ (បំផុត {max_amount}): ",
  "reward_confirmation": "តើអ្នកពិតជា​ចង់ផ្ញើរង្វាន់ {amount} ទៅអ្នករក {finder_id} សម្រាប់ករណី {case_no} មែនទេ?",
  "reward_cancelled": "ការផ្ញើរង្វាន់ត្រូវបានបោះបង់។",
  "confirm_button": "✅ បញ្ជាក់",
  "cancel_button": "❌ បោះបង់",
  "confirm_delete": "❗ តើអ្នកពិតជាចង់លុបករណីនេះទេ?",
  "yes": "✅ បាទ",
  "no": "❌ ទេ",
  "delete_cancelled": "❌ ការលុបករណីត្រូវបានបោះបង់។",
  "error_deleting_case": "⚠️ មានកំហុសក្នុងការលុបករណី។ សូមព្យាយាមម្តងទៀត។",
  "extend_reward_button": "បន្ថែមរង្វាន់ ➕",
  "extend_reward_not_found": "❌ មិនមានការស្នើសុំបន្ថែមរង្វាន់ដែលកំពុងសកម្ម។",
  "insufficient_funds": "❌ អ្នកមិនមានប្រាក់គ្រប់គ្រាន់ក្នុងវីសាតី {wallet_type} របស់អ្នកទេ។ ត្រូវការ: {required_amount}",
  "extend_reward_confirmation": "🔄 *បញ្ជាក់បន្ថែមរង្វាន់*\n\n💰 ចំនួន: {amount} {wallet_type}\n📤 ពី: `{from_wallet}`\n📥 ទៅ: `{to_wallet}`\nតើអ្នកពិតជាចង់បន្តទេ?",
  "extend_success": "✅ ការបន្ថែមរង្វាន់ {amount} {wallet_type} ត្រូវបានបញ្ចប់ដោយជោគជ័យ!",
  "extend_cancelled": "❌ ការបន្ថែមរង្វាន់ត្រូវបានបោះបង់។",
  "transfer_failed": "❌ ការផ្ទេរប្រាក់បរាជ័យ។ សូមពិនិត្យមើលប្រាក់នៅក្នុងវីសាតី ហើយព្យាយាមម្តងទៀត។",
  "case_or_extend_not_found": "❌ មិនមានករណីឬការស្នើសុំបន្ថែមទេ។",
  "no_wallet_found": "❌ មិនមានវីសាតីសម្រាប់ជ្រើសរើស។",
  "insufficient_funds_after_selection": "❌ មិនមានប្រាក់គ្រប់គ្រាន់ក្នុងវីសាតីដែលបានជ្រើសរើស។",
  "extend_already_completed": "⚠️ ការស្នើសុំបន្ថែមរង្វាន់នេះត្រូវបានបញ្ចប់រួចហើយ។",
  "error_processing_extend": "❌ មានកំហុសក្នុងការកែសម្រួលការស្នើសុំបន្ថែមរង្វាន់។",
  "error_approving_extend": "❌ មានកំហុសក្នុងការអនុម័តការស្នើសុំបន្ថែមរង្វាន់។",
  "case_not_found": "❌ មិនមានករណីសម្រាប់រកឃើញ។",
  "extend_reward_not_found": "❌ មិនមានការស្នើសុំបន្ថែមរង្វាន់មិនបានបញ្ចប់សម្រាប់ករណីនេះទេ។",
  "select_wallet_for_extend": "🔄 *ជ្រើសរើសវីសាតីសម្រាប់បន្ថែមរង្វាន់*\n\n💰 ចំនួន: {amount} {wallet_type}\n📤 ពី: `{from_wallet}`\n📥 ទៅ: `{to_wallet}`\n\nសូមជ្រើសវីសាតីពីជម្រើសខាងក្រោម:"
}
,
"id": {
  "no_advertise_cases": "Tidak ada kasus iklan.",
  "select_case_details": "📋 **Pilih kasus untuk melihat detailnya:**",
  "case_not_found": "❌ Kasus tidak ditemukan.",
  "error_fetching_cases": "Terjadi kesalahan saat mengambil kasus.",
  "error_fetching_case_details": "❌ Terjadi kesalahan saat mengambil detail kasus.",
  "error_paginating_cases": "❌ Terjadi kesalahan saat melakukan pagination kasus.",
  "invalid_case_id": "❌ ID kasus tidak valid.",
  "not_authorized_edit": "❌ Anda tidak memiliki izin untuk mengedit kasus ini.",
  "not_authorized_delete": "❌ Anda tidak memiliki izin untuk menghapus kasus ini.",
  "case_deleted_successfully": "✅ Kasus berhasil dihapus.",
  "edit_canceled": "📋 Pengeditan dibatalkan. Kembali ke daftar kasus.",
  "enter_new_value": "✏️ Masukkan nilai baru untuk **{field_name}**: ",
  "field_updated_successfully": "✅ **{field_name}** berhasil diperbarui menjadi: **{new_value}**",
  "invalid_value": "❌ {error_message} Masukkan nilai yang valid.",
  "edit_field_prompt": "📝 **Field mana yang ingin Anda edit?**",
  "cancel_edit_button": "Batal",
  "edit_button": "📝 Edit",
  "delete_button": "🗑 Hapus",
  "previous_button": "⬅️ Sebelumnya",
  "next_button": "➡️ Berikutnya",
  "editable_fields": {
    "Name": "Nama",
    "Person Name": "Nama Orang",
    "Relationship": "Hubungan",
    "Last Seen Location": "Lokasi Terakhir Dilihat",
    "Gender": "Jenis Kelamin",
    "Age": "Usia",
    "Hair Color": "Warna Rambut",
    "Eye Color": "Warna Mata",
    "Height": "Tinggi",
    "Weight": "Berat",
    "Distinctive Features": "Ciri-ciri Khas",
    "Country": "Negara",
    "City": "Kota"
  },
  "case_details_template": "📌 **Detail Kasus**\n👤 **Nama Orang:** {person_name}\n📍 **Lokasi Terakhir Dilihat:** {last_seen_location}\n💰 **Hadiah:** {reward} {reward_type}\n💼 **Dompet:** {wallet}\n👤 **Jenis Kelamin:** {gender}\n🧒 **Usia:** {age}\n📏 **Tinggi:** {height} cm\n",
  "invalid_reward_amount": "❌ Jumlah hadiah tidak valid. Hadiah maksimum yang valid adalah {max_amount}.",
  "reward_success": "✅ Hadiah berhasil dikirim ke pencari {finder_id}.",
  "error_transferring_reward": "❌ Terjadi kesalahan saat mengirim hadiah.",
  "case_or_finder_not_found": "❌ Kasus atau pencari tidak ditemukan.",
  "no_finders_for_case": "❌ Tidak ada pencari untuk kasus ini.",
  "finder_list_header": "👤 **Pencari untuk Kasus ini:**",
  "reward_this_finder": "💰 Berikan hadiah kepada pencari ini",
  "enter_reward_amount": "✏️ Masukkan jumlah hadiah untuk kasus ini (maksimal {max_amount}): ",
  "reward_confirmation": "Apakah Anda yakin ingin mengirim hadiah {amount} ke pencari {finder_id} untuk kasus {case_no}?",
  "reward_cancelled": "Pengiriman hadiah dibatalkan.",
  "confirm_button": "✅ Konfirmasi",
  "cancel_button": "❌ Batalkan",
  "confirm_delete": "❗ Apakah Anda yakin ingin menghapus kasus ini?",
  "yes": "✅ Ya",
  "no": "❌ Tidak",
  "delete_cancelled": "❌ Penghapusan kasus dibatalkan.",
  "error_deleting_case": "⚠️ Terjadi kesalahan saat menghapus kasus. Coba lagi.",
  "extend_reward_button": "Tambahkan Hadiah ➕",
  "extend_reward_not_found": "❌ Tidak ada permintaan untuk menambah hadiah yang aktif.",
  "insufficient_funds": "❌ Anda tidak memiliki cukup dana di dompet {wallet_type} Anda. Diperlukan: {required_amount}",
  "extend_reward_confirmation": "🔄 *Konfirmasi Tambah Hadiah*\n\n💰 Jumlah: {amount} {wallet_type}\n📤 Dari: `{from_wallet}`\n📥 Ke: `{to_wallet}`\nApakah Anda yakin ingin melanjutkan?",
  "extend_success": "✅ Penambahan hadiah {amount} {wallet_type} berhasil!",
  "extend_cancelled": "❌ Penambahan hadiah dibatalkan.",
  "transfer_failed": "❌ Transfer dana gagal. Periksa saldo di dompet dan coba lagi.",
  "case_or_extend_not_found": "❌ Kasus atau permintaan penambahan hadiah tidak ditemukan.",
  "no_wallet_found": "❌ Dompet tidak ditemukan.",
  "insufficient_funds_after_selection": "❌ Anda tidak memiliki cukup dana di dompet yang dipilih.",
  "extend_already_completed": "⚠️ Permintaan penambahan hadiah ini telah selesai.",
  "error_processing_extend": "❌ Terjadi kesalahan saat memproses permintaan penambahan hadiah.",
  "error_approving_extend": "❌ Terjadi kesalahan saat menyetujui permintaan penambahan hadiah.",
  "case_not_found": "❌ Kasus tidak ditemukan.",
  "extend_reward_not_found": "❌ Tidak ada permintaan penambahan hadiah yang belum selesai untuk kasus ini.",
  "select_wallet_for_extend": "🔄 *Pilih dompet untuk menambah hadiah*\n\n💰 Jumlah: {amount} {wallet_type}\n📤 Dari: `{from_wallet}`\n📥 Ke: `{to_wallet}`\n\nPilih dompet dari pilihan berikut:"
}

}
