SETTINGS_CONSTANT = {
    "en": {
        "btn_language": "🌍 Change Language",
        "btn_mobile_number": "📱 Manage Mobile Numbers",
        "btn_close_menu": "❌ Close Menu",
        "menu_settings_title": "⚙️ Settings Menu",
        "choose_language": "🌍 Choose your preferred language:",
        "saved_mobile_numbers": "📱 Your saved mobile numbers:",
        "invalid_mobile_number": "❌ Invalid mobile number. Please try again.",
        "enter_tac": "🔢 Enter the TAC sent to your phone via WhatsApp:",
        "tac_invalid": "❌ Invalid TAC. Please try again.",
        "lang_updated": "✅ Language updated successfully!",
        "invalid_choice": "❌ Invalid choice. Please try again.",
        "btn_add_new": "➕ Add New",
        "remove_mobile": "❌ Remove",
        "back_to_mobile_menu": "🔙 Back to Mobile Menu",
        "selected_mobile_options": "Selected mobile: {mobile}\nWhat would you like to do?",
        "mobile_removed": "✅ Removed mobile: {mobile}",
        "mobile_verified_and_saved": "✅ Mobile number verified and saved successfully!\nYour saved mobile numbers:",
        "wallets_already_updated": "Wallets are already up to date.",
        "verify_tac": "Verifying TAC...",
        "tac_verified": "✅ TAC verified.",
        "wallet_name_prompt": "Please enter a name for your {wallet_type} wallet:",
        "wallet_name_empty": "❌ Wallet name cannot be empty. Please try again.",
        "wallet_not_found": "❌ Wallet not found. Please try again.",
        "wallet_create_err": "❌ An error occurred while creating the wallet. Please try again.",
        "choose_existing_or_new_wallet": "Choose an existing wallet or create a new one:",
    },
    "zh": {
        "btn_language": "🌍 更改语言",
        "btn_mobile_number": "📱 管理手机号码",
        "btn_close_menu": "❌ 关闭菜单",
        "menu_settings_title": "⚙️ 设置菜单",
        "choose_language": "🌍 选择您的语言：",
        "saved_mobile_numbers": "📱 您保存的手机号码：",
        "invalid_mobile_number": "❌ 无效的手机号码。请再试一次。",
        "enter_tac": "🔢 输入通过 WhatsApp 发送到您手机的验证码：",
        "tac_invalid": "❌ 验证码无效。请再试一次。",
        "lang_updated": "✅ 语言更新成功！",
        "invalid_choice": "❌ 无效的选择。请再试一次。",
        "btn_add_new": "➕ 添加新的",
        "remove_mobile": "❌ 删除",
        "back_to_mobile_menu": "🔙 返回手机菜单",
        "selected_mobile_options": "已选手机号: {mobile}\n您想做什么？",
        "mobile_removed": "✅ 已删除手机号: {mobile}",
        "mobile_verified_and_saved": "✅ 手机号码验证并保存成功！\n您保存的手机号码如下：",
        "wallets_already_updated": "钱包信息已经是最新状态。",
        "verify_tac": "正在验证验证码...",
        "tac_verified": "✅ 验证码已验证。",
        "wallet_name_prompt": "请输入您的 {wallet_type} 钱包名称:",
        "wallet_name_empty": "❌ 钱包名称不能为空。请再试一次。",
        "wallet_not_found": "❌ 钱包未找到。请再试一次。",
        "wallet_create_err": "❌ 创建钱包时发生错误。请再试一次。",
        "choose_existing_or_new_wallet": "选择现有钱包或创建新钱包：",
    },
    "ms": {
        "btn_language": "🌍 Tukar Bahasa",
        "btn_mobile_number": "📱 Pengurusan Nombor Telefon",
        "btn_close_menu": "❌ Tutup Menu",
        "menu_settings_title": "⚙️ Menu Tetapan",
        "choose_language": "🌍 Pilih bahasa pilihan anda:",
        "saved_mobile_numbers": "📱 Nombor telefon yang disimpan:",
        "invalid_mobile_number": "❌ Nombor telefon tidak sah. Sila cuba lagi.",
        "enter_tac": "🔢 Masukkan TAC yang dihantar ke telefon anda melalui WhatsApp:",
        "tac_invalid": "❌ TAC tidak sah. Sila cuba lagi.",
        "lang_updated": "✅ Bahasa berjaya dikemaskini!",
        "invalid_choice": "❌ Pilihan tidak sah. Sila cuba lagi.",
        "btn_add_new": "➕ Tambah Baru",
        "remove_mobile": "❌ Buang",
        "back_to_mobile_menu": "🔙 Kembali ke Menu Telefon",
        "selected_mobile_options": "Nombor telefon dipilih: {mobile}\nApa yang ingin anda lakukan?",
        "mobile_removed": "✅ Nombor telefon telah dibuang: {mobile}",
        "mobile_verified_and_saved": "✅ Nombor telefon telah disahkan dan disimpan!\nNombor telefon tersimpan:",
        "wallets_already_updated": "Dompet sudah kemaskini.",
        "verify_tac": "Pengesahan TAC...",
        "tac_verified": "✅ TAC berjaya disahkan.",
        "wallet_name_prompt": "Sila masukkan nama untuk dompet {wallet_type} anda:",
        "wallet_name_empty": "❌ Nama dompet tidak boleh kosong. Sila cuba lagi.",
        "wallet_not_found": "❌ Dompet tidak dijumpai. Sila cuba lagi.",
        "wallet_create_err": "❌ Ralat semasa mencipta dompet. Sila cuba lagi.",
        "choose_existing_or_new_wallet": "Pilih dompet sedia ada atau cipta dompet baru:",
    },
    "ko": {
        "btn_language": "🌍 언어 변경",
        "btn_mobile_number": "📱 휴대전화 번호 관리",
        "btn_close_menu": "❌ 메뉴 닫기",
        "menu_settings_title": "⚙️ 설정 메뉴",
        "choose_language": "🌍 원하는 언어를 선택하세요:",
        "saved_mobile_numbers": "📱 저장된 휴대전화 번호:",
        "invalid_mobile_number": "❌ 유효하지 않은 휴대전화 번호입니다. 다시 시도해 주세요.",
        "enter_tac": "🔢 WhatsApp을 통해 전송된 TAC를 입력하세요:",
        "tac_invalid": "❌ 무효한 TAC입니다. 다시 시도해 주세요.",
        "lang_updated": "✅ 언어가 성공적으로 업데이트되었습니다!",
        "invalid_choice": "❌ 잘못된 선택입니다. 다시 시도해 주세요.",
        "btn_add_new": "➕ 추가",
        "remove_mobile": "❌ 삭제",
        "back_to_mobile_menu": "🔙 휴대전화 메뉴로 돌아가기",
        "selected_mobile_options": "선택된 번호: {mobile}\n무엇을 하시겠습니까?",
        "mobile_removed": "✅ 번호 삭제됨: {mobile}",
        "mobile_verified_and_saved": "✅ 휴대전화 번호 인증 및 저장 완료!\n저장된 번호 목록:",
        "wallets_already_updated": "지갑 정보는 이미 최신 상태입니다.",
        "verify_tac": "TAC 확인 중...",
        "tac_verified": "✅ TAC 인증이 완료되었습니다.",
        "wallet_name_prompt": "{wallet_type} 지갑에 사용할 이름을 입력하세요:",
        "wallet_name_empty": "❌ 지갑 이름은 비워둘 수 없습니다. 다시 시도하세요.",
        "wallet_not_found": "❌ 지갑을 찾을 수 없습니다. 다시 시도하세요.",
        "wallet_create_err": "❌ 지갑 생성 중 오류가 발생했습니다. 다시 시도하세요.",
        "choose_existing_or_new_wallet": "기존 지갑을 선택하거나 새 지갑을 만드세요:",
    },
    "es": {
        "btn_language": "🌍 Cambiar idioma",
        "btn_mobile_number": "📱 Administrar números móviles",
        "btn_close_menu": "❌ Cerrar menú",
        "menu_settings_title": "⚙️ Menú de configuración",
        "choose_language": "🌍 Elige tu idioma preferido:",
        "saved_mobile_numbers": "📱 Tus números móviles guardados:",
        "invalid_mobile_number": "❌ Número de móvil inválido. Inténtalo de nuevo.",
        "enter_tac": "🔢 Introduce el código TAC enviado a tu móvil:",
        "tac_invalid": "❌ Código TAC inválido. Inténtalo de nuevo.",
        "lang_updated": "✅ ¡Idioma actualizado correctamente!",
        "invalid_choice": "❌ Elección inválida. Inténtalo de nuevo.",
        "btn_add_new": "➕ Añadir nuevo",
        "remove_mobile": "❌ Eliminar",
        "back_to_mobile_menu": "🔙 Volver al menú de móviles",
        "selected_mobile_options": "Número seleccionado: {mobile}\n¿Qué te gustaría hacer?",
        "mobile_removed": "✅ Número eliminado: {mobile}",
        "mobile_verified_and_saved": "✅ ¡Número móvil verificado y guardado correctamente!\nTus números móviles guardados:",
        "wallets_already_updated": "Las billeteras ya están actualizadas.",
        "verify_tac": "Verificando TAC...",
        "tac_verified": "✅ Código TAC verificado correctamente.",
        "wallet_name_prompt": "Por favor, introduce un nombre para tu billetera {wallet_type}:",
        "wallet_name_empty": "❌ El nombre de la billetera no puede estar vacío. Inténtalo de nuevo.",
        "wallet_not_found": "❌ Billetera no encontrada. Inténtalo de nuevo.",
        "wallet_create_err": "❌ Ocurrió un error al crear la billetera. Inténtalo de nuevo.",
        "choose_existing_or_new_wallet": "Elige una billetera existente o crea una nueva:",
    },
    "hi": {
        "btn_language": "🌍 भाषा बदलें",
        "btn_mobile_number": "📱 मोबाइल नंबर प्रबंधित करें",
        "btn_close_menu": "❌ मेनू बंद करें",
        "menu_settings_title": "⚙️ सेटिंग्स मेनू",
        "choose_language": "🌍 अपनी पसंदीदा भाषा चुनें:",
        "saved_mobile_numbers": "📱 आपके सेव किए गए मोबाइल नंबर:",
        "invalid_mobile_number": "❌ अमान्य मोबाइल नंबर। कृपया पुनः प्रयास करें।",
        "enter_tac": "🔢 अपने मोबाइल पर भेजा गया TAC कोड दर्ज करें:",
        "tac_invalid": "❌ अमान्य TAC। कृपया पुनः प्रयास करें।",
        "lang_updated": "✅ भाषा सफलतापूर्वक अपडेट की गई!",
        "invalid_choice": "❌ अमान्य विकल्प। कृपया पुनः प्रयास करें।",
        "btn_add_new": "➕ नया जोड़ें",
        "remove_mobile": "❌ हटाएं",
        "back_to_mobile_menu": "🔙 मोबाइल मेनू पर वापस जाएं",
        "selected_mobile_options": "चयनित मोबाइल: {mobile}\nआप क्या करना चाहेंगे?",
        "mobile_removed": "✅ मोबाइल हटाया गया: {mobile}",
        "mobile_verified_and_saved": "✅ मोबाइल नंबर सफलतापूर्वक सत्यापित और सेव किया गया!\nआपके सेव किए गए नंबर:",
        "wallets_already_updated": "वॉलेट पहले से ही अपडेट हैं।",
        "verify_tac": "TAC सत्यापित किया जा रहा है...",
        "tac_verified": "✅ TAC सफलतापूर्वक सत्यापित हुआ।",
        "wallet_name_prompt": "कृपया अपने {wallet_type} वॉलेट के लिए एक नाम दर्ज करें:",
        "wallet_name_empty": "❌ वॉलेट नाम खाली नहीं हो सकता। कृपया पुनः प्रयास करें।",
        "wallet_not_found": "❌ वॉलेट नहीं मिला। कृपया पुनः प्रयास करें।",
        "wallet_create_err": "❌ वॉलेट बनाते समय त्रुटि हुई। कृपया पुनः प्रयास करें।",
        "choose_existing_or_new_wallet": "एक मौजूदा वॉलेट चुनें या एक नया बनाएं:",
    },
    "ar": {
        "btn_language": "🌍 تغيير اللغة",
        "btn_mobile_number": "📱 إدارة أرقام الهاتف",
        "btn_close_menu": "❌ إغلاق القائمة",
        "menu_settings_title": "⚙️ قائمة الإعدادات",
        "choose_language": "🌍 اختر لغتك المفضلة:",
        "saved_mobile_numbers": "📱 أرقام الهاتف المحفوظة:",
        "invalid_mobile_number": "❌ رقم هاتف غير صالح. الرجاء المحاولة مرة أخرى.",
        "enter_tac": "🔢 أدخل رمز التحقق المرسل إلى هاتفك:",
        "tac_invalid": "❌ رمز التحقق غير صالح. الرجاء المحاولة مرة أخرى.",
        "lang_updated": "✅ تم تحديث اللغة بنجاح!",
        "invalid_choice": "❌ خيار غير صالح. الرجاء المحاولة مرة أخرى.",
        "btn_add_new": "➕ إضافة جديد",
        "remove_mobile": "❌ إزالة",
        "back_to_mobile_menu": "🔙 الرجوع إلى قائمة الهاتف",
        "selected_mobile_options": "رقم الهاتف المحدد: {mobile}\nماذا تريد أن تفعل؟",
        "mobile_removed": "✅ تم إزالة الرقم: {mobile}",
        "mobile_verified_and_saved": "✅ تم التحقق من رقم الهاتف وحفظه بنجاح!\nأرقام الهاتف المحفوظة:",
        "wallets_already_updated": "المحافظ محدّثة بالفعل.",
        "verify_tac": "جارٍ التحقق من الرمز...",
        "tac_verified": "✅ تم التحقق من الرمز بنجاح.",
        "wallet_name_prompt": "يرجى إدخال اسم لمحفظة {wallet_type} الخاصة بك:",
        "wallet_name_empty": "❌ لا يمكن أن يكون اسم المحفظة فارغًا. الرجاء المحاولة مرة أخرى.",
        "wallet_not_found": "❌ لم يتم العثور على المحفظة. الرجاء المحاولة مرة أخرى.",
        "wallet_create_err": "❌ حدث خطأ أثناء إنشاء المحفظة. الرجاء المحاولة مرة أخرى.",
        "choose_existing_or_new_wallet": "اختر محفظة موجودة أو أنشئ واحدة جديدة:",
    },
    "th": {
        "btn_language": "🌍 เปลี่ยนภาษา",
        "btn_mobile_number": "📱 จัดการเบอร์โทรศัพท์",
        "btn_close_menu": "❌ ปิดเมนู",
        "menu_settings_title": "⚙️ เมนูตั้งค่า",
        "choose_language": "🌍 เลือกภาษาที่คุณต้องการ:",
        "saved_mobile_numbers": "📱 เบอร์โทรที่คุณบันทึกไว้:",
        "invalid_mobile_number": "❌ เบอร์โทรไม่ถูกต้อง กรุณาลองใหม่",
        "enter_tac": "🔢 กรอก TAC ที่ส่งไปยังมือถือของคุณผ่าน WhatsApp:",
        "tac_invalid": "❌ TAC ไม่ถูกต้อง กรุณาลองใหม่",
        "lang_updated": "✅ อัปเดตภาษาสำเร็จ!",
        "invalid_choice": "❌ เลือกไม่ถูกต้อง กรุณาลองใหม่",
        "btn_add_new": "➕ เพิ่มใหม่",
        "remove_mobile": "❌ ลบออก",
        "back_to_mobile_menu": "🔙 กลับไปที่เมนูเบอร์โทร",
        "selected_mobile_options": "เลือกเบอร์: {mobile}\nคุณต้องการทำอะไร?",
        "mobile_removed": "✅ เบอร์ถูกลบแล้ว: {mobile}",
        "mobile_verified_and_saved": "✅ ตรวจสอบและบันทึกเบอร์โทรเรียบร้อยแล้ว!\nเบอร์โทรที่บันทึกไว้:",
        "wallets_already_updated": "กระเป๋าเงินอัปเดตล่าสุดอยู่แล้ว",
        "verify_tac": "กำลังตรวจสอบ TAC...",
        "tac_verified": "✅ ตรวจสอบ TAC เรียบร้อยแล้ว",
        "wallet_name_prompt": "กรุณาใส่ชื่อสำหรับกระเป๋าเงิน {wallet_type} ของคุณ:",
        "wallet_name_empty": "❌ ชื่อกระเป๋าเงินห้ามว่าง กรุณาลองใหม่",
        "wallet_not_found": "❌ ไม่พบกระเป๋าเงิน กรุณาลองใหม่",
        "wallet_create_err": "❌ เกิดข้อผิดพลาดขณะสร้างกระเป๋าเงิน กรุณาลองใหม่",
        "choose_existing_or_new_wallet": "เลือกกระเป๋าเงินที่มีอยู่ หรือสร้างใหม่:",
    },
    "id": {
        "btn_language": "🌍 Ubah Bahasa",
        "btn_mobile_number": "📱 Kelola Nomor Telepon",
        "btn_close_menu": "❌ Tutup Menu",
        "menu_settings_title": "⚙️ Menu Pengaturan",
        "choose_language": "🌍 Pilih bahasa pilihan Anda:",
        "saved_mobile_numbers": "📱 Nomor telepon yang tersimpan:",
        "invalid_mobile_number": "❌ Nomor telepon tidak valid. Sila coba lagi.",
        "enter_tac": "🔢 Masukkan TAC yang dikirim ke WhatsApp Anda:",
        "tac_invalid": "❌ TAC tidak valid. Sila coba lagi.",
        "lang_updated": "✅ Bahasa berhasil diperbarui!",
        "invalid_choice": "❌ Pilihan tidak valid. Sila coba lagi.",
        "btn_add_new": "➕ Tambah Baru",
        "remove_mobile": "❌ Hapus",
        "back_to_mobile_menu": "🔙 Kembali ke Menu Telepon",
        "selected_mobile_options": "Nomor terpilih: {mobile}\nApa yang ingin Anda lakukan?",
        "mobile_removed": "✅ Nomor dihapus: {mobile}",
        "mobile_verified_and_saved": "✅ Nomor telepon diverifikasi dan disimpan!\nNomor tersimpan:",
        "wallets_already_updated": "Dompet sudah mutakhir.",
        "verify_tac": "Memverifikasi TAC...",
        "tac_verified": "✅ TAC berhasil diverifikasi.",
        "wallet_name_prompt": "Silakan masukkan nama untuk dompet {wallet_type} Anda:",
        "wallet_name_empty": "❌ Nama dompet tidak boleh kosong. Sila coba lagi.",
        "wallet_not_found": "❌ Dompet tidak ditemukan. Sila coba lagi.",
        "wallet_create_err": "❌ Terjadi kesalahan saat membuat dompet. Sila coba lagi.",
        "choose_existing_or_new_wallet": "Pilih dompet yang ada atau buat baru:",
    },
    "vi": {
        "btn_language": "🌍 Thay đổi ngôn ngữ",
        "btn_mobile_number": "📱 Quản lý số điện thoại",
        "btn_close_menu": "❌ Đóng menu",
        "menu_settings_title": "⚙️ Trình cài đặt",
        "choose_language": "🌍 Chọn ngôn ngữ bạn thích:",
        "saved_mobile_numbers": "📱 Số điện thoại đã lưu:",
        "invalid_mobile_number": "❌ Số điện thoại không hợp lệ. Vui lòng thử lại.",
        "enter_tac": "🔢 Nhập mã TAC được gửi đến WhatsApp của bạn:",
        "tac_invalid": "❌ Mã TAC không hợp lệ. Vui lòng thử lại.",
        "lang_updated": "✅ Ngôn ngữ đã cập nhật thành công!",
        "invalid_choice": "❌ Lựa chọn không hợp lệ. Vui lòng thử lại.",
        "btn_add_new": "➕ Thêm mới",
        "remove_mobile": "❌ Xóa bỏ",
        "back_to_mobile_menu": "🔙 Quay lại Menu điện thoại",
        "selected_mobile_options": "Số đã chọn: {mobile}\nBạn muốn làm gì tiếp?",
        "mobile_removed": "✅ Số đã bị xóa: {mobile}",
        "mobile_verified_and_saved": "✅ Số điện thoại đã xác minh và lưu thành công!\nDanh sách số đã lưu:",
        "wallets_already_updated": "Ví đã ở trạng thái mới nhất.",
        "verify_tac": "Đang xác thực TAC...",
        "tac_verified": "✅ Xác thực TAC thành công.",
        "wallet_name_prompt": "Vui lòng nhập tên cho ví {wallet_type} của bạn:",
        "wallet_name_empty": "❌ Tên ví không được để trống. Vui lòng thử lại.",
        "wallet_not_found": "❌ Không tìm thấy ví. Vui lòng thử lại.",
        "wallet_create_err": "❌ Có lỗi xảy ra khi tạo ví. Vui lòng thử lại.",
        "choose_existing_or_new_wallet": "Chọn một ví có sẵn hoặc tạo mới:",
    },
    "km": {
        "btn_language": "🌍 ផ្លាស់ប្ដូរភាសា",
        "btn_mobile_number": "📱 គ្រប់គ្រងលេខទូរសព្ទ",
        "btn_close_menu": "❌ បិទម៉ឺនុយ",
        "menu_settings_title": "⚙️ ម៉ឺនុយកំណត់",
        "choose_language": "🌍 ជ្រើសរើសភាសារបស់អ្នក:",
        "saved_mobile_numbers": "📱 លេខទូរសព្ទដែលរក្សាទុករួចហើយ:",
        "invalid_mobile_number": "❌ លេខទូរសព្ទមិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។",
        "enter_tac": "🔢 សូមបញ្ចូលលេខកូដ TAC ដែលបានផ្ញើទៅទូរសព្ទរបស់អ្នកតាមរយៈ WhatsApp:",
        "tac_invalid": "❌ លេខកូដ TAC មិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។",
        "lang_updated": "✅ ភាសាបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ!",
        "invalid_choice": "❌ ជម្រើសមិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។",
        "btn_add_new": "➕ បន្ថែមថ្មី",
        "remove_mobile": "❌ យកចេញ",
        "back_to_mobile_menu": "🔙 ត្រលប់ទៅម៉ឺនុយទូរសព្ទវិញ",
        "selected_mobile_options": "លេខទូរសព្ទដែលបានជ្រើសរើស: {mobile}\nអ្នកចង់ធ្វើអ្វីបន្ត?",
        "mobile_removed": "✅ លេខទូរសព្ទត្រូវបានយកចេញ: {mobile}",
        "mobile_verified_and_saved": "✅ លេខទូរសព្ទត្រូវបានផ្ទៀងផ្ទាត់និងរក្សាទុកដោយជោគជ័យ!\nលេខទូរសព្ទដែលរក្សាទុក:",
        "wallets_already_updated": "កាបូបបានធ្វើបច្ចុប្បន្នភាពរួចហើយ។",
        "verify_tac": "កំពុងផ្ទៀងផ្ទាត់ TAC...",
        "tac_verified": "✅ TAC ត្រូវបានផ្ទៀងផ្ទាត់ដោយជោគជ័យ។",
        "wallet_name_prompt": "សូមបញ្ចូលឈ្មោះសម្រាប់កាបូប {wallet_type} របស់អ្នក:",
        "wallet_name_empty": "❌ ឈ្មោះកាបូបមិនអាចទទេបានទេ។ សូមព្យាយាមម្តងទៀត។",
        "wallet_not_found": "❌ មិនរកឃើញកាបូបទេ។ សូមព្យាយាមម្តងទៀត។",
        "wallet_create_err": "❌ កំហុសកើតឡើងខណៈពេលបង្កើតកាបូប។ សូមព្យាយាមម្តងទៀត។",
        "choose_existing_or_new_wallet": "ជ្រើសរើសកាបូបមានស្រាប់ ឬបង្កើតថ្មី:",
    },
    "ja": {
        "btn_language": "🌍 言語を変更",
        "btn_mobile_number": "📱 モバイル番号の管理",
        "btn_close_menu": "❌ メニューを閉じる",
        "menu_settings_title": "⚙️ 設定メニュー",
        "choose_language": "🌍 好みの言語を選択してください:",
        "saved_mobile_numbers": "📱 保存されているモバイル番号:",
        "invalid_mobile_number": "❌ 無効な電話番号です。もう一度やり直してください。",
        "enter_tac": "🔢 WhatsAppで送られてきたTACコードを入力してください:",
        "tac_invalid": "❌ 無効なTACです。もう一度やり直してください。",
        "lang_updated": "✅ 言語が更新されました!",
        "invalid_choice": "❌ 無効な選択です。もう一度やり直してください。",
        "btn_add_new": "➕ 新規追加",
        "remove_mobile": "❌ 削除",
        "back_to_mobile_menu": "🔙 モバイルメニューに戻る",
        "selected_mobile_options": "選択された番号: {mobile}\n何をしますか？",
        "mobile_removed": "✅ 削除済み番号: {mobile}",
        "mobile_verified_and_saved": "✅ 電話番号の確認が完了し、保存されました。\n保存されている番号:",
        "wallets_already_updated": "ウォレットはすでに最新です。",
        "verify_tac": "TACを確認中...",
        "tac_verified": "✅ TACの検証が完了しました。",
        "wallet_name_prompt": "あなたの {wallet_type} ウォレット名を入力してください:",
        "wallet_name_empty": "❌ ウォレット名は空にできません。再度試してください。",
        "wallet_not_found": "❌ ウォレットが見つかりません。再度試してください。",
        "wallet_create_err": "❌ ウォレット作成中にエラーが発生しました。再度試してください。",
        "choose_existing_or_new_wallet": "既存のウォレットを選択するか、新規に作成してください:",
    },
    "ur": {
        "btn_language": "🌍 زبان تبدیل کریں",
        "btn_mobile_number": "📱 موبائل نمبرز کا انتظام",
        "btn_close_menu": "❌ مینو بند کریں",
        "menu_settings_title": "⚙️ ترتیبات کا مینو",
        "choose_language": "🌍 اپنی پسندیدہ زبان منتخب کریں:",
        "saved_mobile_numbers": "📱 آپ کے محفوظ شدہ موبائل نمبر:",
        "invalid_mobile_number": "❌ غیر درست موبائل نمبر۔ دوبارہ کوشش کریں۔",
        "enter_tac": "🔢 WhatsApp کے ذریعے بھیجا گیا TAC درج کریں:",
        "tac_invalid": "❌ غیر درست TAC۔ دوبارہ کوشش کریں۔",
        "lang_updated": "✅ زبان کامیابی سے اپ ڈیٹ ہو گئی!",
        "invalid_choice": "❌ غلط انتخاب۔ دوبارہ کوشش کریں۔",
        "btn_add_new": "➕ نیا شامل کریں",
        "remove_mobile": "❌ حذف کریں",
        "back_to_mobile_menu": "🔙 موبائل مینو پر واپس جائیں",
        "selected_mobile_options": "منتخب موبائل: {mobile}\nآپ کیا کرنا چاہتے ہیں؟",
        "mobile_removed": "✅ موبائل نمبر حذف کر دیا گیا: {mobile}",
        "mobile_verified_and_saved": "✅ موبائل نمبر کی تصدیق اور محفوظ کر لیا گیا!\nآپ کے محفوظ شدہ موبائل نمبر:",
        "wallets_already_updated": "والیٹس پہلے ہی اپ ڈیٹ ہیں۔",
        "verify_tac": "TAC کی تصدیق ہو رہی ہے...",
        "tac_verified": "✅ TAC کی تصدیق کامیاب رہی۔",
        "wallet_name_prompt": "براہ کرم اپنے {wallet_type} والیٹ کے لیے نام درج کریں:",
        "wallet_name_empty": "❌ والیٹ کا نام خالی نہیں ہو سکتا۔ دوبارہ کوشش کریں۔",
        "wallet_not_found": "❌ والیٹ نہیں ملا۔ دوبارہ کوشش کریں۔",
        "wallet_create_err": "❌ والیٹ بناتے وقت کچھ غلطی ہو گئی۔ دوبارہ کوشش کریں۔",
        "choose_existing_or_new_wallet": "ایک موجودہ والیٹ کو منتخب کریں یا نیا بنائیں:",
    },
}


# TODO: missing some of the language in the settings
