SETTINGS_CONSTANT = {
    "en": {
        "btn_language": "🌍 Change Language",
        "btn_mobile_number": "📱 Manage Mobile Numbers",
        "btn_close_menu": "❌ Close Menu",
        "menu_settings_title": "⚙️ Settings Menu",
        "choose_language": "🌍 Choose your preferred language:",
        "saved_mobile_numbers": "📱 Your saved mobile numbers:",
        "invalid_mobile_number": "❌ Invalid mobile number. Please try again.",
        "enter_tac": "🔢 Enter the TAC sent to your phone via WhatsApp:",
        "tac_invalid": "❌ Invalid TAC. Please try again.",
        "lang_updated": "✅ Language updated successfully!",
        "invalid_choice": "❌ Invalid choice. Please try again.",
        "btn_add_new": "➕ Add New",
        "remove_mobile": "❌ Remove",
        "back_to_mobile_menu": "🔙 Back to Mobile Menu",
        "selected_mobile_options": "Selected mobile: {mobile}\nWhat would you like to do?",
        "mobile_removed": "✅ Removed mobile: {mobile}",
        "mobile_verified_and_saved": "✅ Mobile number verified and saved successfully!\nYour saved mobile numbers:",
        "wallets_already_updated": "Wallets are already up to date.",
        "verify_tac": "Verifying TAC...",
        "tac_verified": "✅ TAC verified.",
        "wallet_name_prompt": "Please enter a name for your {wallet_type} wallet:",
        "wallet_name_empty": "❌ Wallet name cannot be empty. Please try again.",
        "wallet_not_found": "❌ Wallet not found. Please try again.",
        "wallet_create_err": "❌ An error occurred while creating the wallet. Please try again.",
        "choose_existing_or_new_wallet": "Choose an existing wallet or create a new one:",
    },
    "zh": {
        "btn_language": "🌍 更改语言",
        "btn_mobile_number": "📱 管理手机号码",
        "btn_close_menu": "❌ 关闭菜单",
        "menu_settings_title": "⚙️ 设置菜单",
        "choose_language": "🌍 选择您喜欢的语言：",
        "saved_mobile_numbers": "📱 您保存的手机号码：",
        "invalid_mobile_number": "❌ 无效的手机号码，请重试。",
        "enter_tac": "🔢 输入通过 WhatsApp 发送到您手机的 TAC：",
        "tac_invalid": "❌ 无效的验证码，请重试。",
        "lang_updated": "✅ 语言更新成功！",
        "invalid_choice": "❌ 无效的选择，请重试。",
        "btn_add_new": "➕ 添加新的",
        "remove_mobile": "❌ 移除",
        "back_to_mobile_menu": "🔙 返回手机号码菜单",
        "selected_mobile_options": "已选手机号码：{mobile}\n您想做什么？",
        "mobile_removed": "✅ 已移除手机号码：{mobile}",
        "mobile_verified_and_saved": "✅ 手机号码验证并保存成功！\n您的保存的手机号码：",
        "wallets_already_updated": "钱包已经是最新的。",
        "verify_tac": "正在验证验证码...",
        "tac_verified": "✅ TAC 验证成功",
        "wallet_name_prompt": "请输入您的 {wallet_type} 钱包名称：",
        "wallet_name_empty": "❌ 钱包名称不能为空，请重试。",
        "wallet_not_found": "❌ 未找到钱包，请重试。",
        "wallet_create_err": "❌ 创建钱包时发生错误，请重试。",
        "choose_existing_or_new_wallet": "选择现有的钱包或创建一个新的钱包：",
    },
    "ms": {  # Malay (Malaysia)
        "btn_language": "🌍 Tukar Bahasa",
        "btn_mobile_number": "📱 Urus Nombor Telefon",
        "btn_close_menu": "❌ Tutup Menu",
        "menu_settings_title": "⚙️ Menu Tetapan",
        "choose_language": "🌍 Pilih bahasa pilihan anda:",
        "saved_mobile_numbers": "📱 Nombor telefon yang disimpan:",
        "invalid_mobile_number": "❌ Nombor telefon tidak sah. Sila cuba lagi.",
        "enter_tac": "🔢 Masukkan kod TAC (pengesahan) yang dihantar ke telefon anda:",
        "tac_invalid": "❌ Kod TAC tidak sah. Sila cuba lagi.",
        "lang_updated": "✅ Bahasa berjaya dikemaskini!",
        "invalid_choice": "❌ Pilihan tidak sah. Sila cuba lagi.",
        "btn_add_new": "➕ Tambah Baru",
        "remove_mobile": "❌ Buang",
        "back_to_mobile_menu": "🔙 Kembali ke Menu Telefon",
        "selected_mobile_options": "Nombor telefon dipilih: {mobile}\nApa yang ingin anda lakukan?",
        "mobile_removed": "✅ Nombor telefon telah dibuang: {mobile}",
        "mobile_verified_and_saved": "✅ Nombor telefon berjaya disahkan dan disimpan!\nNombor telefon yang disimpan:",
        "wallets_already_updated": "Dompet sudah dikemaskini.",
        "verify_tac": "Mengesahkan TAC...",
        "tac_verified": "✅ TAC berjaya disahkan.",
        "wallet_name_prompt": "Sila masukkan nama untuk dompet {wallet_type} anda:",
        "wallet_name_empty": "❌ Nama dompet tidak boleh kosong. Sila cuba lagi.",
        "wallet_not_found": "❌ Dompet tidak ditemui. Sila cuba lagi.",
        "wallet_create_err": "❌ Ralat berlaku semasa mencipta dompet. Sila cuba lagi.",
        "choose_existing_or_new_wallet": "Pilih dompet sedia ada atau cipta yang baru:",
    },
    "ko": {
        "btn_language": "🌍 언어 변경",
        "btn_mobile_number": "📱 휴대폰 번호 관리",
        "btn_close_menu": "❌ 메뉴 닫기",
        "menu_settings_title": "⚙️ 설정 메뉴",
        "choose_language": "🌍 선호하는 언어를 선택하세요:",
        "saved_mobile_numbers": "📱 저장된 휴대폰 번호:",
        "invalid_mobile_number": "❌ 유효하지 않은 번호입니다. 다시 시도해주세요.",
        "enter_tac": "🔢 휴대폰으로 전송된 인증 코드를 입력하세요:",
        "tac_invalid": "❌ 인증 코드가 유효하지 않습니다. 다시 시도해주세요.",
        "lang_updated": "✅ 언어가 성공적으로 업데이트되었습니다!",
        "invalid_choice": "❌ 잘못된 선택입니다. 다시 시도해주세요.",
        "btn_add_new": "➕ 새로 추가",
        "remove_mobile": "❌ 제거",
        "back_to_mobile_menu": "🔙 휴대폰 메뉴로 돌아가기",
        "selected_mobile_options": "선택된 번호: {mobile}\n무엇을 하시겠습니까?",
        "mobile_removed": "✅ 제거된 번호: {mobile}",
        "mobile_verified_and_saved": "✅ 휴대폰 번호가 확인되어 저장되었습니다!\n저장된 번호:",
        "wallets_already_updated": "지갑은 이미 최신 상태입니다.",
        "verify_tac": "인증 코드 확인 중...",
        "tac_verified": "✅ 인증 코드가 확인되었습니다.",
        "wallet_name_prompt": "{wallet_type} 지갑 이름을 입력해주세요:",
        "wallet_name_empty": "❌ 지갑 이름은 비워둘 수 없습니다. 다시 시도해주세요.",
        "wallet_not_found": "❌ 지갑을 찾을 수 없습니다. 다시 시도해주세요.",
        "wallet_create_err": "❌ 지갑 생성 중 오류가 발생했습니다. 다시 시도해주세요.",
        "choose_existing_or_new_wallet": "기존 지갑을 선택하거나 새로 만드세요:",
    },
    "es": {
        "btn_language": "🌍 Cambiar idioma",
        "btn_mobile_number": "📱 Administrar números móviles",
        "btn_close_menu": "❌ Cerrar menú",
        "menu_settings_title": "⚙️ Menú de configuración",
        "choose_language": "🌍 Elige tu idioma preferido:",
        "saved_mobile_numbers": "📱 Tus números móviles guardados:",
        "invalid_mobile_number": "❌ Número de móvil inválido. Inténtalo de nuevo.",
        "enter_tac": "🔢 Introduce el código TAC enviado a tu móvil:",
        "tac_invalid": "❌ Código TAC inválido. Inténtalo de nuevo.",
        "lang_updated": "✅ ¡Idioma actualizado correctamente!",
        "invalid_choice": "❌ Elección inválida. Inténtalo de nuevo.",
        "btn_add_new": "➕ Añadir nuevo",
        "remove_mobile": "❌ Eliminar",
        "back_to_mobile_menu": "🔙 Volver al menú de móviles",
        "selected_mobile_options": "Número seleccionado: {mobile}\n¿Qué te gustaría hacer?",
        "mobile_removed": "✅ Número eliminado: {mobile}",
        "mobile_verified_and_saved": "✅ ¡Número móvil verificado y guardado correctamente!\nTus números móviles guardados:",
        "wallets_already_updated": "Las billeteras ya están actualizadas.",
        "verify_tac": "Verificando TAC...",
        "tac_verified": "✅ Código TAC verificado correctamente.",
        "wallet_name_prompt": "Por favor, introduce un nombre para tu billetera {wallet_type}:",
        "wallet_name_empty": "❌ El nombre de la billetera no puede estar vacío. Inténtalo de nuevo.",
        "wallet_not_found": "❌ Billetera no encontrada. Inténtalo de nuevo.",
        "wallet_create_err": "❌ Ocurrió un error al crear la billetera. Inténtalo de nuevo.",
        "choose_existing_or_new_wallet": "Elige una billetera existente o crea una nueva:",
    },
    "hi": {
        "btn_language": "🌍 भाषा बदलें",
        "btn_mobile_number": "📱 मोबाइल नंबर प्रबंधित करें",
        "btn_close_menu": "❌ मेनू बंद करें",
        "menu_settings_title": "⚙️ सेटिंग्स मेनू",
        "choose_language": "🌍 अपनी पसंदीदा भाषा चुनें:",
        "saved_mobile_numbers": "📱 आपके सेव किए गए मोबाइल नंबर:",
        "invalid_mobile_number": "❌ अमान्य मोबाइल नंबर। कृपया पुनः प्रयास करें।",
        "enter_tac": "🔢 अपने मोबाइल पर भेजा गया TAC कोड दर्ज करें:",
        "tac_invalid": "❌ अमान्य TAC। कृपया पुनः प्रयास करें।",
        "lang_updated": "✅ भाषा सफलतापूर्वक अपडेट की गई!",
        "invalid_choice": "❌ अमान्य विकल्प। कृपया पुनः प्रयास करें।",
        "btn_add_new": "➕ नया जोड़ें",
        "remove_mobile": "❌ हटाएं",
        "back_to_mobile_menu": "🔙 मोबाइल मेनू पर वापस जाएं",
        "selected_mobile_options": "चयनित मोबाइल: {mobile}\nआप क्या करना चाहेंगे?",
        "mobile_removed": "✅ मोबाइल हटाया गया: {mobile}",
        "mobile_verified_and_saved": "✅ मोबाइल नंबर सफलतापूर्वक सत्यापित और सेव किया गया!\nआपके सेव किए गए नंबर:",
        "wallets_already_updated": "वॉलेट पहले से ही अपडेट हैं।",
        "verify_tac": "TAC सत्यापित किया जा रहा है...",
        "tac_verified": "✅ TAC सफलतापूर्वक सत्यापित हुआ।",
        "wallet_name_prompt": "कृपया अपने {wallet_type} वॉलेट के लिए एक नाम दर्ज करें:",
        "wallet_name_empty": "❌ वॉलेट नाम खाली नहीं हो सकता। कृपया पुनः प्रयास करें।",
        "wallet_not_found": "❌ वॉलेट नहीं मिला। कृपया पुनः प्रयास करें।",
        "wallet_create_err": "❌ वॉलेट बनाते समय त्रुटि हुई। कृपया पुनः प्रयास करें।",
        "choose_existing_or_new_wallet": "एक मौजूदा वॉलेट चुनें या एक नया बनाएं:",
    },
    "ar": {
        "btn_language": "🌍 تغيير اللغة",
        "btn_mobile_number": "📱 إدارة أرقام الهاتف",
        "btn_close_menu": "❌ إغلاق القائمة",
        "menu_settings_title": "⚙️ قائمة الإعدادات",
        "choose_language": "🌍 اختر لغتك المفضلة:",
        "saved_mobile_numbers": "📱 أرقام الهاتف المحفوظة:",
        "invalid_mobile_number": "❌ رقم هاتف غير صالح. الرجاء المحاولة مرة أخرى.",
        "enter_tac": "🔢 أدخل رمز التحقق المرسل إلى هاتفك:",
        "tac_invalid": "❌ رمز التحقق غير صالح. الرجاء المحاولة مرة أخرى.",
        "lang_updated": "✅ تم تحديث اللغة بنجاح!",
        "invalid_choice": "❌ خيار غير صالح. الرجاء المحاولة مرة أخرى.",
        "btn_add_new": "➕ إضافة جديد",
        "remove_mobile": "❌ إزالة",
        "back_to_mobile_menu": "🔙 الرجوع إلى قائمة الهاتف",
        "selected_mobile_options": "رقم الهاتف المحدد: {mobile}\nماذا تريد أن تفعل؟",
        "mobile_removed": "✅ تم إزالة الرقم: {mobile}",
        "mobile_verified_and_saved": "✅ تم التحقق من رقم الهاتف وحفظه بنجاح!\nأرقام الهاتف المحفوظة:",
        "wallets_already_updated": "المحافظ محدّثة بالفعل.",
        "verify_tac": "جارٍ التحقق من الرمز...",
        "tac_verified": "✅ تم التحقق من الرمز بنجاح.",
        "wallet_name_prompt": "يرجى إدخال اسم لمحفظة {wallet_type} الخاصة بك:",
        "wallet_name_empty": "❌ لا يمكن أن يكون اسم المحفظة فارغًا. الرجاء المحاولة مرة أخرى.",
        "wallet_not_found": "❌ لم يتم العثور على المحفظة. الرجاء المحاولة مرة أخرى.",
        "wallet_create_err": "❌ حدث خطأ أثناء إنشاء المحفظة. الرجاء المحاولة مرة أخرى.",
        "choose_existing_or_new_wallet": "اختر محفظة موجودة أو أنشئ واحدة جديدة:",
    },
    "th": {
        "choose_wallet": "กรุณาเลือกประเภทกระเป๋าเงิน:",
        "sol_wallet": "โซลานา (SOL)",
        "usdt_wallet": "ยูเอสดี เทเธอร์ (USDT)",
        "choose_existing_or_new_wallet": "เลือกกระเป๋าเงินที่มีอยู่หรือสร้างใหม่",
        "wallet_name_prompt": "คุณได้เลือกกระเป๋าเงินประเภท {wallet_type}.\nกรุณาใส่ชื่อสำหรับกระเป๋าเงินของคุณ:",
        "wallet_name_empty": "❌ ชื่อกระเป๋าเงินไม่สามารถเว้นว่างได้ กรุณาลองใหม่อีกครั้ง.",
        "wallet_create_ok": "✅ สร้างกระเป๋าเงินสำเร็จ!\n\n",
        "wallet_create_details": (
            "📌 <b>ข้อมูลกระเป๋าเงิน:</b>\n"
            "🧾 <b>ชื่อ:</b> <code>{name}</code>\n"
            "💰 <b>ประเภท:</b> <code>{wallet_type}</code>\n"
            "🔐 <b>คีย์สาธารณะ:</b> <code>{public_key}</code>\n"
        ),
        "wallet_create_err": "❌ เกิดข้อผิดพลาดในการสร้างกระเป๋าเงิน กรุณาลองใหม่ภายหลัง.",
        "cancel_msg": "ยกเลิกการดำเนินการ ใช้ /start เพื่อเริ่มต้นใหม่.",
        "account_wallet_type": "ประเภทกระเป๋าเงินบัญชี (SOL | USDT)",
        "menu_wallet_title": "💳 เมนูกระเป๋าเงิน",
        "btn_refresh": "🔄 รีเฟรช",
        "btn_sol": "💰 SOL",
        "btn_usdt": "💵 USDT",
        "btn_show_address": "🏠 แสดงที่อยู่",
        "btn_create_wallet": "➕ สร้างกระเป๋าเงิน",
        "btn_delete_wallet": "🗑️ ลบกระเป๋าเงิน",
        "wallet_no_exists": "❌ ไม่พบกระเป๋าเงิน กรุณาสร้างใหม่โดยใช้ปุ่ม 'สร้างกระเป๋าเงิน'.",
        "wallet_exists": "📌 <b>กระเป๋าเงินที่มีอยู่:</b>\nชื่อ: {name}\nคีย์สาธารณะ: {pub}\nยอดคงเหลือ: {bal} SOL",
        "wallet_deleted": "✅ ลบกระเป๋าเงินเรียบร้อยแล้ว.",
        "wallet_not_deleted": "❌ ไม่มีข้อมูลกระเป๋าเงินที่จะลบ.",
        "wallet_refreshed": "🔄 ยอดคงเหลือได้รับการอัปเดต:\nชื่อ: {name}\nคีย์สาธารณะ: {pub}\nยอดคงเหลือ: {bal} SOL",
        "guide_create_wallet": (
            "📝 <b>วิธีการสร้างกระเป๋าเงิน:</b>\n"
            "1️⃣ เลือกประเภทกระเป๋าเงิน (SOL หรือ USDT).\n"
            "2️⃣ ป้อนชื่อที่ไม่ซ้ำกันสำหรับกระเป๋าเงินของคุณ.\n"
            "3️⃣ กระเป๋าเงินของคุณจะถูกสร้างพร้อมกับคีย์สาธารณะและคีย์ลับ.\n"
            "4️⃣ ใช้คีย์สาธารณะเพื่อรับเงิน.\n\n"
            "💡 เคล็ดลับ: เก็บรักษาคีย์ลับของคุณให้ปลอดภัยและอย่าแบ่งปันกับใคร."
        ),
        "guide_delete_wallet": (
            "⚠️ <b>ข้อมูลสำคัญ:</b>\n"
            "การลบกระเป๋าเงินไม่สามารถย้อนกลับได้ เงินทั้งหมดในกระเป๋าจะสูญหาย.\n"
            "โปรดแน่ใจว่าคุณได้โอนเงินทั้งหมดก่อนดำเนินการต่อ."
        ),
        "no_wallets": "คุณยังไม่มีข้อมูลกระเป๋าเงิน.",
        "select_wallet": "เลือกกระเป๋าเงินเพื่อดูประวัติการทำธุรกรรม:",
        "wallet_details": "**ชื่อกระเป๋าเงิน:** {name} \n\n **ที่อยู่สาธารณะ:** {public_key}",
        "wallet_not_found": "ไม่พบกระเป๋าเงิน.",
        "back_button": "⬅️ กลับ",
        "sol_wallets_header": "<b>กระเป๋าเงิน SOL ของคุณ:</b>\n",
        "wallet_balance": "<b>ชื่อ:</b> {name}, <b>ยอดคงเหลือ:</b> {balance} SOL\n",
        "wallet_error": "<b>ชื่อ:</b> {name}, <b>ข้อผิดพลาด:</b> {error}\n",
        "no_sol_wallets": "คุณยังไม่มีข้อมูลกระเป๋าเงิน SOL.",
        "no_usdt_wallets": "คุณยังไม่มีข้อมูลกระเป๋าเงิน USDT.",
        "refresh_btn": "🔄 รีเฟรช",
    },
}



# TODO: missing some of the language in the settings 