STATS_CONSTANT = {
    "en": {
        # Main stats page
        "community_stats_title": "<b>📊 PeopleTrace Community Stats</b>",
        "total_cases_submitted": "• <b>Total Cases Submitted:</b> {}",
        "regions_covered": "• <b>Regions Covered:</b> {} countries, {} cities",
        "unsolved_cases": "• <b>🕵️‍♂️ Unsolved Cases:</b> {} (Click below 👇)",
        "successfully_found": "• <b>✅ Successfully Found:</b> {}",
        "average_reward_offered": "• <b>🎁 Average Reward Offered:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ Fastest Case Solved:</b> {} days",
        "top_active_region": "• <b>🔥 Top Active Region:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍🧑 Common Demographic:</b> {}",
        "highest_reward": "• <b>💰 Highest Reward:</b> {} USDT",

        # Buttons
        "view_unsolved_cases_button": "🕵️ View Unsolved Cases",
        "view_local_stats_button": "📍 View Local Stats",
        "my_submissions_button": "📂 My Submissions",
        "back_button": "⬅️ Back",

        # Menu messages
        "local_stats_coming_soon": "📍 Coming soon: Local Stats based on your location.",
        "unsolved_country_list": "Choose a country from the list below:",
        "no_unsolved_country": "📍 No unsolved cases in any country.",  # <-- NEW FIELD

        # Country case list
        "no_cases_in_country": "No cases found in {}.",
        "unsolved_cases_in_country": "<b>🕵️ Unsolved Cases in {}:</b>",

        # User cases
        "you_havent_submitted_cases": "📂 You haven’t submitted any cases yet.",
        "your_submitted_cases_title": "<b>📂 Your Submitted Cases:</b>",

        # Case details
        "case_details_title": "<b>📄 Case Details</b>",
        "case_no_label": "• <b>Case No:</b> {}",
        "name_label": "• <b>Name:</b> {}",
        "status_label": "• <b>Status:</b> {}",
        "last_seen_label": "• <b>Last Seen:</b> {}",
        "reward_label": "• <b>Reward:</b> {} {}",
        "created_at_label": "• <b>Created At:</b> {}",

        # Errors
        "invalid_selection_error": "⚠️ <b>Invalid Selection</b>\n\nPlease choose a valid option.",

        # Remaining strings
        "ask_for_local_stats_input": "📍 Please share your city and province.",
        "invalid_local_stats_format": "⚠️ <b>Invalid Format</b>\n\nPlease enter as: <i>City, Province</i>",
        "no_local_cases_found": "🕵️ No cases found in {city}, {province}.",
        "local_cases_found_title": "<b>📂 Cases in {city}, {province}:</b>",
        
    },
    
    "zh": {
        "community_stats_title": "<b>📊 PeopleTrace 社区统计</b>",
        "total_cases_submitted": "• <b>提交的总案件数：</b> {}",
        "regions_covered": "• <b>覆盖地区：</b> {} 个国家，{} 个城市",
        "unsolved_cases": "• <b>🕵️‍♂️ 未解决案件：</b> {} （点击下方👇）",
        "successfully_found": "• <b>✅ 成功找到人数：</b> {}",
        "average_reward_offered": "• <b>🎁 平均悬赏金额：</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ 解决最快案件：</b> {} 天",
        "top_active_region": "• <b>🔥 最活跃地区：</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍🧑 常见人群特征：</b> {}",
        "highest_reward": "• <b>💰 最高悬赏金：</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ 查看未解决案件",
        "view_local_stats_button": "📍 查看本地统计",
        "my_submissions_button": "📂 我的提交",
        "back_button": "⬅️ 返回",
        "local_stats_coming_soon": "📍 即将推出：基于您所在地区的统计数据。",
        "unsolved_country_list": "从下方选择一个国家：",
        "no_unsolved_country": "📍 没有任何国家有未解决案件。",  # <-- NEW FIELD

        "no_cases_in_country": "在 {} 中没有找到案件。",
        "unsolved_cases_in_country": "<b>🕵️ 在 {} 中的未解决案件：</b>",
        "you_havent_submitted_cases": "📂 您尚未提交任何案件。",
        "your_submitted_cases_title": "<b>📂 您提交的案件：</b>",
        "case_details_title": "<b>📄 案件详情</b>",
        "case_no_label": "• <b>案件编号：</b> {}",
        "name_label": "• <b>姓名：</b> {}",
        "status_label": "• <b>状态：</b> {}",
        "last_seen_label": "• <b>最后出现地点：</b> {}",
        "reward_label": "• <b>悬赏：</b> {} {}",
        "created_at_label": "• <b>创建时间：</b> {}",
        "invalid_selection_error": "⚠️ <b>无效选择</b>\n\n请选择有效选项。",
    },

    "ms": {
        "community_stats_title": "<b>📊 Statistik Komuniti PeopleTrace</b>",
        "total_cases_submitted": "• <b>Jumlah Kes Dihantar:</b> {}",
        "regions_covered": "• <b>Kawasan Diliputi:</b> {} negara, {} bandar",
        "unsolved_cases": "• <b>🕵️‍♂️ Kes Belum Diselesaikan:</b> {} (Klik di bawah 👇)",
        "successfully_found": "• <b>✅ Berjaya Dijumpai:</b> {}",
        "average_reward_offered": "• <b>🎁 Purata Ganjaran Ditawarkan:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ Kes Paling Cepat Diselesaikan:</b> {} hari",
        "top_active_region": "• <b>🔥 Kawasan Paling Aktif:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍🧑 Demografi Biasa:</b> {}",
        "highest_reward": "• <b>💰 Ganjaran Tertinggi:</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ Lihat Kes Belum Diselesaikan",
        "view_local_stats_button": "📍 Lihat Statistik Tempatan",
        "my_submissions_button": "📂 Hantaran Saya",
        "back_button": "⬅️ Kembali",
        "local_stats_coming_soon": "📍 Akan datang: Statistik tempatan berdasarkan lokasi anda.",
        "unsolved_country_list": "Pilih satu negara dari senarai di bawah:",
        "no_unsolved_country": "📍 Tiada kes yang belum diselesaikan di mana-mana negara.",  # <-- NEW FIELD

        "no_cases_in_country": "Tiada kes dijumpai di {}.",
        "unsolved_cases_in_country": "<b>🕵️ Kes Belum Diselesaikan di {}:</b>",
        "you_havent_submitted_cases": "📂 Anda belum menghantar sebarang kes lagi.",
        "your_submitted_cases_title": "<b>📂 Kes Yang Telah DiHantar:</b>",
        "case_details_title": "<b>📄 Butiran Kes</b>",
        "case_no_label": "• <b>No. Kes:</b> {}",
        "name_label": "• <b>Nama:</b> {}",
        "status_label": "• <b>Status:</b> {}",
        "last_seen_label": "• <b>Kali Terakhir Dilihat:</b> {}",
        "reward_label": "• <b>Ganjaran:</b> {} {}",
        "created_at_label": "• <b>Dicipta Pada:</b> {}",
        "invalid_selection_error": "⚠️ <b>Pemilihan Tidak Sah</b>\n\nSila pilih opsyen yang sah.",
    },

    "th": {
        "community_stats_title": "<b>📊 สถิติชุมชน PeopleTrace</b>",
        "total_cases_submitted": "• <b>จำนวนคดีที่ส่งเข้ามาทั้งหมด:</b> {}",
        "regions_covered": "• <b>พื้นที่ครอบคลุม:</b> {} ประเทศ, {} เมือง",
        "unsolved_cases": "• <b>🕵️‍♂️ คดียังไม่คลี่คลาย:</b> {} (คลิกด้านล่าง 👇)",
        "successfully_found": "• <b>✅ พบตัวบุคคลแล้ว:</b> {}",
        "average_reward_offered": "• <b>🎁 เฉลี่ยรางวัลนำจับ:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ คดีเร็วที่สุดที่คลี่คลาย:</b> {} วัน",
        "top_active_region": "• <b>🔥 พื้นที่ที่มีการเคลื่อนไหวสูงสุด:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍🧑 กลุ่มประชากรหลัก:</b> {}",
        "highest_reward": "• <b>💰 รางวัลนำจับสูงสุด:</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ ดูคดียังไม่คลี่คลาย",
        "view_local_stats_button": "📍 ดูสถิติในพื้นที่",
        "my_submissions_button": "📂 การส่งของฉัน",
        "back_button": "⬅️ ย้อนกลับ",
        "local_stats_coming_soon": "📍 เร็วๆ นี้: สถิติในพื้นที่ตามตำแหน่งของคุณ",
        "unsolved_country_list": "เลือกประเทศจากด้านล่าง:",
        "no_unsolved_country": "📍 ไม่มีคดียังไม่คลี่คลายในประเทศใดเลย.",  # <-- NEW FIELD

        "no_cases_in_country": "ไม่มีคดีใน {}",
        "unsolved_cases_in_country": "<b>🕵️ คดียังไม่คลี่คลายใน {}:</b>",
        "you_havent_submitted_cases": "📂 คุณยังไม่ได้ส่งคดีใดๆ เข้ามาเลย",
        "your_submitted_cases_title": "<b>📂 คดีที่คุณส่งเข้ามา:</b>",
        "case_details_title": "<b>📄 รายละเอียดคดี</b>",
        "case_no_label": "• <b>เลขคดี:</b> {}",
        "name_label": "• <b>ชื่อ:</b> {}",
        "status_label": "• <b>สถานะ:</b> {}",
        "last_seen_label": "• <b>พบครั้งสุดท้าย:</b> {}",
        "reward_label": "• <b>รางวัล:</b> {} {}",
        "created_at_label": "• <b>สร้างเมื่อ:</b> {}",
        "invalid_selection_error": "⚠️ <b>เลือกไม่ถูกต้อง</b>\n\nกรุณาเลือกตัวเลือกที่ถูกต้อง",
    },

    "vi": {
        "community_stats_title": "<b>📊 Thống kê Cộng đồng PeopleTrace</b>",
        "total_cases_submitted": "• <b>Tổng số trường hợp đã gửi:</b> {}",
        "regions_covered": "• <b>Khu vực được bao phủ:</b> {} quốc gia, {} thành phố",
        "unsolved_cases": "• <b>🕵️‍♂️ Trường hợp chưa giải quyết:</b> {} (Nhấn bên dưới 👇)",
        "successfully_found": "• <b>✅ Đã tìm thấy thành công:</b> {}",
        "average_reward_offered": "• <b>🎁 Phần thưởng trung bình:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ Vụ giải quyết nhanh nhất:</b> {} ngày",
        "top_active_region": "• <b>🔥 Khu vực hoạt động mạnh nhất:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍🧑 Nhân khẩu học phổ biến:</b> {}",
        "highest_reward": "• <b>💰 Phần thưởng cao nhất:</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ Xem các vụ chưa giải quyết",
        "view_local_stats_button": "📍 Xem thống kê địa phương",
        "my_submissions_button": "📂 Gửi của tôi",
        "back_button": "⬅️ Quay lại",
        "local_stats_coming_soon": "📍 Sắp ra mắt: Thống kê địa phương dựa trên vị trí của bạn.",
        "unsolved_country_list": "Chọn một quốc gia từ danh sách dưới đây:",
        "no_unsolved_country": "📍 Không có trường hợp nào chưa giải quyết ở bất kỳ quốc gia nào.",  # <-- NEW FIELD

        "no_cases_in_country": "Không có trường hợp nào trong {}.",
        "unsolved_cases_in_country": "<b>🕵️ Các vụ chưa giải quyết tại {}:</b>",
        "you_havent_submitted_cases": "📂 Bạn chưa gửi bất kỳ trường hợp nào.",
        "your_submitted_cases_title": "<b>📂 Các trường hợp đã gửi:</b>",
        "case_details_title": "<b>📄 Chi tiết trường hợp</b>",
        "case_no_label": "• <b>Mã hồ sơ:</b> {}",
        "name_label": "• <b>Tên:</b> {}",
        "status_label": "• <b>Trạng thái:</b> {}",
        "last_seen_label": "• <b>Lần cuối thấy:</b> {}",
        "reward_label": "• <b>Phần thưởng:</b> {} {}",
        "created_at_label": "• <b>Ngày tạo:</b> {}",
        "invalid_selection_error": "⚠️ <b>Lựa chọn không hợp lệ</b>\n\nVui lòng chọn tùy chọn hợp lệ.",
    },

    "ur": {
        "community_stats_title": "<b>📊 پیپل ٹریس کمیونٹی اعداد و شمار</b>",
        "total_cases_submitted": "• <b>کل معاملات جمع کروائے گئے:</b> {}",
        "regions_covered": "• <b>کور کیے گئے علاقے:</b> {} ممالک، {} شہروں",
        "unsolved_cases": "• <b>🕵️‍♂️ غیر حل شدہ معاملات:</b> {} (ذیل میں کلک کریں 👇)",
        "successfully_found": "• <b>✅ کامیابی سے تلاش کیا گیا:</b> {}",
        "average_reward_offered": "• <b>🎁 اوسط انعام کی پیشکش:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ سب سے زیادہ تیزی سے حل شدہ معاملہ:</b> {} دن",
        "top_active_region": "• <b>🔥 سب سے زیادہ فعال علاقہ:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍🧑 عام آبادی:</b> {}",
        "highest_reward": "• <b>💰 سب سے زیادہ انعام:</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ غیر حل شدہ معاملات دیکھیں",
        "view_local_stats_button": "📍 مقامی اعداد و شمار دیکھیں",
        "my_submissions_button": "📂 میری جمع کروائیں",
        "back_button": "⬅️ واپس",
        "local_stats_coming_soon": "📍 قریب میں: اپنی لوکیشن کی بنیاد پر مقامی اعداد و شمار۔",
        "unsolved_country_list": "ذیل میں لسٹ سے ایک ملک منتخب کریں:",
        "no_unsolved_country": "📍 کسی بھی ملک میں غیر حل شدہ معاملات نہیں ہیں۔",  # <-- NEW FIELD

        "no_cases_in_country": "{} میں کوئی معاملہ نہیں ملا۔",
        "unsolved_cases_in_country": "<b>🕵️ {} میں غیر حل شدہ معاملات:</b>",
        "you_havent_submitted_cases": "📂 آپ نے ابھی تک کوئی معاملہ جمع نہیں کروایا۔",
        "your_submitted_cases_title": "<b>📂 آپ کے جمع کروائے گئے معاملات:</b>",
        "case_details_title": "<b>📄 معاملے کی تفصیلات</b>",
        "case_no_label": "• <b>کیس نمبر:</b> {}",
        "name_label": "• <b>نام:</b> {}",
        "status_label": "• <b>حالت:</b> {}",
        "last_seen_label": "• <b>آخری بار دیکھا گیا:</b> {}",
        "reward_label": "• <b>انعام:</b> {} {}",
        "created_at_label": "• <b>بنایا گیا:</b> {}",
        "invalid_selection_error": "⚠️ <b>غلط انتخاب</b>\n\nبراہ کرم درست اختیار منتخب کریں۔",
    },

    "ja": {
        "community_stats_title": "<b>📊 PeopleTrace コミュニティ統計</b>",
        "total_cases_submitted": "• <b>提出された総ケース数：</b> {}",
        "regions_covered": "• <b>カバー地域：</b> {} 国、{} 都市",
        "unsolved_cases": "• <b>🕵️‍♂️ 未解決のケース：</b> {} （下記をクリック👇）",
        "successfully_found": "• <b>✅ 成功裏に発見：</b> {}",
        "average_reward_offered": "• <b>🎁 平均報奨金：</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ 最速で解決したケース：</b> {} 日",
        "top_active_region": "• <b>🔥 最も活発な地域：</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ 一般的な人口統計：</b> {}",
        "highest_reward": "• <b>💰 最高報奨金：</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ 未解決のケースを表示",
        "view_local_stats_button": "📍 地域統計を表示",
        "my_submissions_button": "📂 私の投稿",
        "back_button": "⬅️ 戻る",
        "local_stats_coming_soon": "📍 間もなくリリース：あなたの位置に基づく地域統計。",
        "unsolved_country_list": "以下から国を選択してください：",
        "no_unsolved_country": "📍 どの国にも未解決のケースはありません。",  # <-- NEW FIELD

        "no_cases_in_country": "{} にはケースが見つかりませんでした。",
        "unsolved_cases_in_country": "<b>🕵️ {} 内の未解決のケース：</b>",
        "you_havent_submitted_cases": "📂 ケースはまだ送信していません。",
        "your_submitted_cases_title": "<b>📂 提出済みのケース：</b>",
        "case_details_title": "<b>📄 ケース詳細</b>",
        "case_no_label": "• <b>ケース番号：</b> {}",
        "name_label": "• <b>名前：</b> {}",
        "status_label": "• <b>ステータス：</b> {}",
        "last_seen_label": "• <b>最後に見た場所：</b> {}",
        "reward_label": "• <b>報奨金：</b> {} {}",
        "created_at_label": "• <b>作成日時：</b> {}",
        "invalid_selection_error": "⚠️ <b>無効な選択です</b>\n\n有効なオプションを選択してください。",
    },

    "ko": {
        "community_stats_title": "<b>📊 PeopleTrace 커뮤니티 통계</b>",
        "total_cases_submitted": "• <b>제출된 총 사건 수:</b> {}",
        "regions_covered": "• <b>포함 지역:</b> {} 국가, {} 도시",
        "unsolved_cases": "• <b>🕵️‍♂️ 미해결 사건:</b> {} (아래 클릭 👇)",
        "successfully_found": "• <b>✅ 성공적으로 발견됨:</b> {}",
        "average_reward_offered": "• <b>🎁 평균 제안 보상금:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ 가장 빠르게 해결된 사건:</b> {} 일",
        "top_active_region": "• <b>🔥 가장 활발한 지역:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ 일반 인구통계:</b> {}",
        "highest_reward": "• <b>💰 최고 보상금:</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ 미해결 사건 보기",
        "view_local_stats_button": "📍 지역 통계 보기",
        "my_submissions_button": "📂 내 제출물",
        "back_button": "⬅️ 뒤로 가기",
        "local_stats_coming_soon": "📍 곧 출시: 귀하의 위치 기반 지역 통계.",
        "unsolved_country_list": "아래 목록에서 국가를 선택하세요:",
        "no_unsolved_country": "📍 어느 나라에도 미해결 사건이 없습니다.",  # <-- NEW FIELD

        "no_cases_in_country": "{}에 사건이 없습니다.",
        "unsolved_cases_in_country": "<b>🕵️ {}의 미해결 사건:</b>",
        "you_havent_submitted_cases": "📂 아직 사건을 제출하지 않았습니다.",
        "your_submitted_cases_title": "<b>📂 귀하가 제출한 사건:</b>",
        "case_details_title": "<b>📄 사건 상세 정보</b>",
        "case_no_label": "• <b>사건 번호:</b> {}",
        "name_label": "• <b>이름:</b> {}",
        "status_label": "• <b>상태:</b> {}",
        "last_seen_label": "• <b>마지막으로 본 장소:</b> {}",
        "reward_label": "• <b>보상금:</b> {} {}",
        "created_at_label": "• <b>생성 날짜:</b> {}",
        "invalid_selection_error": "⚠️ <b>잘못된 선택입니다</b>\n\n유효한 옵션을 선택해 주세요.",
    },

    "km": {
        "community_stats_title": "<b>📊 ស្ថិតិសហគមន៍ PeopleTrace</b>",
        "total_cases_submitted": "• <b>ចំនួនករណីដែលបានដាក់ជូនទាំងអស់:</b> {}",
        "regions_covered": "• <b>តំបន់ដែលបានគ្របដណ្ដប់:</b> {} ប្រទេស, {} ទីក្រុង",
        "unsolved_cases": "• <b>🕵️‍♂️ ករណីមិនទាន់ដោះស្រាយ:</b> {} (ចុចខាងក្រោម 👇)",
        "successfully_found": "• <b>✅ រកឃើញដោយជោគជ័យ:</b> {}",
        "average_reward_offered": "• <b>🎁 រង្វាន់ជាមធ្យម:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ ករណីដោះស្រាយលឿនបំផុត:</b> {} ថ្ងៃ",
        "top_active_region": "• <b>🔥 តំបន់សកម្មភាពខ្ពស់បំផុត:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ ប្រជាសាស្ត្រទូទៅ:</b> {}",
        "highest_reward": "• <b>💰 រង្វាន់ខ្ពស់បំផុត:</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ មើលករណីមិនទាន់ដោះស្រាយ",
        "view_local_stats_button": "📍 មើលស្ថិតិក្នុងស្រុក",
        "my_submissions_button": "📂 ការដាក់ស្នើរបស់ខ្ញុំ",
        "back_button": "⬅️ ត្រលប់ក្រោយ",
        "local_stats_coming_soon": "📍 បើកដំណើរការឆាប់ៗនេះ: ស្ថិតិក្នុងស្រុកដោយផ្អែកលើទីតាំងរបស់អ្នក។",
        "unsolved_country_list": "ជ្រើសរើសប្រទេសពីបញ្ជីខាងក្រោម៖",
        "no_unsolved_country": "📍 គ្មានករណីមិនទាន់ដោះស្រាយនៅក្នុងប្រទេសណាមួយទេ។",  # <-- NEW FIELD

        "no_cases_in_country": "គ្មានករណីនៅក្នុង {}។",
        "unsolved_cases_in_country": "<b>🕵️ ករណីមិនទាន់ដោះស្រាយនៅ {}:</b>",
        "you_havent_submitted_cases": "📂 អ្នកមិនទាន់បានដាក់ស្នើករណីណាមួយទេ។",
        "your_submitted_cases_title": "<b>📂 ករណីដែលអ្នកបានដាក់ស្នើ:</b>",
        "case_details_title": "<b>📄 ព័ត៌មានលម្អិតអំពីករណី</b>",
        "case_no_label": "• <b>លេខករណី:</b> {}",
        "name_label": "• <b>ឈ្មោះ:</b> {}",
        "status_label": "• <b>ស្ថានភាព:</b> {}",
        "last_seen_label": "• <b>លើកចុងក្រោយដែលបានឃើញ:</b> {}",
        "reward_label": "• <b>រង្វាន់:</b> {} {}",
        "created_at_label": "• <b>បង្កើតនៅ:</b> {}",
        "invalid_selection_error": "⚠️ <b>ការជ្រើសរើសមិនត្រឹមត្រូវ</b>\n\nសូមជ្រើសរើសជម្រើសដែលត្រឹមត្រូវ។",
    },

    "id": {
        "community_stats_title": "<b>📊 Statistik Komunitas PeopleTrace</b>",
        "total_cases_submitted": "• <b>Total Kasus Diajukan:</b> {}",
        "regions_covered": "• <b>Wilayah Terjangkau:</b> {} negara, {} kota",
        "unsolved_cases": "• <b>🕵️‍♂️ Kasus Belum Terpecahkan:</b> {} (Klik di bawah 👇)",
        "successfully_found": "• <b>✅ Berhasil Ditemukan:</b> {}",
        "average_reward_offered": "• <b>🎁 Rata-rata Hadiah:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ Kasus Tercepat Diselesaikan:</b> {} hari",
        "top_active_region": "• <b>🔥 Wilayah Paling Aktif:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ Demografi Umum:</b> {}",
        "highest_reward": "• <b>💰 Hadiah Tertinggi:</b> {} USDT",
        "view_unsolved_cases_button": "🕵️ Lihat Kasus Belum Terpecahkan",
        "view_local_stats_button": "📍 Lihat Statistik Lokal",
        "my_submissions_button": "📂 Kiriman Saya",
        "back_button": "⬅️ Kembali",
        "local_stats_coming_soon": "📍 Segera hadir: Statistik lokal berdasarkan lokasi Anda.",
        "unsolved_country_list": "Pilih negara dari daftar di bawah ini:",
        "no_unsolved_country": "📍 Tidak ada kasus yang belum terselesaikan di semua negara.",  # <-- NEW FIELD

        "no_cases_in_country": "Tidak ada kasus di {}.",
        "unsolved_cases_in_country": "<b>🕵️ Kasus yang Belum Diselesaikan di {}:</b>",
        "you_havent_submitted_cases": "📂 Anda belum mengirimkan kasus apa pun.",
        "your_submitted_cases_title": "<b>📂 Kasus yang Telah Dikirim:</b>",
        "case_details_title": "<b>📄 Detail Kasus</b>",
        "case_no_label": "• <b>No. Kasus:</b> {}",
        "name_label": "• <b>Nama:</b> {}",
        "status_label": "• <b>Status:</b> {}",
        "last_seen_label": "• <b>Terakhir Dilihat:</b> {}",
        "reward_label": "• <b>Reward:</b> {} {}",
        "created_at_label": "• <b>Dibuat pada:</b> {}",
        "invalid_selection_error": "⚠️ <b>Pemilihan tidak valid</b>\n\nSilakan pilih opsi yang benar.",
    }
}