STATS_CONSTANT = {
    "english": {
        # Main stats page
        "community_stats_title": "<b>📊 PeopleTrace Community Stats</b>",
        "total_cases_submitted": "• <b>Total Cases Submitted:</b> {}",
        "regions_covered": "• <b>Regions Covered:</b> {} countries, {} cities",
        "unsolved_cases": "• <b>🕵️‍♂️ Unsolved Cases:</b> {} (Click below 👇)",
        "successfully_found": "• <b>✅ Successfully Found:</b> {}",
        "average_reward_offered": "• <b>🎁 Average Reward Offered:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ Fastest Case Solved:</b> {} days",
        "top_active_region": "• <b>🔥 Top Active Region:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ Common Demographic:</b> {}",
        "highest_reward": "• <b>💰 Highest Reward:</b> {} USDT",

        # Admin daily stats broadcast
        "admin_daily_stats_title": "<b>📊 PeopleTrace Community Stats</b>\n\n<b>Here’s how the community is doing right now:</b>",
        "admin_total_cases_submitted": "👤 <b>Total Cases Submitted:</b> {}",
        "admin_regions_covered": "🗺️ <b>Regions Covered:</b> {} countries, {} cities",
        "admin_unsolved_cases": "🚨 <b>Unsolved Cases:</b> {} 🡨 Click for details",
        "admin_successfully_found": "✅ <b>Successfully Found:</b> {}",
        "admin_average_reward_offered": "🎯 <b>Average Reward Offered:</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>Fastest Case Solved:</b> {} days",
        "admin_top_active_region": "🔎 <b>Top Active Region:</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>Most Commonly Searched Demographic:</b> {}",
        "admin_highest_reward": "💸 <b>Highest Reward Offered:</b> {} USDT",
        "admin_footer_message": "🧠 These real-time numbers help guide your choices — from reward amount to region focus. Be a part of our growing impact.",

        # Buttons
        "view_unsolved_cases_button": "🕵️ View Unsolved Cases",

        "view_local_stats_button": "🔍 View Local Stats",
        "my_submissions_button": "📂 View My Submissions",
        "back_to_menu_button": "🔙 Back to Menu",

        # Menu messages
        "local_stats_coming_soon": "📍 Coming soon: Local Stats based on your location.",
        "unsolved_country_list": "Choose a country from the list below:",
        "no_unsolved_country": "📍 No unsolved cases in any country.",

        # Country case list
        "no_cases_in_country": "No cases found in {}.",
        "unsolved_cases_in_country": "<b>🕵️ Unsolved Cases in {}:</b>",

        # User cases
        "you_havent_submitted_cases": "📂 You haven’t submitted any cases yet.",
        "your_submitted_cases_title": "<b>📂 Your Submitted Cases:</b>",

        # Case details
        "case_details_title": "<b>📄 Case Details</b>",
        "case_no_label": "• <b>Case No:</b> {}",
        "name_label": "• <b>Name:</b> {}",
        "status_label": "• <b>Status:</b> {}",
        "last_seen_label": "• <b>Last Seen:</b> {}",
        "reward_label": "• <b>Reward:</b> {} {}",
        "created_at_label": "• <b>Created At:</b> {}",

        # Errors
        "invalid_selection_error": "⚠️ <b>Invalid Selection</b>\n\nPlease choose a valid option.",

        # New local stats strings
        "ask_for_local_stats_input": "📍 Please share your city and province.",
        "invalid_local_stats_format": "⚠️ <b>Invalid Format</b>\n\nPlease enter as: <i>City, Province</i>",
        "no_local_cases_found": "🕵️ No cases found in {city}, {province}.",
        "local_cases_found_title": "<b>📂 Cases in {city}, {province}:</b>",
    },

    "chinese": {
        "community_stats_title": "<b>📊 PeopleTrace 社区数据</b>",
        "total_cases_submitted": "• <b>提交的总案件数：</b> {}",
        "regions_covered": "• <b>覆盖区域：</b> {} 个国家，{} 个城市",
        "unsolved_cases": "• <b>🕵️‍♂️ 未解决案件：</b> {} (点击下方 👇)",
        "successfully_found": "• <b>✅ 已成功找回：</b> {}",
        "average_reward_offered": "• <b>🎁 平均悬赏金：</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ 最快解决时间：</b> {} 天",
        "top_active_region": "• <b>🔥 活跃地区：</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ 常见人群特征：</b> {}",
        "highest_reward": "• <b>💰 最高悬赏金：</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 PeopleTrace 社区数据</b>\n\n以下是社区当前情况：",
        "admin_total_cases_submitted": "👤 <b>提交的总案件数：</b> {}",
        "admin_regions_covered": "🗺️ <b>覆盖区域：</b> {} 个国家，{} 个城市",
        "admin_unsolved_cases": "🚨 <b>未解决案件：</b> {} 🡨 点击查看详情",
        "admin_successfully_found": "✅ <b>已成功找回：</b> {}",
        "admin_average_reward_offered": "🎯 <b>平均悬赏金：</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>最快解决时间：</b> {} 天",
        "admin_top_active_region": "🔎 <b>最活跃地区：</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>最常搜索的人群特征：</b> {}",
        "admin_highest_reward": "💸 <b>最高悬赏金：</b> {} USDT",
        "admin_footer_message": "🧠 这些实时数据有助于指导你的决策——从悬赏金额到关注区域。加入我们不断增长的影响！",

        "view_unsolved_cases_button": "🕵️ 查看未解决案件",
        "view_local_stats_button": "📍 查看本地统计",
        "my_submissions_button": "📂 我的提交",
        "back_button": "⬅️ 返回",
        "admin_view_local_stats_button": "🔍 查看本地统计",
        "admin_my_submissions_button": "📂 查看我的提交",
        "admin_back_to_menu_button": "🔙 返回菜单",

        "local_stats_coming_soon": "📍 即将推出：基于你所在位置的本地统计数据。",
        "unsolved_country_list": "请从以下列表中选择一个国家：",
        "no_unsolved_country": "📍 目前没有未解决案件的国家。",

        "no_cases_in_country": "在 {} 中未找到任何案件。",
        "unsolved_cases_in_country": "<b>🕵️ 在 {} 中的未解决案件：</b>",

        "you_havent_submitted_cases": "📂 您尚未提交任何案件。",
        "your_submitted_cases_title": "<b>📂 您提交的案件：</b>",

        "case_details_title": "<b>📄 案件详情</b>",
        "case_no_label": "• <b>案件编号：</b> {}",
        "name_label": "• <b>姓名：</b> {}",
        "status_label": "• <b>状态：</b> {}",
        "last_seen_label": "• <b>最后出现：</b> {}",
        "reward_label": "• <b>悬赏金：</b> {} {}",
        "created_at_label": "• <b>创建时间：</b> {}",

        "invalid_selection_error": "⚠️ <b>无效选择</b>\n\n请选择有效选项。",

        "ask_for_local_stats_input": "📍 请提供您的城市和省份。",
        "invalid_local_stats_format": "⚠️ <b>格式错误</b>\n\n请输入格式为：<i>城市, 省份</i>",
        "no_local_cases_found": "🕵️ 在 {city}, {province} 中未找到任何案件。",
        "local_cases_found_title": "<b>📂 在 {city}, {province} 中的案件：</b>",
    },

    "malay": {
        "community_stats_title": "<b>📊 Statistik Komuniti PeopleTrace</b>",
        "total_cases_submitted": "• <b>Jumlah Kes Dihantar:</b> {}",
        "regions_covered": "• <b>Kawasan Diliputi:</b> {} negara, {} bandar",
        "unsolved_cases": "• <b>🕵️‍♂️ Kes Belum Diselesaikan:</b> {} (Klik di bawah 👇)",
        "successfully_found": "• <b>✅ Berjaya Dijumpai:</b> {}",
        "average_reward_offered": "• <b>🎁 Purata Ganjaran:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ Kes Terpantas Diselesaikan:</b> {} hari",
        "top_active_region": "• <b>🔥 Kawasan Paling Aktif:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ Kumpulan Demografi Biasa:</b> {}",
        "highest_reward": "• <b>💰 Ganjaran Tertinggi:</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 Statistik Komuniti PeopleTrace</b>\n\nInilah perkembangan komuniti pada masa ini:",
        "admin_total_cases_submitted": "👤 <b>Jumlah Kes Dihantar:</b> {}",
        "admin_regions_covered": "🗺️ <b>Kawasan Diliputi:</b> {} negara, {} bandar",
        "admin_unsolved_cases": "🚨 <b>Kes Belum Diselesaikan:</b> {} 🡨 Klik untuk maklumat lanjut",
        "admin_successfully_found": "✅ <b>Berjaya Dijumpai:</b> {}",
        "admin_average_reward_offered": "🎯 <b>Purata Ganjaran:</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>Kes Terpantas Diselesaikan:</b> {} hari",
        "admin_top_active_region": "🔎 <b>Kawasan Paling Aktif:</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>Kumpulan Demografi Biasa:</b> {}",
        "admin_highest_reward": "💸 <b>Ganjaran Tertinggi:</b> {} USDT",
        "admin_footer_message": "🧠 Nombor-nombor masa nyata ini membantu memandu pilihan anda – dari jumlah ganjaran hingga fokus kawasan. Jadi sebahagian daripada kesan berkembang kami!",

        "view_unsolved_cases_button": "🕵️ Lihat Kes Belum Diselesaikan",
        "view_local_stats_button": "📍 Lihat Statistik Tempatan",
        "my_submissions_button": "📂 Hantaran Saya",
        "back_button": "⬅️ Kembali",
        "admin_view_local_stats_button": "🔍 Lihat Statistik Tempatan",
        "admin_my_submissions_button": "📂 Lihat Hantaran Saya",
        "admin_back_to_menu_button": "🔙 Kembali ke Menu",

        "local_stats_coming_soon": "📍 Akan datang: Statistik tempatan berdasarkan lokasi anda.",
        "unsolved_country_list": "Pilih sebuah negara dari senarai di bawah:",
        "no_unsolved_country": "📍 Tiada kes belum diselesaikan di mana-mana negara.",

        "no_cases_in_country": "Tiada kes ditemui di {}.",
        "unsolved_cases_in_country": "<b>🕵️ Kes Belum Diselesaikan di {}:</b>",

        "you_havent_submitted_cases": "📂 Anda belum menghantar sebarang kes lagi.",
        "your_submitted_cases_title": "<b>📂 Kes Yang Telah DiHantar:</b>",

        "case_details_title": "<b>📄 Butiran Kes</b>",
        "case_no_label": "• <b>No. Kes:</b> {}",
        "name_label": "• <b>Nama:</b> {}",
        "status_label": "• <b>Status:</b> {}",
        "last_seen_label": "• <b>Kali Terakhir Dilihat:</b> {}",
        "reward_label": "• <b>Ganjaran:</b> {} {}",
        "created_at_label": "• <b>Dicipta Pada:</b> {}",

        "invalid_selection_error": "⚠️ <b>Pemilihan Tidak Sah</b>\n\nSila pilih pilihan yang sah.",

        "ask_for_local_stats_input": "📍 Sila kongsi bandar dan negeri anda.",
        "invalid_local_stats_format": "⚠️ <b>Format Tidak Sah</b>\n\nSila masukkan seperti: <i>Bandar, Negeri</i>",
        "no_local_cases_found": "🕵️ Tiada kes ditemui di {city}, {province}.",
        "local_cases_found_title": "<b>📂 Kes di {city}, {province}:</b>",
    },

    "indonesian": {
        "community_stats_title": "<b>📊 Statistik Komunitas PeopleTrace</b>",
        "total_cases_submitted": "• <b>Total Kasus Diajukan:</b> {}",
        "regions_covered": "• <b>Wilayah Terliputi:</b> {} negara, {} kota",
        "unsolved_cases": "• <b>🕵️‍♂️ Kasus Belum Terpecahkan:</b> {} (Klik di bawah 👇)",
        "successfully_found": "• <b>✅ Berhasil Ditemukan:</b> {}",
        "average_reward_offered": "• <b>🎁 Rata-rata Hadiah:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ Kasus Tercepat Diselesaikan:</b> {} hari",
        "top_active_region": "• <b>🔥 Wilayah Paling Aktif:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ Demografi Umum:</b> {}",
        "highest_reward": "• <b>💰 Hadiah Tertinggi:</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 Statistik Komunitas PeopleTrace</b>\n\nBegini kondisi komunitas saat ini:",
        "admin_total_cases_submitted": "👤 <b>Total Kasus Diajukan:</b> {}",
        "admin_regions_covered": "🗺️ <b>Wilayah Terliputi:</b> {} negara, {} kota",
        "admin_unsolved_cases": "🚨 <b>Kasus Belum Terpecahkan:</b> {} 🡨 Klik untuk detail",
        "admin_successfully_found": "✅ <b>Berhasil Ditemukan:</b> {}",
        "admin_average_reward_offered": "🎯 <b>Rata-rata Hadiah:</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>Kasus Tercepat Diselesaikan:</b> {} hari",
        "admin_top_active_region": "🔎 <b>Wilayah Paling Aktif:</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>Demografi Umum:</b> {}",
        "admin_highest_reward": "💸 <b>Hadiah Tertinggi:</b> {} USDT",
        "admin_footer_message": "🧠 Angka-angka real-time ini membantu memandu pilihan Anda—dari besarnya hadiah hingga fokus wilayah. Jadilah bagian dari dampak positif yang terus berkembang.",

        "view_unsolved_cases_button": "🕵️ Lihat Kasus Belum Terpecahkan",
        "view_local_stats_button": "📍 Lihat Statistik Lokal",
        "my_submissions_button": "📂 Pengajuan Saya",
        "back_button": "⬅️ Kembali",
        "admin_view_local_stats_button": "🔍 Lihat Statistik Lokal",
        "admin_my_submissions_button": "📂 Lihat Pengajuan Saya",
        "admin_back_to_menu_button": "🔙 Kembali ke Menu",

        "local_stats_coming_soon": "📍 Segera hadir: Statistik lokal berdasarkan lokasi Anda.",
        "unsolved_country_list": "Pilih negara dari daftar di bawah:",
        "no_unsolved_country": "📍 Tidak ada kasus belum terpecahkan di semua negara.",

        "no_cases_in_country": "Tidak ada kasus ditemukan di {}.",
        "unsolved_cases_in_country": "<b>🕵️ Kasus Belum Terpecahkan di {}:</b>",

        "you_havent_submitted_cases": "📂 Anda belum mengajukan kasus apa pun.",
        "your_submitted_cases_title": "<b>📂 Kasus Yang Telah Diajukan:</b>",

        "case_details_title": "<b>📄 Detail Kasus</b>",
        "case_no_label": "• <b>No. Kasus:</b> {}",
        "name_label": "• <b>Nama:</b> {}",
        "status_label": "• <b>Status:</b> {}",
        "last_seen_label": "• <b>Terkahir Terlihat:</b> {}",
        "reward_label": "• <b>Hadiah:</b> {} {}",
        "created_at_label": "• <b>Dibuat Pada:</b> {}",

        "invalid_selection_error": "⚠️ <b>Pilihan Tidak Valid</b>\n\nSilakan pilih opsi yang valid.",

        "ask_for_local_stats_input": "📍 Silakan bagikan kota dan provinsi Anda.",
        "invalid_local_stats_format": "⚠️ <b>Format Tidak Valid</b>\n\nSilakan masukkan sebagai: <i>Kota, Provinsi</i>",
        "no_local_cases_found": "🕵️ Tidak ada kasus ditemukan di {city}, {province}.",
        "local_cases_found_title": "<b>📂 Kasus di {city}, {province}:</b>",
    },

        "thai": {
        # ภาษาไทย - Thai
        "community_stats_title": "<b>📊 สถิติชุมชน PeopleTrace</b>",
        "total_cases_submitted": "• <b>จำนวนคดีที่ส่งทั้งหมด:</b> {}",
        "regions_covered": "• <b>พื้นที่ครอบคลุม:</b> {} ประเทศ, {} เมือง",
        "unsolved_cases": "• <b>🕵️‍♂️ คดียังไม่คลี่คลาย:</b> {} (คลิกด้านล่าง 👇)",
        "successfully_found": "• <b>✅ พบตัวแล้ว:</b> {}",
        "average_reward_offered": "• <b>🎁 เงินรางวัลเฉลี่ย:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ คดีเร็วที่สุดที่คลี่คลาย:</b> {} วัน",
        "top_active_region": "• <b>🔥 พื้นที่ใช้งานมากที่สุด:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ กลุ่มประชากรหลัก:</b> {}",
        "highest_reward": "• <b>💰 เงินรางวัลสูงสุด:</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 สถิติชุมชน PeopleTrace</b>\n\nสถานะของชุมชนในขณะนี้:",
        "admin_total_cases_submitted": "👤 <b>จำนวนคดีที่ส่งทั้งหมด:</b> {}",
        "admin_regions_covered": "🗺️ <b>พื้นที่ครอบคลุม:</b> {} ประเทศ, {} เมือง",
        "admin_unsolved_cases": "🚨 <b>คดียังไม่คลี่คลาย:</b> {} 🡨 คลิกเพื่อดูรายละเอียด",
        "admin_successfully_found": "✅ <b>พบตัวแล้ว:</b> {}",
        "admin_average_reward_offered": "🎯 <b>เงินรางวัลเฉลี่ย:</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>คดีเร็วที่สุดที่คลี่คลาย:</b> {} วัน",
        "admin_top_active_region": "🔎 <b>พื้นที่ใช้งานมากที่สุด:</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>กลุ่มประชากรหลัก:</b> {}",
        "admin_highest_reward": "💸 <b>เงินรางวัลสูงสุด:</b> {} USDT",
        "admin_footer_message": "🧠 ตัวเลขแบบเรียลไทม์เหล่านี้จะช่วยให้คุณวางแผนได้ดีขึ้น เช่น การกำหนดเงินรางวัลหรือเลือกพื้นที่สนใจ มาร่วมสร้างการเปลี่ยนแปลงไปด้วยกัน!",

        "view_unsolved_cases_button": "🕵️ ดูคดียังไม่คลี่คลาย",
        "view_local_stats_button": "📍 ดูสถิติในพื้นที่",
        "my_submissions_button": "📂 ส่งคำขอของฉัน",
        "back_button": "⬅️ กลับ",
        "admin_view_local_stats_button": "🔍 ดูสถิติในพื้นที่",
        "admin_my_submissions_button": "📂 ดูคำขอของฉัน",
        "admin_back_to_menu_button": "🔙 กลับสู่เมนูหลัก",

        "local_stats_coming_soon": "📍 เร็ว ๆ นี้: สถิติเฉพาะตามตำแหน่งของคุณ",
        "unsolved_country_list": "เลือกประเทศจากรายชื่อข้างล่าง:",
        "no_unsolved_country": "📍 ไม่มีคดียังไม่คลี่คลายในประเทศใดเลย.",

        "no_cases_in_country": "ไม่พบคดีใน {}.",
        "unsolved_cases_in_country": "<b>🕵️ คดียังไม่คลี่คลายใน {}:</b>",

        "you_havent_submitted_cases": "📂 คุณยังไม่ได้ส่งคดีใด ๆ เลย",
        "your_submitted_cases_title": "<b>📂 คดีที่คุณส่งแล้ว:</b>",

        "case_details_title": "<b>📄 รายละเอียดคดี</b>",
        "case_no_label": "• <b>หมายเลขคดี:</b> {}",
        "name_label": "• <b>ชื่อ:</b> {}",
        "status_label": "• <b>สถานะ:</b> {}",
        "last_seen_label": "• <b>พบครั้งสุดท้าย:</b> {}",
        "reward_label": "• <b>รางวัล:</b> {} {}",
        "created_at_label": "• <b>สร้างเมื่อ:</b> {}",

        "invalid_selection_error": "⚠️ <b>การเลือกไม่ถูกต้อง</b>\n\nกรุณาเลือกตัวเลือกที่ถูกต้อง",

        "ask_for_local_stats_input": "📍 กรุณากรอกเมืองและจังหวัดของคุณ",
        "invalid_local_stats_format": "⚠️ <b>รูปแบบไม่ถูกต้อง</b>\n\nกรุณากรอกเป็น: <i>เมือง, จังหวัด</i>",
        "no_local_cases_found": "🕵️ ไม่พบคดีใน {city}, {province}",
        "local_cases_found_title": "<b>📂 คดีใน {city}, {province}:</b>",
    },

    "vietnamese": {
        # Tiếng Việt - Vietnamese
        "community_stats_title": "<b>📊 Thống kê cộng đồng PeopleTrace</b>",
        "total_cases_submitted": "• <b>Tổng số trường hợp đã gửi:</b> {}",
        "regions_covered": "• <b>Khu vực bao phủ:</b> {} quốc gia, {} thành phố",
        "unsolved_cases": "• <b>🕵️‍♂️ Trường hợp chưa giải quyết:</b> {} (Nhấn vào bên dưới 👇)",
        "successfully_found": "• <b>✅ Đã tìm thấy:</b> {}",
        "average_reward_offered": "• <b>🎁 Phần thưởng trung bình:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ Nhanh nhất được giải:</b> {} ngày",
        "top_active_region": "• <b>🔥 Khu vực hoạt động nhiều nhất:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ Nhóm tuổi phổ biến:</b> {}",
        "highest_reward": "• <b>💰 Phần thưởng cao nhất:</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 Thống kê cộng đồng PeopleTrace</b>\n\nTình hình hiện tại của cộng đồng:",
        "admin_total_cases_submitted": "👤 <b>Tổng số trường hợp đã gửi:</b> {}",
        "admin_regions_covered": "🗺️ <b>Khu vực bao phủ:</b> {} quốc gia, {} thành phố",
        "admin_unsolved_cases": "🚨 <b>Trường hợp chưa giải quyết:</b> {} 🡨 Nhấn để xem chi tiết",
        "admin_successfully_found": "✅ <b>Đã tìm thấy:</b> {}",
        "admin_average_reward_offered": "🎯 <b>Phần thưởng trung bình:</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>Nhanh nhất được giải:</b> {} ngày",
        "admin_top_active_region": "🔎 <b>Khu vực hoạt động nhiều nhất:</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>Nhóm tuổi phổ biến:</b> {}",
        "admin_highest_reward": "💸 <b>Phần thưởng cao nhất:</b> {} USDT",
        "admin_footer_message": "🧠 Những con số thời gian thực này sẽ giúp bạn đưa ra quyết định tốt hơn — từ mức phần thưởng đến khu vực tập trung. Hãy là một phần trong tác động đang phát triển của chúng tôi.",

        "view_unsolved_cases_button": "🕵️ Xem các trường hợp chưa giải",
        "view_local_stats_button": "📍 Xem thống kê địa phương",
        "my_submissions_button": "📂 Gửi yêu cầu của tôi",
        "back_button": "⬅️ Trở lại",
        "admin_view_local_stats_button": "🔍 Xem thống kê địa phương",
        "admin_my_submissions_button": "📂 Xem yêu cầu của tôi",
        "admin_back_to_menu_button": "🔙 Về menu chính",

        "local_stats_coming_soon": "📍 Sắp có: Thống kê dựa trên vị trí của bạn.",
        "unsolved_country_list": "Chọn quốc gia từ danh sách bên dưới:",
        "no_unsolved_country": "📍 Không có trường hợp nào chưa giải ở bất kỳ quốc gia nào.",

        "no_cases_in_country": "Không tìm thấy trường hợp nào ở {}.",
        "unsolved_cases_in_country": "<b>🕵️ Các trường hợp chưa giải ở {}:</b>",

        "you_havent_submitted_cases": "📂 Bạn chưa gửi bất kỳ trường hợp nào.",
        "your_submitted_cases_title": "<b>📂 Các trường hợp đã gửi:</b>",

        "case_details_title": "<b>📄 Chi tiết trường hợp</b>",
        "case_no_label": "• <b>Mã trường hợp:</b> {}",
        "name_label": "• <b>Tên:</b> {}",
        "status_label": "• <b>Trạng thái:</b> {}",
        "last_seen_label": "• <b>Lần cuối thấy:</b> {}",
        "reward_label": "• <b>Phần thưởng:</b> {} {}",
        "created_at_label": "• <b>Tạo lúc:</b> {}",

        "invalid_selection_error": "⚠️ <b>Lựa chọn không hợp lệ</b>\n\nVui lòng chọn tùy chọn hợp lệ.",
        "ask_for_local_stats_input": "📍 Vui lòng chia sẻ thành phố và tỉnh của bạn.",
        "invalid_local_stats_format": "⚠️ <b>Định dạng không hợp lệ</b>\n\nVui lòng nhập theo định dạng: <i>Thành phố, Tỉnh</i>",
        "no_local_cases_found": "🕵️ Không tìm thấy trường hợp nào ở {city}, {province}.",
        "local_cases_found_title": "<b>📂 Các trường hợp ở {city}, {province}:</b>",
    },

    "khmer": {
        # ភាសាខ្មែរ - Khmer
        "community_stats_title": "<b>📊 ស្ថិតិសហគមន៍ PeopleTrace</b>",
        "total_cases_submitted": "• <b>ចំនួនករណីបានដាក់ផ្ញើ:</b> {}",
        "regions_covered": "• <b>តំបន់ដែលគ្របដណ្តប់:</b> {} ប្រទេស, {} ទីក្រុង",
        "unsolved_cases": "• <b>🕵️‍♂️ ករណីដែលមិនទាន់ដោះស្រាយ:</b> {} (ចុចខាងក្រោម 👇)",
        "successfully_found": "• <b>✅ បានរកឃើញ:</b> {}",
        "average_reward_offered": "• <b>🎁 រង្វាន់ជាមធ្យម:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ ករណីដោះស្រាយលឿនបំផុត:</b> {} ថ្ងៃ",
        "top_active_region": "• <b>🔥 តំបន់សកម្មបំផុត:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ ក្រុមអាយុទូទៅ:</b> {}",
        "highest_reward": "• <b>💰 រង្វាន់ខ្ពស់បំផុត:</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 ស្ថិតិសហគមន៍ PeopleTrace</b>\n\nស្ថានភាពបច្ចុប្បន្នរបស់សហគមន៍:",
        "admin_total_cases_submitted": "👤 <b>ចំនួនករណីបានដាក់ផ្ញើ:</b> {}",
        "admin_regions_covered": "🗺️ <b>តំបន់ដែលគ្របដណ្តប់:</b> {} ប្រទេស, {} ទីក្រុង",
        "admin_unsolved_cases": "🚨 <b>ករណីដែលមិនទាន់ដោះស្រាយ:</b> {} 🡨 ចុចដើម្បីមើលព័ត៌មានលម្អិត",
        "admin_successfully_found": "✅ <b>បានរកឃើញ:</b> {}",
        "admin_average_reward_offered": "🎯 <b>រង្វាន់ជាមធ្យម:</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>ករណីដោះស្រាយលឿនបំផុត:</b> {} ថ្ងៃ",
        "admin_top_active_region": "🔎 <b>តំបន់សកម្មបំផុត:</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>ក្រុមអាយុទូទៅ:</b> {}",
        "admin_highest_reward": "💸 <b>រង្វាន់ខ្ពស់បំផុត:</b> {} USDT",
        "admin_footer_message": "🧠 លេខទាំងនេះនៅពេលវាលឿន នឹងជួយណែនាំការសម្រេចចិត្តរបស់អ្នក។ ចាប់ពីចំនួនរង្វាន់ រហូតដល់ការផ្តោតអារម្មណ៍លើតំបន់។ ចូលរួមជាផ្នែកមួយនៃឥទ្ធិពលដែលកំពុងកើនឡើងរបស់យើង។",

        "view_unsolved_cases_button": "🕵️ មើលករណីមិនទាន់ដោះស្រាយ",
        "view_local_stats_button": "📍 មើលស្ថិតិក្នុងស្រុក",
        "my_submissions_button": "📂 ការដាក់ផ្ញើរបស់ខ្ញុំ",
        "back_button": "⬅️ ត្រលប់ក្រោយ",
        "admin_view_local_stats_button": "🔍 មើលស្ថិតិក្នុងស្រុក",
        "admin_my_submissions_button": "📂 មើលការដាក់ផ្ញើរបស់ខ្ញុំ",
        "admin_back_to_menu_button": "🔙 ត្រលប់ទៅមុខងារ",

        "local_stats_coming_soon": "📍 ឆាប់ៗនេះ: ស្ថិតិដែលផ្អែកលើទីតាំងរបស់អ្នក។",
        "unsolved_country_list": "ជ្រើសរើសប្រទេសពីបញ្ជីខាងក្រោម:",
        "no_unsolved_country": "📍 គ្មានករណីដែលមិនទាន់ដោះស្រាយនៅក្នុងប្រទេសណាទេ។",

        "no_cases_in_country": "គ្មានករណីនៅក្នុង {} ទេ។",
        "unsolved_cases_in_country": "<b>🕵️ ករណីមិនទាន់ដោះស្រាយនៅ {}:</b>",

        "you_havent_submitted_cases": "📂 អ្នកមិនទាន់បានដាក់ផ្ញើករណីណាមួយទេ។",
        "your_submitted_cases_title": "<b>📂 ករណីដែលអ្នកបានដាក់ផ្ញើ:</b>",

        "case_details_title": "<b>📄 ព័ត៌មានករណី</b>",
        "case_no_label": "• <b>លេខករណី:</b> {}",
        "name_label": "• <b>ឈ្មោះ:</b> {}",
        "status_label": "• <b>ស្ថានភាព:</b> {}",
        "last_seen_label": "• <b>បានឃើញចុងក្រោយ:</b> {}",
        "reward_label": "• <b>រង្វាន់:</b> {} {}",
        "created_at_label": "• <b>បានបង្កើតនៅ:</b> {}",

        "invalid_selection_error": "⚠️ <b>ការជ្រើសរើសមិនត្រឹមត្រូវ</b>\n\nសូមជ្រើសរើសជម្រើសដែលត្រឹមត្រូវ។",
        "ask_for_local_stats_input": "📍 សូមចែករំលែកទីក្រុង និងខេត្តរបស់អ្នក។",
        "invalid_local_stats_format": "⚠️ <b>ទម្រង់មិនត្រឹមត្រូវ</b>\n\nសូមបញ្ចូលជា: <i>ទីក្រុង, ខេត្ត</i>",
        "no_local_cases_found": "🕵️ គ្មានករណីនៅក្នុង {city}, {province} ទេ។",
        "local_cases_found_title": "<b>📂 ករណីនៅក្នុង {city}, {province}:</b>",
    },

    "japanese": {
        # 日本語 - Japanese
        "community_stats_title": "<b>📊 PeopleTrace コミュニティ統計</b>",
        "total_cases_submitted": "• <b>送信された総ケース数：</b> {}",
        "regions_covered": "• <b>カバーされた地域：</b> {} 国、{} 都市",
        "unsolved_cases": "• <b>🕵️‍♂️ 解決していないケース：</b> {}（下記をクリック👇）",
        "successfully_found": "• <b>✅ 成功して発見：</b> {}",
        "average_reward_offered": "• <b>🎁 平均報酬額：</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ 最速で解決したケース：</b> {} 日",
        "top_active_region": "• <b>🔥 最も活発な地域：</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ 一般的な年齢層：</b> {}",
        "highest_reward": "• <b>💰 最高報酬額：</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 PeopleTrace コミュニティ統計</b>\n\n現在のコミュニティ状況：",
        "admin_total_cases_submitted": "👤 <b>送信された総ケース数：</b> {}",
        "admin_regions_covered": "🗺️ <b>カバーされた地域：</b> {} 国、{} 都市",
        "admin_unsolved_cases": "🚨 <b>解決していないケース：</b> {} 🡨 詳細を見るにはクリック",
        "admin_successfully_found": "✅ <b>成功して発見：</b> {}",
        "admin_average_reward_offered": "🎯 <b>平均報酬額：</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>最速で解決したケース：</b> {} 日",
        "admin_top_active_region": "🔎 <b>最も活発な地域：</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>一般的な年齢層：</b> {}",
        "admin_highest_reward": "💸 <b>最高報酬額：</b> {} USDT",
        "admin_footer_message": "🧠 このリアルタイムデータは、報酬金額や注力する地域まであなたの意思決定をサポートします。私たちの成長に寄与してください。",

        "view_unsolved_cases_button": "🕵️ 解決していないケースを表示",
        "view_local_stats_button": "📍 地域統計を表示",
        "my_submissions_button": "📂 私の提出内容",
        "back_button": "⬅️ 戻る",
        "admin_view_local_stats_button": "🔍 地域統計を表示",
        "admin_my_submissions_button": "📂 私の提出内容を表示",
        "admin_back_to_menu_button": "🔙 メニューに戻る",

        "local_stats_coming_soon": "📍 間もなく提供開始：あなたの位置に基づく地域統計。",
        "unsolved_country_list": "以下のリストから国を選択してください：",
        "no_unsolved_country": "📍 未解決のケースのある国はありません。",

        "no_cases_in_country": "{} にはケースが見つかりませんでした。",
        "unsolved_cases_in_country": "<b>🕵️ {} の未解決ケース：</b>",

        "you_havent_submitted_cases": "📂 あなたはまだケースを提出していません。",
        "your_submitted_cases_title": "<b>📂 提出済みのケース：</b>",

        "case_details_title": "<b>📄 ケース詳細</b>",
        "case_no_label": "• <b>ケース番号：</b> {}",
        "name_label": "• <b>名前：</b> {}",
        "status_label": "• <b>ステータス：</b> {}",
        "last_seen_label": "• <b>最終確認日：</b> {}",
        "reward_label": "• <b>報酬：</b> {} {}",
        "created_at_label": "• <b>作成日時：</b> {}",

        "invalid_selection_error": "⚠️ <b>無効な選択です</b>\n\n有効なオプションを選択してください。",
        "ask_for_local_stats_input": "📍 ご自身の都市と県を共有してください。",
        "invalid_local_stats_format": "⚠️ <b>形式が正しくありません</b>\n\n以下のように入力してください：<i>都市, 県</i>",
        "no_local_cases_found": "🕵️ {city}, {province} にケースは見つかりませんでした。",
        "local_cases_found_title": "<b>📂 {city}, {province} のケース：</b>",
    },

    "korean": {
        # 한국어 - Korean
        "community_stats_title": "<b>📊 PeopleTrace 커뮤니티 통계</b>",
        "total_cases_submitted": "• <b>제출된 총 사건 수:</b> {}",
        "regions_covered": "• <b>포함 지역:</b> {} 국가, {} 도시",
        "unsolved_cases": "• <b>🕵️‍♂️ 해결되지 않은 사건:</b> {} (아래 클릭 👇)",
        "successfully_found": "• <b>✅ 성공적으로 발견:</b> {}",
        "average_reward_offered": "• <b>🎁 평균 보상금:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ 가장 빠르게 해결된 사건:</b> {} 일",
        "top_active_region": "• <b>🔥 가장 활발한 지역:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ 일반적인 인구 통계:</b> {}",
        "highest_reward": "• <b>💰 최고 보상금:</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 PeopleTrace 커뮤니티 통계</b>\n\n현재 커뮤니티 상황:",
        "admin_total_cases_submitted": "👤 <b>제출된 총 사건 수:</b> {}",
        "admin_regions_covered": "🗺️ <b>포함 지역:</b> {} 국가, {} 도시",
        "admin_unsolved_cases": "🚨 <b>해결되지 않은 사건:</b> {} 🡨 자세히 보기 클릭",
        "admin_successfully_found": "✅ <b>성공적으로 발견:</b> {}",
        "admin_average_reward_offered": "🎯 <b>평균 보상금:</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>가장 빠르게 해결된 사건:</b> {} 일",
        "admin_top_active_region": "🔎 <b>가장 활발한 지역:</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>일반적인 인구 통계:</b> {}",
        "admin_highest_reward": "💸 <b>최고 보상금:</b> {} USDT",
        "admin_footer_message": "🧠 실시간 숫자들은 보상 금액에서부터 주의 집중 지역까지 당신의 결정을 돕습니다. 저희 성장하는 영향력에 함께하세요.",

        "view_unsolved_cases_button": "🕵️ 해결되지 않은 사건 보기",
        "view_local_stats_button": "📍 지역 통계 보기",
        "my_submissions_button": "📂 제출한 내역",
        "back_button": "⬅️ 돌아가기",
        "admin_view_local_stats_button": "🔍 지역 통계 보기",
        "admin_my_submissions_button": "📂 제출한 내역 보기",
        "admin_back_to_menu_button": "🔙 메뉴로 돌아가기",

        "local_stats_coming_soon": "📍 곧 출시: 위치 기반 지역 통계.",
        "unsolved_country_list": "아래 목록에서 국가를 선택하세요:",
        "no_unsolved_country": "📍 해결되지 않은 사건이 있는 국가가 없습니다.",

        "no_cases_in_country": "{} 에는 사건이 없습니다.",
        "unsolved_cases_in_country": "<b>🕵️ {} 의 미해결 사건:</b>",

        "you_havent_submitted_cases": "📂 아직 사건을 제출하지 않았습니다.",
        "your_submitted_cases_title": "<b>📂 제출한 사건:</b>",

        "case_details_title": "<b>📄 사건 상세 정보</b>",
        "case_no_label": "• <b>사건 번호:</b> {}",
        "name_label": "• <b>이름:</b> {}",
        "status_label": "• <b>상태:</b> {}",
        "last_seen_label": "• <b>마지막 발견 시간:</b> {}",
        "reward_label": "• <b>보상금:</b> {} {}",
        "created_at_label": "• <b>생성 일자:</b> {}",

        "invalid_selection_error": "⚠️ <b>잘못된 선택입니다</b>\n\n올바른 옵션을 선택해주세요.",
        "ask_for_local_stats_input": "📍 도시와 시/도를 입력해주세요.",
        "invalid_local_stats_format": "⚠️ <b>형식이 잘못되었습니다</b>\n\n다음과 같이 입력해주세요: <i>도시, 시/도</i>",
        "no_local_cases_found": "🕵️ {city}, {province} 에는 사건이 없습니다.",
        "local_cases_found_title": "<b>📂 {city}, {province} 의 사건:</b>",
    },

    "urdu": {
        # اردو - Urdu
        "community_stats_title": "<b>📊 پیپل ٹریس کمیونٹی شماریات</b>",
        "total_cases_submitted": "• <b>کُل معاملات جمع کروائے گئے:</b> {}",
        "regions_covered": "• <b>سر چھائے علاقہ جات:</b> {} ممالک، {} شہر",
        "unsolved_cases": "• <b>🕵️‍♂️ حل نہ کئے گئے معاملات:</b> {} (نیچے کلک کریں 👇)",
        "successfully_found": "• <b>✅ کامیابی سے تلاش کئے گئے:</b> {}",
        "average_reward_offered": "• <b>🎁 اوسط انعامی رقم:</b> {} USDT",
        "fastest_case_solved": "• <b>⏱ سب سے تیزی سے حل کیا گیا معاملہ:</b> {} دن",
        "top_active_region": "• <b>🔥 سب سے زیادہ فعال علاقہ:</b> {}",
        "common_demographic": "• <b>🧑‍🤝‍◕ عام آبادی:</b> {}",
        "highest_reward": "• <b>💰 سب سے زیادہ انعامی رقم:</b> {} USDT",

        "admin_daily_stats_title": "<b>📊 پیپل ٹریس کمیونٹی شماریات</b>\n\nکمیونٹی کی موجودہ صورتحال:",
        "admin_total_cases_submitted": "👤 <b>کُل معاملات جمع کروائے گئے:</b> {}",
        "admin_regions_covered": "🗺️ <b>سر چھائے علاقہ جات:</b> {} ممالک، {} شہر",
        "admin_unsolved_cases": "🚨 <b>حل نہ کئے گئے معاملات:</b> {} 🡨 تفصیل دیکھنے کے لئے کلک کریں",
        "admin_successfully_found": "✅ <b>کامیابی سے تلاش کئے گئے:</b> {}",
        "admin_average_reward_offered": "🎯 <b>اوسط انعامی رقم:</b> {} USDT",
        "admin_fastest_case_solved": "⏱️ <b>سب سے تیزی سے حل کیا گیا معاملہ:</b> {} دن",
        "admin_top_active_region": "🔎 <b>سب سے زیادہ فعال علاقہ:</b> {}",
        "admin_common_demographic": "🧍‍♂️ <b>عام آبادی:</b> {}",
        "admin_highest_reward": "💸 <b>سب سے زیادہ انعامی رقم:</b> {} USDT",
        "admin_footer_message": "🧠 یہ حقیقی وقت کے اعداد و شمار آپ کو مناسب انعامی رقم اور علاقائی توجہ کے حوالے سے رہنمائی کریں گے۔ ہمارے بڑھتے ہوئے اثر میں شامل ہوں۔",

        "view_unsolved_cases_button": "🕵️ حل نہ کئے گئے معاملات دیکھیں",
        "view_local_stats_button": "📍 مقامی شماریات دیکھیں",
        "my_submissions_button": "📂 میری جمع کرائی گئی درخواستیں",
        "back_button": "⬅️ واپس",
        "admin_view_local_stats_button": "🔍 مقامی شماریات دیکھیں",
        "admin_my_submissions_button": "📂 میری جمع کرائی گئی درخواستیں دیکھیں",
        "admin_back_to_menu_button": "🔙 مینو میں واپس جائیں",

        "local_stats_coming_soon": "📍 جلد ہی آرہا ہے: آپ کی لوکیشن کے مطابق مقامی شماریات۔",
        "unsolved_country_list": "ذیل میں فہرست سے ملک منتخب کریں:",
        "no_unsolved_country": "📍 کسی بھی ملک میں حل نہ کئے گئے معاملات نہیں ہیں۔",

        "no_cases_in_country": "{} میں کوئی معاملہ نہیں ملا۔",
        "unsolved_cases_in_country": "<b>🕵️ {} میں حل نہ کئے گئے معاملات:</b>",

        "you_havent_submitted_cases": "📂 آپ نے ابھی تک کوئی معاملہ جمع نہیں کرایا ہے۔",
        "your_submitted_cases_title": "<b>📂 جمع کرائے گئے معاملات:</b>",

        "case_details_title": "<b>📄 معاملہ کی تفصیل</b>",
        "case_no_label": "• <b>معاملہ نمبر:</b> {}",
        "name_label": "• <b>نام:</b> {}",
        "status_label": "• <b>حالت:</b> {}",
        "last_seen_label": "• <b>آخری بار دیکھا گیا:</b> {}",
        "reward_label": "• <b>انعام:</b> {} {}",
        "created_at_label": "• <b>بنایا گیا:</b> {}",

        "invalid_selection_error": "⚠️ <b>غلط انتخاب</b>\n\nبراہ کرم درست اختیار منتخب کریں۔",
        "ask_for_local_stats_input": "📍 براہ کرم اپنا شہر اور صوبہ بتائیں۔",
        "invalid_local_stats_format": "⚠️ <b>غلط فارمیٹ</b>\n\nبرائے مہربانی اس طرح درج کریں: <i>شہر، صوبہ</i>",
        "no_local_cases_found": "🕵️ {city}, {province} میں کوئی معاملہ نہیں ملا۔",
        "local_cases_found_title": "<b>📂 {city}, {province} کے معاملات:</b>",
    }
}
