WALLET_MENU_CONSTANT = {
    "en": {
        # Buttons
        "refresh_btn": "🔄 Refresh",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Tron Network)",
        "address_btn": "💼 Show Address",
        "history_btn": "📜 History",

        "no_wallet": "You don't have any wallets yet.",
    },
    "zh": {
        "refresh_btn": "🔄 刷新",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Tron Network)",
        "address_btn": "💼 显示地址",
        "history_btn": "📜 历史记录",
        "create_wallet_btn": "➕ 创建钱包",
        "delete_wallet_btn": "❌ 删除钱包",
        "welcome_text": "欢迎来到钱包菜单!",
        "refresh_wallet_text": "钱包已刷新!",
        "no_wallet": "你还没有钱包。",
    },
    "ms": {
        # Butang
        "refresh_btn": "🔄 Segar Semula",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Tron Network)",
        "address_btn": "💼 Tunjukkan Alamat",
        "history_btn": "📜 Sejarah",
        "create_wallet_btn": "➕ Buat Dompet",
        "delete_wallet_btn": "❌ Padam Dompet",
        "welcome_text": "Selamat datang ke Menu Dompet!",
        "refresh_wallet_text": "Dompet telah dikemas kini!",
        "no_wallet": "Anda belum mempunyai dompet lagi.",
    },
    "id": {
        "refresh_btn": "🔄 Segarkan",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Jaringan Tron)",
        "address_btn": "💼 Tampilkan Alamat",
        "history_btn": "📜 Riwayat",
        "create_wallet_btn": "➕ Buat Dompet",
        "delete_wallet_btn": "❌ Hapus Dompet",
        "welcome_text": "Selamat datang di Menu Dompet!",
        "refresh_wallet_text": "Dompet telah diperbarui!",
        "no_wallet": "Anda belum memiliki dompet.",
    },
    "th": {
        "refresh_btn": "🔄 รีเฟรช",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - เครือข่าย Tron)",
        "address_btn": "💼 แสดงที่อยู่",
        "history_btn": "📜 ประวัติ",
        "create_wallet_btn": "➕ สร้างกระเป๋าเงิน",
        "delete_wallet_btn": "❌ ลบกระเป๋าเงิน",
        "welcome_text": "ยินดีต้อนรับสู่เมนูกระเป๋าเงิน!",
        "refresh_wallet_text": "อัปเดตรายการกระเป๋าเงินแล้ว!",
        "no_wallet": "คุณยังไม่มีกระเป๋าเงินเลย",
    },
    "vi": {
        "refresh_btn": "🔄 Làm mới",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - Mạng Tron)",
        "address_btn": "💼 Hiển thị Địa chỉ",
        "history_btn": "📜 Lịch sử",
        "create_wallet_btn": "➕ Tạo Ví",
        "delete_wallet_btn": "❌ Xóa Ví",
        "welcome_text": "Chào mừng bạn đến với Menu Ví!",
        "refresh_wallet_text": "Ví đã được làm mới!",
        "no_wallet": "Bạn chưa có ví nào cả.",
    },
    "km": {
        "refresh_btn": "🔄 ធ្វើឱ្យស្រស់",
        "sol_btn": "⚡ Solana (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - បណ្តាញ Tron)",
        "address_btn": "💼 បង្ហាញអាសយដ្ឋាន",
        "history_btn": "📜 ប្រវត្តិ",
        "create_wallet_btn": "➕ បង្កើតកាបូប",
        "delete_wallet_btn": "❌ លុបកាបូប",
        "welcome_text": "សូមស្វាគមន៍ចូលទៅកាន់មីនុយកាបូប!",
        "refresh_wallet_text": "កាបូបត្រូវបានធ្វើឱ្យស្រស់រួចរាល់ហើយ!",
        "no_wallet": "អ្នកមិនទាន់មានកាបូបនៅឡើយទេ។",
    },
    "ja": {
        "refresh_btn": "🔄 更新",
        "sol_btn": "⚡ ソラナ（SOL）",
        "usdt_btn": "💵 USDT（TRC20 - トロンネットワーク）",
        "address_btn": "💼 アドレスを表示",
        "history_btn": "📜 履歴",
        "create_wallet_btn": "➕ ウォレットを作成",
        "delete_wallet_btn": "❌ ウォレットを削除",
        "welcome_text": "ウォレットメニューへようこそ！",
        "refresh_wallet_text": "ウォレットが更新されました！",
        "no_wallet": "まだウォレットがありません。",
    },
    "ko": {
        "refresh_btn": "🔄 새로 고침",
        "sol_btn": "⚡ 솔라나(SOL)",
        "usdt_btn": "💵 USDT(TRC20 - 트론 네트워크)",
        "address_btn": "💼 주소 보기",
        "history_btn": "📜 기록",
        "create_wallet_btn": "➕ 지갑 생성",
        "delete_wallet_btn": "❌ 지갑 삭제",
        "welcome_text": "지갑 메뉴에 오신 것을 환영합니다!",
        "refresh_wallet_text": "지갑이 새로 고쳐졌습니다!",
        "no_wallet": "아직 지갑이 없습니다.",
    },
    "ur": {
        "refresh_btn": "🔄 تازہ کریں",
        "sol_btn": "⚡ سولانا (SOL)",
        "usdt_btn": "💵 USDT (TRC20 - ٹرون نیٹ ورک)",
        "address_btn": "💼 پتہ دکھائیں",
        "history_btn": "📜 تاریخچہ",
        "create_wallet_btn": "➕ والٹ بنائیں",
        "delete_wallet_btn": "❌ والٹ حذف کریں",
        "welcome_text": "والٹ مینو میں خوش آمدید!",
        "refresh_wallet_text": "والٹ تازہ کر دیے گئے!",
        "no_wallet": "آپ کے پاس ابھی تک کوئی والٹ نہیں ہے۔",
    }
}