WALLET_LANG_DATA = {
    "en": {
        "choose_wallet": "Please choose the type of wallet:",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - Tron Network)",
        "choose_existing_or_new_wallet": "Choose Existing Wallet or Create New One",
        "wallet_name_prompt": "You've chosen a {wallet_type} wallet.\nPlease enter a name for your wallet:",
        "wallet_name_empty": "❌ Wallet name cannot be empty. Please try again.",
        "wallet_create_ok": "✅ Wallet Created Successfully!\n\n",
        "wallet_create_err": "❌ Error creating wallet. Please try again later.",
        "cancel_msg": "Operation cancelled. Use /start to begin again.",
        "account_wallet_type": "Account Wallet Type (SOL | USDT)",
        "menu_wallet_title": "💳 Wallet Menu",
        "btn_refresh": "🔄 Refresh",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - Tron Network)",
        "btn_show_address": "🏠 Show Address",
        "btn_create_wallet": "➕ Create Wallet",
        "btn_delete_wallet": "🗑️ Delete Wallet",
        "wallet_no_exists": "❌ No wallet found. Please create one using the 'Create Wallet' button.",
        "wallet_exists": "📌 <b>Existing Wallet:</b>\nName: {name}\nPublic Key: `{pub}`\nBalance: {bal} SOL",
        "wallet_deleted": "✅ Wallet deleted successfully.",
        "wallet_not_deleted": "❌ No wallet to delete.",
        "wallet_refreshed": "🔄 Balance updated:\nName: {name}\nPublic Key: `{pub}`\nBalance: {bal} SOL",
        "guide_create_wallet": "📝 <b>How to Create a Wallet:</b>\n1️⃣ Choose the wallet type (SOL or USDT).\n2️⃣ Enter a unique name for your wallet.\n3️⃣ Your wallet will be created with a public key and secret key.\n4️⃣ Use the public key to receive funds.\n\n💡 Tip: Keep your secret key safe and never share it with anyone.",
        "guide_delete_wallet": "⚠️ <b>Important Information:</b>\nDeleting a wallet is irreversible. All funds in the wallet will be lost.\nMake sure you have transferred all funds before proceeding.",
        "no_wallets": "You don't have any wallets yet.",
        "select_wallet": "Select a wallet to view its transaction history:",
        "wallet_details": "**Wallet Name:** {name} \n\n **Public Address:** `{public_key}`",
        "wallet_not_found": "Wallet not found.",
        "back_button": "Back",
        "sol_wallets_header": "<b>Your SOL Wallets:</b>\n",
        "wallet_balance": "<b>Name:</b> {name}, <b>Balance:</b> {balance} SOL\n",
        "wallet_error": "<b>Name:</b> {name}, <b>Error:</b> {error}\n",
        "no_sol_wallets": "You don't have any SOL wallets yet.",
        "no_usdt_wallets": "You don't have any USDT wallets yet.",
        "back_button": "⬅️ Back",
        "refresh_btn": "🔄 Refresh",
        "wallet_not_found": "Wallet not found.",
        "show_balance": "\n\n🔷 {name}\n\n💰 Balance: {balance}\n🔑 Public Key: {public_key}\n\nSelect an action:",
        "show_private_key": "🔐 Show Private Key",
        "back_to_wallet": "⬅️ Back to Wallets",
        "your_usdt_wallet": "📋 Your USDT Wallets:",
        "show_it_btn": "✅ Yes, show it",
        "private_key_warning": "🚨 PRIVATE KEY WARNING 🚨\n\nThis key gives FULL ACCESS to your wallet and funds.\n\n🔐 Private Key:\n{wallet}\n\n❗ Never share this key with anyone\n❗ Never enter it on unverified websites\n❗ Store it securely offline if you must keep it",
        "dont_have_any_wallet": "<b>You don't have any wallets yet.</b>",
        "select_wallet_header": "<b>Select a wallet to view its address:</b>",
        "wallet_not_found": "Wallet not found.",
        "select_wallet_type_header": "Please select the wallet type:",
        "enter_wallet_name": "Please enter the wallet name:",
        "wallet_address_already_in_use": "❌ A wallet with this name already exists. Please choose a different name.",
        "dont_have_wallet_to_delete": "<b>You don't have any wallets to delete.</b>",
        "yes_delete": "Yes, delete",
        "wallet_deleted": "Wallet deleted successfully.",
        "failed_to_delete_wallet": "Failed to delete wallet.",
        "delete_wallet_header": "Select a wallet to delete:",
        "delete_wallet_confirm_reject": "You didn't confirm to delete the wallet",
    },
    "zh": {
        "choose_wallet": "请选择钱包类型：",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - 波场网络)",
        "choose_existing_or_new_wallet": "选择已有钱包或创建新钱包",
        "wallet_name_prompt": "您已选择 {wallet_type} 钱包。\n请输入钱包名称：",
        "wallet_name_empty": "❌ 钱包名称不能为空。请重试。",
        "wallet_create_ok": "✅ 钱包创建成功！\n\n",
        "wallet_create_err": "❌ 创建钱包时出错。请稍后再试。",
        "cancel_msg": "操作已取消。使用 /start 重新开始。",
        "account_wallet_type": "账户钱包类型 (SOL | USDT)",
        "menu_wallet_title": "💳 钱包菜单",
        "btn_refresh": "🔄 刷新",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - 波场网络)",
        "btn_show_address": "🏠 显示地址",
        "btn_create_wallet": "➕ 创建钱包",
        "btn_delete_wallet": "🗑️ 删除钱包",
        "wallet_no_exists": "❌ 未找到钱包，请使用“创建钱包”按钮创建一个。",
        "wallet_exists": "📌 <b>现有钱包：</b>\n名称: {name}\n公钥: `{pub}`\n余额: {bal} SOL",
        "wallet_deleted": "✅ 钱包已成功删除。",
        "wallet_not_deleted": "❌ 没有可删除的钱包。",
        "wallet_refreshed": "🔄 余额已更新：\n名称: {name}\n公钥: `{pub}`\n余额: {bal} SOL",
        "guide_create_wallet": "📝 <b>如何创建钱包：</b>\n1️⃣ 选择钱包类型（SOL 或 USDT）。\n2️⃣ 输入一个独特的钱包名称。\n3️⃣ 钱包将生成公钥和私钥。\n4️⃣ 使用公钥接收资金。\n\n💡 提示：保管好您的私钥，切勿与他人分享。",
        "guide_delete_wallet": "⚠️ <b>重要提示：</b>\n删除钱包是不可逆的，钱包内的所有资金将丢失。\n请确保在操作前已转移所有资金。",
        "no_wallets": "您还没有任何钱包。",
        "select_wallet": "选择一个钱包以查看其交易记录：",
        "wallet_details": "**钱包名称：** {name} \n\n **公钥地址：** `{public_key}`",
        "wallet_not_found": "未找到钱包。",
        "back_button": "返回",
        "sol_wallets_header": "<b>您的 SOL 钱包：</b>\n",
        "wallet_balance": "<b>名称：</b> {name}, <b>余额：</b> {balance} SOL\n",
        "wallet_error": "<b>名称：</b> {name}, <b>错误：</b> {error}\n",
        "no_sol_wallets": "您还没有任何 SOL 钱包。",
        "no_usdt_wallets": "您还没有任何 USDT 钱包。",
        "back_button": "⬅️ 返回",
        "refresh_btn": "🔄 刷新",
        "wallet_not_found": "未找到钱包。",
        "show_balance": "\n\n🔷 {name}\n\n💰 余额：{balance}\n🔑 公钥：{public_key}\n\n选择一个操作：",
        "show_private_key": "🔐 显示私钥",
        "back_to_wallet": "⬅️ 返回钱包列表",
        "your_usdt_wallet": "📋 您的 USDT 钱包：",
        "show_it_btn": "✅ 是的，显示它",
        "private_key_warning": "🚨 私钥警告 🚨\n\n该密钥对您的钱包和资金具有完全访问权限。\n\n🔐 私钥：\n{wallet}\n\n❗ 切勿与任何人分享该密钥\n❗ 切勿在未经验证的网站输入该密钥\n❗ 如果必须保存，请离线安全存储",
        "dont_have_any_wallet": "<b>您还没有任何钱包。</b>",
        "select_wallet_header": "<b>选择一个钱包以查看其地址：</b>",
        "wallet_not_found": "未找到钱包。",
        "select_wallet_type_header": "请选择钱包类型：",
        "enter_wallet_name": "请输入钱包名称：",
        "wallet_address_already_in_use": "❌ 已存在同名钱包，请选择其他名称。",
        "dont_have_wallet_to_delete": "<b>没有可删除的钱包。</b>",
        "yes_delete": "是的，删除",
        "wallet_deleted": "钱包已成功删除。",
        "failed_to_delete_wallet": "删除钱包失败。",
        "delete_wallet_header": "请选择要删除的钱包：",
        "delete_wallet_confirm_reject": "您未确认删除钱包",
    },
    "ms": {
        "choose_wallet": "Sila pilih jenis dompet:",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - Rangkaian Tron)",
        "choose_existing_or_new_wallet": "Pilih Dompet Sedia Ada atau Cipta Dompet Baru",
        "wallet_name_prompt": "Anda telah memilih dompet jenis {wallet_type}.\nSila masukkan nama untuk dompet anda:",
        "wallet_name_empty": "❌ Nama dompet tidak boleh kosong. Sila cuba lagi.",
        "wallet_create_ok": "✅ Dompet Berjaya Dicipta!\n\n",
        "wallet_create_err": "❌ Ralat semasa mencipta dompet. Sila cuba lagi nanti.",
        "cancel_msg": "Operasi dibatalkan. Gunakan /start untuk mula semula.",
        "account_wallet_type": "Jenis Dompet Akaun (SOL | USDT)",
        "menu_wallet_title": "💳 Menu Dompet",
        "btn_refresh": "🔄 Segarkan",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - Rangkaian Tron)",
        "btn_show_address": "🏠 Papar Alamat",
        "btn_create_wallet": "➕ Cipta Dompet",
        "btn_delete_wallet": "🗑️ Padam Dompet",
        "wallet_no_exists": "❌ Tiada dompet dijumpai. Sila cipta satu menggunakan butang 'Cipta Dompet'.",
        "wallet_exists": "📌 <b>Dompet Sedia Ada:</b>\nNama: {name}\nKunci Awam: `{pub}`\nBaki: {bal} SOL",
        "wallet_deleted": "✅ Dompet berjaya dipadam.",
        "wallet_not_deleted": "❌ Tiada dompet untuk dipadam.",
        "wallet_refreshed": "🔄 Baki dikemas kini:\nNama: {name}\nKunci Awam: `{pub}`\nBaki: {bal} SOL",
        "guide_create_wallet": "📝 <b>Cara Mencipta Dompet:</b>\n1️⃣ Pilih jenis dompet (SOL atau USDT).\n2️⃣ Masukkan nama unik untuk dompet anda.\n3️⃣ Dompet akan dijana dengan kunci awam dan kunci sulit.\n4️⃣ Gunakan kunci awam untuk menerima dana.\n\n💡 Tips: Simpan kunci sulit anda dengan selamat dan jangan kongsikan dengan sesiapa.",
        "guide_delete_wallet": "⚠️ <b>Maklumat Penting:</b>\nMemadamkan dompet adalah tindakan tidak boleh dipulihkan. Semua dana dalam dompet akan hilang.\nPastikan semua dana telah dipindahkan sebelum meneruskan.",
        "no_wallets": "Anda belum mempunyai sebarang dompet.",
        "select_wallet": "Pilih dompet untuk melihat sejarah transaksinya:",
        "wallet_details": "**Nama Dompet:** {name} \n\n **Alamat Awam:** `{public_key}`",
        "wallet_not_found": "Dompet tidak dijumpai.",
        "back_button": "Kembali",
        "sol_wallets_header": "<b>Dompet SOL Anda:</b>\n",
        "wallet_balance": "<b>Nama:</b> {name}, <b>Baki:</b> {balance} SOL\n",
        "wallet_error": "<b>Nama:</b> {name}, <b>Ralat:</b> {error}\n",
        "no_sol_wallets": "Anda belum mempunyai sebarang dompet SOL.",
        "no_usdt_wallets": "Anda belum mempunyai sebarang dompet USDT.",
        "back_button": "⬅️ Kembali",
        "refresh_btn": "🔄 Segarkan",
        "wallet_not_found": "Dompet tidak dijumpai.",
        "show_balance": "\n\n🔷 {name}\n\n💰 Baki: {balance}\n🔑 Kunci Awam: {public_key}\n\nPilih tindakan:",
        "show_private_key": "🔐 Papar Kunci Sulit",
        "back_to_wallet": "⬅️ Kembali ke Dompet",
        "your_usdt_wallet": "📋 Dompet USDT Anda:",
        "show_it_btn": "✅ Ya, paparkan",
        "private_key_warning": "🚨 AMARAN KUNCI SULIT 🚨\n\nKunci ini memberi akses PENUH kepada dompet dan dana anda.\n\n🔐 Kunci Sulit:\n{wallet}\n\n❗ Jangan kongsikan kunci ini dengan sesiapa\n❗ Jangan masukkan di laman web yang tidak sah\n❗ Simpan secara selamat secara luar talian jika perlu",
        "dont_have_any_wallet": "<b>Anda belum mempunyai sebarang dompet.</b>",
        "select_wallet_header": "<b>Pilih dompet untuk melihat alamatnya:</b>",
        "wallet_not_found": "Dompet tidak dijumpai.",
        "select_wallet_type_header": "Sila pilih jenis dompet:",
        "enter_wallet_name": "Sila masukkan nama dompet:",
        "wallet_address_already_in_use": "❌ Dompet dengan nama ini sudah wujud. Sila pilih nama lain.",
        "dont_have_wallet_to_delete": "<b>Anda tidak mempunyai dompet untuk dipadam.</b>",
        "yes_delete": "Ya, padam",
        "wallet_deleted": "Dompet berjaya dipadam.",
        "failed_to_delete_wallet": "Gagal memadam dompet.",
        "delete_wallet_header": "Pilih dompet untuk dipadam:",
        "delete_wallet_confirm_reject": "Anda tidak mengesahkan pemadaman dompet",
    },
    "id": {
        "choose_wallet": "Silakan pilih jenis dompet:",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - Jaringan Tron)",
        "choose_existing_or_new_wallet": "Pilih Dompet yang Sudah Ada atau Buat Baru",
        "wallet_name_prompt": "Anda telah memilih dompet {wallet_type}.\nSilakan masukkan nama untuk dompet Anda:",
        "wallet_name_empty": "❌ Nama dompet tidak boleh kosong. Silakan coba lagi.",
        "wallet_create_ok": "✅ Dompet Berhasil Dibuat!\n\n",
        "wallet_create_err": "❌ Kesalahan saat membuat dompet. Silakan coba lagi nanti.",
        "cancel_msg": "Operasi dibatalkan. Gunakan /start untuk memulai lagi.",
        "account_wallet_type": "Jenis Dompet Akun (SOL | USDT)",
        "menu_wallet_title": "💳 Menu Dompet",
        "btn_refresh": "🔄 Segarkan",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - Jaringan Tron)",
        "btn_show_address": "🏠 Tampilkan Alamat",
        "btn_create_wallet": "➕ Buat Dompet",
        "btn_delete_wallet": "🗑️ Hapus Dompet",
        "wallet_no_exists": "❌ Tidak ada dompet ditemukan. Silakan buat dengan tombol 'Buat Dompet'.",
        "wallet_exists": "📌 <b>Dompet yang Ada:</b>\nNama: {name}\nKunci Publik: `{pub}`\nSaldo: {bal} SOL",
        "wallet_deleted": "✅ Dompet berhasil dihapus.",
        "wallet_not_deleted": "❌ Tidak ada dompet untuk dihapus.",
        "wallet_refreshed": "🔄 Saldo diperbarui:\nNama: {name}\nKunci Publik: `{pub}`\nSaldo: {bal} SOL",
        "guide_create_wallet": "📝 <b>Cara Membuat Dompet:</b>\n1️⃣ Pilih jenis dompet (SOL atau USDT).\n2️⃣ Masukkan nama unik untuk dompet Anda.\n3️⃣ Dompet akan dibuat dengan kunci publik dan kunci rahasia.\n4️⃣ Gunakan kunci publik untuk menerima dana.\n\n💡 Tips: Simpan kunci rahasia Anda dengan aman dan jangan berikan kepada siapa pun.",
        "guide_delete_wallet": "⚠️ <b>Informasi Penting:</b>\nMenghapus dompet tidak dapat dibatalkan. Semua dana dalam dompet akan hilang.\nPastikan semua dana telah dipindahkan sebelum melanjutkan.",
        "no_wallets": "Anda belum memiliki dompet.",
        "select_wallet": "Pilih dompet untuk melihat riwayat transaksinya:",
        "wallet_details": "**Nama Dompet:** {name} \n\n **Alamat Publik:** `{public_key}`",
        "wallet_not_found": "Dompet tidak ditemukan.",
        "back_button": "Kembali",
        "sol_wallets_header": "<b>Dompet SOL Anda:</b>\n",
        "wallet_balance": "<b>Nama:</b> {name}, <b>Saldo:</b> {balance} SOL\n",
        "wallet_error": "<b>Nama:</b> {name}, <b>Kesalahan:</b> {error}\n",
        "no_sol_wallets": "Anda belum memiliki dompet SOL.",
        "no_usdt_wallets": "Anda belum memiliki dompet USDT.",
        "back_button": "⬅️ Kembali",
        "refresh_btn": "🔄 Segarkan",
        "wallet_not_found": "Dompet tidak ditemukan.",
        "show_balance": "\n\n🔷 {name}\n\n💰 Saldo: {balance}\n🔑 Kunci Publik: {public_key}\n\nPilih tindakan:",
        "show_private_key": "🔐 Tampilkan Kunci Rahasia",
        "back_to_wallet": "⬅️ Kembali ke Dompet",
        "your_usdt_wallet": "📋 Dompet USDT Anda:",
        "show_it_btn": "✅ Ya, tampilkan",
        "private_key_warning": "🚨 PERINGATAN KUNCI RAHASIA 🚨\n\nKunci ini memberikan akses LENGKAP ke dompet dan dana Anda.\n\n🔐 Kunci Rahasia:\n{wallet}\n\n❗ Jangan bagikan kunci ini dengan siapa pun\n❗ Jangan masukkan di situs web yang tidak terverifikasi\n❗ Simpan secara aman secara offline jika harus menyimpannya",
        "dont_have_any_wallet": "<b>Anda belum memiliki dompet.</b>",
        "select_wallet_header": "<b>Pilih dompet untuk melihat alamatnya:</b>",
        "wallet_not_found": "Dompet tidak ditemukan.",
        "select_wallet_type_header": "Silakan pilih jenis dompet:",
        "enter_wallet_name": "Silakan masukkan nama dompet:",
        "wallet_address_already_in_use": "❌ Dompet dengan nama ini sudah ada. Silakan pilih nama lain.",
        "dont_have_wallet_to_delete": "<b>Anda tidak memiliki dompet untuk dihapus.</b>",
        "yes_delete": "Ya, hapus",
        "wallet_deleted": "Dompet berhasil dihapus.",
        "failed_to_delete_wallet": "Gagal menghapus dompet.",
        "delete_wallet_header": "Pilih dompet untuk dihapus:",
        "delete_wallet_confirm_reject": "Anda tidak mengonfirmasi penghapusan dompet",
    },
    "th": {
        "choose_wallet": "กรุณาเลือกประเภทกระเป๋าเงิน:",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - เครือข่าย Tron)",
        "choose_existing_or_new_wallet": "เลือกกระเป๋าเงินที่มีอยู่หรือสร้างใหม่",
        "wallet_name_prompt": "คุณได้เลือกกระเป๋าเงินแบบ {wallet_type}\nกรุณากรอกชื่อกระเป๋าเงินของคุณ:",
        "wallet_name_empty": "❌ ชื่อกระเป๋าเงินห้ามว่าง กรุณาลองใหม่.",
        "wallet_create_ok": "✅ สร้างกระเป๋าเงินสำเร็จ!\n\n",
        "wallet_create_err": "❌ เกิดข้อผิดพลาดในการสร้างกระเป๋าเงิน กรุณาลองใหม่ในภายหลัง.",
        "cancel_msg": "ยกเลิกการดำเนินการ ใช้ /start เพื่อเริ่มใหม่",
        "account_wallet_type": "ประเภทกระเป๋าเงินบัญชี (SOL | USDT)",
        "menu_wallet_title": "💳 เมนูกระเป๋าเงิน",
        "btn_refresh": "🔄 รีเฟรช",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - เครือข่าย Tron)",
        "btn_show_address": "🏠 แสดงที่อยู่",
        "btn_create_wallet": "➕ สร้างกระเป๋าเงิน",
        "btn_delete_wallet": "🗑️ ลบกระเป๋าเงิน",
        "wallet_no_exists": "❌ ไม่พบกระเป๋าเงิน กรุณาสร้างกระเป๋าเงินด้วยปุ่ม 'สร้างกระเป๋าเงิน'",
        "wallet_exists": "📌 <b>กระเป๋าเงินที่มีอยู่:</b>\nชื่อ: {name}\nคีย์สาธารณะ: `{pub}`\nยอดคงเหลือ: {bal} SOL",
        "wallet_deleted": "✅ ลบกระเป๋าเงินสำเร็จ",
        "wallet_not_deleted": "❌ ไม่มีกระเป๋าเงินให้ลบ",
        "wallet_refreshed": "🔄 อัปเดทยอดคงเหลือ:\nชื่อ: {name}\nคีย์สาธารณะ: `{pub}`\nยอดคงเหลือ: {bal} SOL",
        "guide_create_wallet": "📝 <b>วิธีสร้างกระเป๋าเงิน:</b>\n1️⃣ เลือกประเภทกระเป๋าเงิน (SOL หรือ USDT)\n2️⃣ ใส่ชื่อกระเป๋าเงินที่ไม่ซ้ำใคร\n3️⃣ กระเป๋าเงินจะถูกสร้างขึ้นพร้อมคีย์สาธารณะและคีย์ลับ\n4️⃣ ใช้คีย์สาธารณะเพื่อรับเงิน\n\n💡 เคล็ดลับ: ปกป้องคีย์ลับของคุณ และห้ามเปิดเผยให้ใครรู้เด็ดขาด",
        "guide_delete_wallet": "⚠️ <b>ข้อมูลสำคัญ:</b>\nการลบกระเป๋าเงินไม่สามารถย้อนกลับได้ เงินทั้งหมดในกระเป๋าเงินจะหายไป\nกรุณาย้ายเงินออกให้หมดก่อนดำเนินการ",
        "no_wallets": "คุณยังไม่มีกระเป๋าเงิน",
        "select_wallet": "เลือกกระเป๋าเงินเพื่อดูประวัติการทำธุรกรรม:",
        "wallet_details": "**ชื่อกระเป๋าเงิน:** {name} \n\n **ที่อยู่สาธารณะ:** `{public_key}`",
        "wallet_not_found": "ไม่พบกระเป๋าเงิน",
        "back_button": "ย้อนกลับ",
        "sol_wallets_header": "<b>กระเป๋าเงิน SOL ของคุณ:</b>\n",
        "wallet_balance": "<b>ชื่อ:</b> {name}, <b>ยอดคงเหลือ:</b> {balance} SOL\n",
        "wallet_error": "<b>ชื่อ:</b> {name}, <b>ข้อผิดพลาด:</b> {error}\n",
        "no_sol_wallets": "คุณยังไม่มีกระเป๋าเงิน SOL",
        "no_usdt_wallets": "คุณยังไม่มีกระเป๋าเงิน USDT",
        "back_button": "⬅️ ย้อนกลับ",
        "refresh_btn": "🔄 รีเฟรช",
        "wallet_not_found": "ไม่พบกระเป๋าเงิน",
        "show_balance": "\n\n🔷 {name}\n\n💰 ยอดคงเหลือ: {balance}\n🔑 คีย์สาธารณะ: {public_key}\n\nเลือกการกระทำ:",
        "show_private_key": "🔐 แสดงคีย์ลับ",
        "back_to_wallet": "⬅️ กลับสู่กระเป๋าเงิน",
        "your_usdt_wallet": "📋 กระเป๋าเงิน USDT ของคุณ:",
        "show_it_btn": "✅ ใช่, แสดงเลย",
        "private_key_warning": "🚨 คำเตือนคีย์ลับ 🚨\n\nคีย์นี้ให้สิทธิ์เข้าถึงกระเป๋าเงินและเงินของคุณทั้งหมด\n\n🔐 คีย์ลับ:\n{wallet}\n\n❗ ห้ามเปิดเผยคีย์นี้กับใคร\n❗ ห้ามกรอกบนเว็บไซต์ที่ไม่น่าเชื่อถือ\n❗ จัดเก็บไว้ในที่ปลอดภัยแบบออฟไลน์หากจำเป็น",
        "dont_have_any_wallet": "<b>คุณยังไม่มีกระเป๋าเงินเลย</b>",
        "select_wallet_header": "<b>เลือกกระเป๋าเงินเพื่อดูที่อยู่ของมัน:</b>",
        "wallet_not_found": "ไม่พบกระเป๋าเงิน",
        "select_wallet_type_header": "กรุณาเลือกประเภทกระเป๋าเงิน:",
        "enter_wallet_name": "กรุณากรอกชื่อกระเป๋าเงิน:",
        "wallet_address_already_in_use": "❌ มีกระเป๋าเงินชื่อนี้อยู่แล้ว กรุณาเลือกชื่ออื่น",
        "dont_have_wallet_to_delete": "<b>คุณไม่มีกระเป๋าเงินให้ลบ</b>",
        "yes_delete": "ใช่, ลบเลย",
        "wallet_deleted": "ลบกระเป๋าเงินสำเร็จ",
        "failed_to_delete_wallet": "ลบกระเป๋าเงินไม่สำเร็จ",
        "delete_wallet_header": "เลือกกระเป๋าเงินที่ต้องการลบ:",
        "delete_wallet_confirm_reject": "คุณไม่ได้ยืนยันการลบกระเป๋าเงิน",
    },
    "vi": {
        "choose_wallet": "Vui lòng chọn loại ví:",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - Mạng Tron)",
        "choose_existing_or_new_wallet": "Chọn Ví Có Sẵn hoặc Tạo Ví Mới",
        "wallet_name_prompt": "Bạn đã chọn ví {wallet_type}.\nVui lòng nhập tên cho ví của bạn:",
        "wallet_name_empty": "❌ Tên ví không được để trống. Vui lòng thử lại.",
        "wallet_create_ok": "✅ Tạo ví thành công!\n\n",
        "wallet_create_err": "❌ Lỗi khi tạo ví. Vui lòng thử lại sau.",
        "cancel_msg": "Hủy thao tác. Sử dụng /start để bắt đầu lại.",
        "account_wallet_type": "Loại Ví Tài Khoản (SOL | USDT)",
        "menu_wallet_title": "💳 Menu Ví",
        "btn_refresh": "🔄 Làm mới",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - Mạng Tron)",
        "btn_show_address": "🏠 Hiển thị địa chỉ",
        "btn_create_wallet": "➕ Tạo ví mới",
        "btn_delete_wallet": "🗑️ Xóa ví",
        "wallet_no_exists": "❌ Không tìm thấy ví. Vui lòng tạo mới bằng nút 'Tạo ví'.",
        "wallet_exists": "📌 <b>Ví hiện có:</b>\nTên: {name}\nKhóa công khai: `{pub}`\nSố dư: {bal} SOL",
        "wallet_deleted": "✅ Xóa ví thành công.",
        "wallet_not_deleted": "❌ Không có ví để xóa.",
        "wallet_refreshed": "🔄 Cập nhật số dư:\nTên: {name}\nKhóa công khai: `{pub}`\nSố dư: {bal} SOL",
        "guide_create_wallet": "📝 <b>Hướng dẫn tạo ví:</b>\n1️⃣ Chọn loại ví (SOL hoặc USDT).\n2️⃣ Nhập tên duy nhất cho ví của bạn.\n3️⃣ Ví sẽ được tạo với khóa công khai và khóa riêng.\n4️⃣ Sử dụng khóa công khai để nhận tiền.\n\n💡 Lưu ý: Giữ an toàn khóa riêng và không chia sẻ với bất kỳ ai.",
        "guide_delete_wallet": "⚠️ <b>Thông tin quan trọng:</b>\nViệc xóa ví là không thể hoàn tác. Toàn bộ tiền trong ví sẽ bị mất.\nHãy đảm bảo bạn đã rút hết tiền trước khi thực hiện.",
        "no_wallets": "Bạn chưa có ví nào.",
        "select_wallet": "Chọn ví để xem lịch sử giao dịch:",
        "wallet_details": "**Tên ví:** {name} \n\n **Địa chỉ công khai:** `{public_key}`",
        "wallet_not_found": "Không tìm thấy ví.",
        "back_button": "Quay lại",
        "sol_wallets_header": "<b>Ví SOL của bạn:</b>\n",
        "wallet_balance": "<b>Tên:</b> {name}, <b>Số dư:</b> {balance} SOL\n",
        "wallet_error": "<b>Tên:</b> {name}, <b>Lỗi:</b> {error}\n",
        "no_sol_wallets": "Bạn chưa có ví SOL nào.",
        "no_usdt_wallets": "Bạn chưa có ví USDT nào.",
        "back_button": "⬅️ Quay lại",
        "refresh_btn": "🔄 Làm mới",
        "wallet_not_found": "Không tìm thấy ví.",
        "show_balance": "\n\n🔷 {name}\n\n💰 Số dư: {balance}\n🔑 Khóa công khai: {public_key}\n\nChọn hành động:",
        "show_private_key": "🔐 Hiển thị khóa riêng",
        "back_to_wallet": "⬅️ Quay lại danh sách ví",
        "your_usdt_wallet": "📋 Ví USDT của bạn:",
        "show_it_btn": "✅ Có, hiển thị",
        "private_key_warning": "🚨 CẢNH BÁO KHÓA RIÊNG 🚨\n\nKhóa này cấp QUYỀN TRUY CẬP TOÀN BỘ ví và tiền của bạn.\n\n🔐 Khóa riêng:\n{wallet}\n\n❗ Không chia sẻ khóa này với bất kỳ ai\n❗ Không nhập nó trên các trang web chưa xác thực\n❗ Lưu trữ ngoại tuyến an toàn nếu bạn phải giữ nó",
        "dont_have_any_wallet": "<b>Bạn chưa có ví nào.</b>",
        "select_wallet_header": "<b>Chọn ví để xem địa chỉ của nó:</b>",
        "wallet_not_found": "Không tìm thấy ví.",
        "select_wallet_type_header": "Vui lòng chọn loại ví:",
        "enter_wallet_name": "Vui lòng nhập tên ví:",
        "wallet_address_already_in_use": "❌ Tên ví này đã tồn tại. Vui lòng chọn tên khác.",
        "dont_have_wallet_to_delete": "<b>Bạn không có ví nào để xóa.</b>",
        "yes_delete": "Có, xóa",
        "wallet_deleted": "Xóa ví thành công.",
        "failed_to_delete_wallet": "Xóa ví thất bại.",
        "delete_wallet_header": "Chọn ví cần xóa:",
        "delete_wallet_confirm_reject": "Bạn chưa xác nhận xóa ví",
    },
    "km": {
        "choose_wallet": "សូមជ្រើសរើសប្រភេទកាបូបអេឡិចត្រូនិច:",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - បណ្តាញ Tron)",
        "choose_existing_or_new_wallet": "ជ្រើសរើសកាបូបដែលមានស្រាប់ ឬ បង្កើតថ្មី",
        "wallet_name_prompt": "អ្នកបានជ្រើសរើសកាបូបប្រភេទ {wallet_type}\nសូមបញ្ចូលឈ្មោះកាបូបរបស់អ្នក:",
        "wallet_name_empty": "❌ ឈ្មោះកាបូបមិនអាចទទេបានទេ។ សូមព្យាយាមម្តងទៀត។",
        "wallet_create_ok": "✅ បង្កើតកាបូបបានជោគជ័យ!\n\n",
        "wallet_create_err": "❌ មានបញ្ហាក្នុងការបង្កើតកាបូប។ សូមព្យាយាមម្តងទៀត។",
        "cancel_msg": "បញ្ជាក់ត្រូវបានបោះបង់។ ប្រើ /start ដើម្បីចាប់ផ្តើមឡើងវិញ។",
        "account_wallet_type": "ប្រភេទកាបូបគណនី (SOL | USDT)",
        "menu_wallet_title": "💳 ម៉ឺនុយកាបូប",
        "btn_refresh": "🔄 ធ្វើអាប់ដេត",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - បណ្តាញ Tron)",
        "btn_show_address": "🏠 បង្ហាញអាសយដ្ឋាន",
        "btn_create_wallet": "➕ បង្កើតកាបូប",
        "btn_delete_wallet": "🗑️ លុបកាបូប",
        "wallet_no_exists": "❌ មិនឃើញកាបូបណាមួយទេ។ សូមបង្កើតកាបូបថ្មីដោយប្រើប៊ូតុង 'បង្កើតកាបូប'។",
        "wallet_exists": "📌 <b>កាបូបដែលមាន:</b>\nឈ្មោះ: {name}\nសោសាធារណៈ: `{pub}`\nសមតុល្យ: {bal} SOL",
        "wallet_deleted": "✅ កាបូបត្រូវបានលុបដោយជោគជ័យ។",
        "wallet_not_deleted": "❌ គ្មានកាបូបណាដើម្បីលុបទេ។",
        "wallet_refreshed": "🔄 សមតុល្យត្រូវបានធ្វើអាប់ដេត:\nឈ្មោះ: {name}\nសោសាធារណៈ: `{pub}`\nសមតុល្យ: {bal} SOL",
        "guide_create_wallet": "📝 <b>របៀបបង្កើតកាបូប:</b>\n1️⃣ ជ្រើសរើសប្រភេទកាបូប (SOL ឬ USDT)។\n2️⃣ បញ្ចូលឈ្មោះកាបូបដែលមានតែមួយគត់។\n3️⃣ កាបូបនឹងត្រូវបានបង្កើតជាមួយនឹងសោសាធារណៈ និងសោសំងាត់។\n4️⃣ ប្រើសោសាធារណៈដើម្បីទទួលប្រាក់។\n\n💡 គន្លឹះ: ថែរក្សាសោសំងាត់របស់អ្នកឱ្យមានសុវត្ថិភាព ហើយកុំចែករំលែកវាជាមួយនរណាម្នាក់ឡើយ។",
        "guide_delete_wallet": "⚠️ <b>ព័ត៌មានសំខាន់ៗ:</b>\nការលុបកាបូបគឺមិនអាចត្រឡប់ក្រោយវិញបានទេ។ ប្រាក់ទាំងអស់នៅក្នុងកាបូបនឹងបាត់បង់។\nសូមប្រាកដថាអ្នកបានផ្ទេរប្រាក់ទាំងអស់ចេញមុនពេលបន្ត។",
        "no_wallets": "អ្នកមិនទាន់មានកាបូបណាមួយនៅឡើយ។",
        "select_wallet": "ជ្រើសរើសកាបូបមួយដើម្បីមើលប្រវត្តិប្រតិបត្តិការរបស់វា:",
        "wallet_details": "**ឈ្មោះកាបូប:** {name} \n\n **អាសយដ្ឋានសាធារណៈ:** `{public_key}`",
        "wallet_not_found": "មិនឃើញកាបូបទេ។",
        "back_button": "ត្រឡប់ក្រោយ",
        "sol_wallets_header": "<b>កាបូប SOL របស់អ្នក:</b>\n",
        "wallet_balance": "<b>ឈ្មោះ:</b> {name}, <b>សមតុល្យ:</b> {balance} SOL\n",
        "wallet_error": "<b>ឈ្មោះ:</b> {name}, <b>កំហុស:</b> {error}\n",
        "no_sol_wallets": "អ្នកមិនទាន់មានកាបូប SOL នៅឡើយ។",
        "no_usdt_wallets": "អ្នកមិនទាន់មានកាបូប USDT នៅឡើយ។",
        "back_button": "⬅️ ត្រឡប់ក្រោយ",
        "refresh_btn": "🔄 ធ្វើអាប់ដេត",
        "wallet_not_found": "មិនឃើញកាបូបទេ។",
        "show_balance": "\n\n🔷 {name}\n\n💰 សមតុល្យ: {balance}\n🔑 សោសាធារណៈ: {public_key}\n\nជ្រើសរើសសកម្មភាពមួយ:",
        "show_private_key": "🔐 បង្ហាញសោសំងាត់",
        "back_to_wallet": "⬅️ ត្រឡប់ទៅកាបូប",
        "your_usdt_wallet": "📋 កាបូប USDT របស់អ្នក:",
        "show_it_btn": "✅ បាទ បង្ហាញវា",
        "private_key_warning": "🚨 ការព្រមានសោសំងាត់ 🚨\n\nសោនេះផ្តល់​សិទ្ធិ​ចូលប្រើ​កាបូប និង​ប្រាក់របស់អ្នក​ទាំងមូល។\n\n🔐 សោសំងាត់:\n{wallet}\n\n❗ កុំចែករំលែកសោនេះជាមួយនរណាម្នាក់ឡើយ\n❗ កុំបញ្ចូលវានៅលើគេហទំព័រដែលមិនបានផ្ទៀងផ្ទាត់\n❗ រក្សាទុកវាឱ្យមានសុវត្ថិភាពនៅក្រៅអ៊ីនធឺណិត ប្រសិនបើអ្នកត្រូវការរក្សាទុក",
        "dont_have_any_wallet": "<b>អ្នកមិនទាន់មានកាបូបណាមួយនៅឡើយ។</b>",
        "select_wallet_header": "<b>ជ្រើសរើសកាបូបមួយដើម្បីមើលអាសយដ្ឋានរបស់វា:</b>",
        "wallet_not_found": "មិនឃើញកាបូបទេ។",
        "select_wallet_type_header": "សូមជ្រើសរើសប្រភេទកាបូប:",
        "enter_wallet_name": "សូមបញ្ចូលឈ្មោះកាបូប:",
        "wallet_address_already_in_use": "❌ កាបូបដែលមានឈ្មោះនេះមានរួចហើយ។ សូមជ្រើសរើសឈ្មោះផ្សេងទៀត។",
        "dont_have_wallet_to_delete": "<b>អ្នកមិនមានកាបូបណាដើម្បីលុបទេ។</b>",
        "yes_delete": "បាទ លុប",
        "wallet_deleted": "កាបូបត្រូវបានលុបដោយជោគជ័យ។",
        "failed_to_delete_wallet": "បរាជ័យក្នុងការលុបកាបូប។",
        "delete_wallet_header": "ជ្រើសរើសកាបូបដែលត្រូវលុប:",
        "delete_wallet_confirm_reject": "អ្នកមិនបានបញ្ជាក់ការលុបកាបូប",
    },
    "ja": {
        "choose_wallet": "ウォレットの種類を選択してください：",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - トロンネットワーク)",
        "choose_existing_or_new_wallet": "既存のウォレットを選択または新規作成",
        "wallet_name_prompt": "あなたは {wallet_type} ウォレットを選択しました。\nウォレット名を入力してください：",
        "wallet_name_empty": "❌ ウォレット名は空にできません。再度試してください。",
        "wallet_create_ok": "✅ ウォレットが正常に作成されました！\n\n",
        "wallet_create_err": "❌ ウォレット作成中にエラーが発生しました。後でもう一度お試しください。",
        "cancel_msg": "操作がキャンセルされました。/start を使用して再開してください。",
        "account_wallet_type": "アカウントウォレットの種類 (SOL | USDT)",
        "menu_wallet_title": "💳 ウォレットメニュー",
        "btn_refresh": "🔄 更新",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - トロンネットワーク)",
        "btn_show_address": "🏠 アドレスを表示",
        "btn_create_wallet": "➕ ウォレットを作成",
        "btn_delete_wallet": "🗑️ ウォレットを削除",
        "wallet_no_exists": "❌ ウォレットが見つかりません。「ウォレットを作成」ボタンで作成してください。",
        "wallet_exists": "📌 <b>既存のウォレット：</b>\n名前: {name}\n公開鍵: `{pub}`\n残高: {bal} SOL",
        "wallet_deleted": "✅ ウォレットの削除が成功しました。",
        "wallet_not_deleted": "❌ 削除するウォレットがありません。",
        "wallet_refreshed": "🔄 残高を更新しました:\n名前: {name}\n公開鍵: `{pub}`\n残高: {bal} SOL",
        "guide_create_wallet": "📝 <b>ウォレットの作成方法：</b>\n1️⃣ ウォレットの種類（SOL または USDT）を選択します。\n2️⃣ ウォレットの名前を入力します。\n3️⃣ 公開鍵と秘密鍵を持つウォレットが作成されます。\n4️⃣ 公開鍵を使用して資金を受け取ります。\n\n💡 ヒント: 秘密鍵は安全に保管し、誰にも教えないでください。",
        "guide_delete_wallet": "⚠️ <b>重要情報：</b>\nウォレットの削除は元に戻せません。ウォレット内のすべての資金が失われます。\n削除前にすべての資金を移動済みか確認してください。",
        "no_wallets": "まだウォレットがありません。",
        "select_wallet": "取引履歴を確認するウォレットを選択してください：",
        "wallet_details": "**ウォレット名：** {name} \n\n **公開アドレス：** `{public_key}`",
        "wallet_not_found": "ウォレットが見つかりません。",
        "back_button": "戻る",
        "sol_wallets_header": "<b>あなたのSOLウォレット：</b>\n",
        "wallet_balance": "<b>名前：</b> {name}, <b>残高：</b> {balance} SOL\n",
        "wallet_error": "<b>名前：</b> {name}, <b>エラー：</b> {error}\n",
        "no_sol_wallets": "まだSOLウォレットがありません。",
        "no_usdt_wallets": "まだUSDTウォレットがありません。",
        "back_button": "⬅️ 戻る",
        "refresh_btn": "🔄 更新",
        "wallet_not_found": "ウォレットが見つかりません。",
        "show_balance": "\n\n🔷 {name}\n\n💰 残高: {balance}\n🔑 公開鍵: {public_key}\n\n操作を選択してください：",
        "show_private_key": "🔐 秘密鍵を表示",
        "back_to_wallet": "⬅️ ウォレット一覧に戻る",
        "your_usdt_wallet": "📋 あなたのUSDTウォレット：",
        "show_it_btn": "✅ はい、表示する",
        "private_key_warning": "🚨 秘密鍵警告 🚨\n\nこの鍵はウォレットと資金への完全なアクセス権を持ちます。\n\n🔐 秘密鍵:\n{wallet}\n\n❗ 誰にもこの鍵を教えないでください\n❗ 認証されていないサイトに入力しないでください\n❗ 必要な場合のみ、オフラインで安全に保管してください",
        "dont_have_any_wallet": "<b>まだウォレットがありません。</b>",
        "select_wallet_header": "<b>アドレスを確認するウォレットを選択してください：</b>",
        "wallet_not_found": "ウォレットが見つかりません。",
        "select_wallet_type_header": "ウォレットの種類を選択してください：",
        "enter_wallet_name": "ウォレット名を入力してください：",
        "wallet_address_already_in_use": "❌ この名前のウォレットはすでに存在します。別の名前を選んでください。",
        "dont_have_wallet_to_delete": "<b>削除できるウォレットがありません。</b>",
        "yes_delete": "はい、削除する",
        "wallet_deleted": "ウォレットの削除が成功しました。",
        "failed_to_delete_wallet": "ウォレットの削除に失敗しました。",
        "delete_wallet_header": "削除するウォレットを選択してください：",
        "delete_wallet_confirm_reject": "ウォレットの削除を確認しませんでした",
    },
    "ko": {
        "choose_wallet": "지갑 유형을 선택하세요:",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - 트론 네트워크)",
        "choose_existing_or_new_wallet": "기존 지갑 선택 또는 새 지갑 생성",
        "wallet_name_prompt": "당신은 {wallet_type} 지갑을 선택했습니다.\n지갑 이름을 입력해주세요:",
        "wallet_name_empty": "❌ 지갑 이름은 비워둘 수 없습니다. 다시 시도해주세요.",
        "wallet_create_ok": "✅ 지갑 생성 성공!\n\n",
        "wallet_create_err": "❌ 지갑 생성 중 오류 발생. 나중에 다시 시도해주세요.",
        "cancel_msg": "작업이 취소되었습니다. /start 명령어로 다시 시작하세요.",
        "account_wallet_type": "계정 지갑 유형 (SOL | USDT)",
        "menu_wallet_title": "💳 지갑 메뉴",
        "btn_refresh": "🔄 새로 고침",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - 트론 네트워크)",
        "btn_show_address": "🏠 주소 보기",
        "btn_create_wallet": "➕ 지갑 생성",
        "btn_delete_wallet": "🗑️ 지갑 삭제",
        "wallet_no_exists": "❌ 지갑을 찾을 수 없습니다. '지갑 생성' 버튼으로 새 지갑을 만들어주세요.",
        "wallet_exists": "📌 <b>기존 지갑:</b>\n이름: {name}\n공개 키: `{pub}`\n잔액: {bal} SOL",
        "wallet_deleted": "✅ 지갑 삭제 완료.",
        "wallet_not_deleted": "❌ 삭제할 지갑이 없습니다.",
        "wallet_refreshed": "🔄 잔액 업데이트:\n이름: {name}\n공개 키: `{pub}`\n잔액: {bal} SOL",
        "guide_create_wallet": "📝 <b>지갑 생성 방법:</b>\n1️⃣ 지갑 종류(SOL 또는 USDT)를 선택합니다.\n2️⃣ 고유한 지갑 이름을 입력합니다.\n3️⃣ 공개 키와 비밀 키가 함께 생성됩니다.\n4️⃣ 공개 키를 사용해 자금을 받을 수 있습니다.\n\n💡 팁: 비밀 키는 안전하게 보관하고 절대 타인과 공유하지 마세요.",
        "guide_delete_wallet": "⚠️ <b>중요 정보:</b>\n지갑 삭제는 되돌릴 수 없습니다. 지갑 내 모든 자산이 소실됩니다.\n삭제 전 모든 자금을 이체했는지 확인하세요.",
        "no_wallets": "아직 생성된 지갑이 없습니다.",
        "select_wallet": "거래 내역을 확인할 지갑을 선택하세요:",
        "wallet_details": "**지갑 이름:** {name} \n\n **공개 주소:** `{public_key}`",
        "wallet_not_found": "지갑을 찾을 수 없습니다.",
        "back_button": "뒤로 가기",
        "sol_wallets_header": "<b>내 SOL 지갑:</b>\n",
        "wallet_balance": "<b>이름:</b> {name}, <b>잔액:</b> {balance} SOL\n",
        "wallet_error": "<b>이름:</b> {name}, <b>오류:</b> {error}\n",
        "no_sol_wallets": "아직 SOL 지갑이 없습니다.",
        "no_usdt_wallets": "아직 USDT 지갑이 없습니다.",
        "back_button": "⬅️ 뒤로",
        "refresh_btn": "🔄 새로 고침",
        "wallet_not_found": "지갑을 찾을 수 없습니다.",
        "show_balance": "\n\n🔷 {name}\n\n💰 잔액: {balance}\n🔑 공개 키: {public_key}\n\n동작을 선택하세요:",
        "show_private_key": "🔐 비밀 키 보기",
        "back_to_wallet": "⬅️ 지갑 목록으로 돌아가기",
        "your_usdt_wallet": "📋 귀하의 USDT 지갑:",
        "show_it_btn": "✅ 예, 보여주세요",
        "private_key_warning": "🚨 비밀 키 경고 🚨\n\n이 키는 지갑과 자금에 대한 전체 접근 권한을 부여합니다.\n\n🔐 비밀 키:\n{wallet}\n\n❗ 누구에게도 이 키를 공유하지 마세요\n❗ 검증되지 않은 웹사이트에 절대 입력하지 마세요\n❗ 보관해야 한다면 오프라인에서 안전하게 저장하세요",
        "dont_have_any_wallet": "<b>아직 지갑이 없습니다.</b>",
        "select_wallet_header": "<b>주소를 확인할 지갑을 선택하세요:</b>",
        "wallet_not_found": "지갑을 찾을 수 없습니다.",
        "select_wallet_type_header": "지갑 유형을 선택하세요:",
        "enter_wallet_name": "지갑 이름을 입력하세요:",
        "wallet_address_already_in_use": "❌ 동일한 이름의 지갑이 이미 존재합니다. 다른 이름을 선택하세요.",
        "dont_have_wallet_to_delete": "<b>삭제할 지갑이 없습니다.</b>",
        "yes_delete": "예, 삭제합니다",
        "wallet_deleted": "지갑이 성공적으로 삭제되었습니다.",
        "failed_to_delete_wallet": "지갑 삭제에 실패했습니다.",
        "delete_wallet_header": "삭제할 지갑을 선택하세요:",
        "delete_wallet_confirm_reject": "지갑 삭제를 확인하지 않았습니다.",
    },
    "ur": {
        "choose_wallet": "براہ کرم والٹ کی قسم منتخب کریں:",
        "sol_wallet": "⚡ Solana (SOL)",
        "usdt_wallet": "💵 USDT (TRC20 - ٹرون نیٹ ورک)",
        "choose_existing_or_new_wallet": "موجودہ والٹ کو منتخب کریں یا نیا والٹ بنائیں",
        "wallet_name_prompt": "آپ نے {wallet_type} والٹ کو منتخب کیا ہے۔\nبراہ کرم اپنے والٹ کے لیے نام درج کریں:",
        "wallet_name_empty": "❌ والٹ کا نام خالی نہیں ہو سکتا۔ براہ کرم دوبارہ کوشش کریں۔",
        "wallet_create_ok": "✅ والٹ کامیابی سے بنایا گیا!\n\n",
        "wallet_create_err": "❌ والٹ بناتے وقت خرابی آ گئی۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
        "cancel_msg": "آپریشن منسوخ کر دیا گیا۔ دوبارہ شروع کرنے کے لیے /start استعمال کریں۔",
        "account_wallet_type": "اکاؤنٹ والٹ کی قسم (SOL | USDT)",
        "menu_wallet_title": "💳 والٹ مینو",
        "btn_refresh": "🔄 تازہ کاری",
        "btn_sol": "⚡ Solana (SOL)",
        "btn_usdt": "💵 USDT (TRC20 - ٹرون نیٹ ورک)",
        "btn_show_address": "🏠 پتہ دکھائیں",
        "btn_create_wallet": "➕ والٹ بنائیں",
        "btn_delete_wallet": "🗑️ والٹ حذف کریں",
        "wallet_no_exists": "❌ کوئی والٹ نہیں ملا۔ براہ کرم 'والٹ بنائیں' بٹن کے ذریعے ایک بنائیں۔",
        "wallet_exists": "📌 <b>موجودہ والٹ:</b>\nنام: {name}\nعوامی کلید: `{pub}`\nبقایا: {bal} SOL",
        "wallet_deleted": "✅ والٹ کامیابی سے حذف کر دیا گیا۔",
        "wallet_not_deleted": "❌ حذف کرنے کے لیے کوئی والٹ موجود نہیں۔",
        "wallet_refreshed": "🔄 بقایا تازہ کاری:\nنام: {name}\nعوامی کلید: `{pub}`\nبقایا: {bal} SOL",
        "guide_create_wallet": "📝 <b>والٹ بنانے کا طریقہ:</b>\n1️⃣ والٹ کی قسم منتخب کریں (SOL یا USDT)۔\n2️⃣ اپنے والٹ کے لیے ایک منفرد نام درج کریں۔\n3️⃣ آپ کا والٹ عوامی کلید اور رازداری کلید کے ساتھ بنایا جائے گا۔\n4️⃣ فنڈز وصول کرنے کے لیے عوامی کلید استعمال کریں۔\n\n💡 تجاویز: اپنی رازداری کلید کو محفوظ رکھیں اور کسی کے ساتھ شیئر نہ کریں۔",
        "guide_delete_wallet": "⚠️ <b>اہم معلومات:</b>\nوالٹ حذف کرنا غیر معکوس عمل ہے۔ والٹ میں موجود تمام فنڈز ضائع ہو جائیں گے۔\nجاری رکھنے سے پہلے یقینی بنائیں کہ آپ نے تمام فنڈز منتقل کر دیے ہیں۔",
        "no_wallets": "آپ کے پاس ابھی کوئی والٹ نہیں ہے۔",
        "select_wallet": "اپنی لین دین کی تاریخ دیکھنے کے لیے والٹ منتخب کریں:",
        "wallet_details": "**والٹ کا نام:** {name} \n\n **عوامی پتہ:** `{public_key}`",
        "wallet_not_found": "والٹ نہیں ملا۔",
        "back_button": "واپس",
        "sol_wallets_header": "<b>آپ کے SOL والٹس:</b>\n",
        "wallet_balance": "<b>نام:</b> {name}, <b>بقایا:</b> {balance} SOL\n",
        "wallet_error": "<b>نام:</b> {name}, <b>خرابی:</b> {error}\n",
        "no_sol_wallets": "آپ کے پاس ابھی کوئی SOL والٹ نہیں ہے۔",
        "no_usdt_wallets": "آپ کے پاس ابھی کوئی USDT والٹ نہیں ہے۔",
        "back_button": "⬅️ واپس",
        "refresh_btn": "🔄 تازہ کاری",
        "wallet_not_found": "والٹ نہیں ملا۔",
        "show_balance": "\n\n🔷 {name}\n\n💰 بقایا: {balance}\n🔑 عوامی کلید: {public_key}\n\nکوئی کارروائی منتخب کریں:",
        "show_private_key": "🔐 رازداری کلید دکھائیں",
        "back_to_wallet": "⬅️ والٹس پر واپس",
        "your_usdt_wallet": "📋 آپ کے USDT والٹس:",
        "show_it_btn": "✅ ہاں، دکھائیں",
        "private_key_warning": "🚨 رازداری کلید کی انتباہ 🚨\n\nیہ کلید آپ کے والٹ اور فنڈز تک مکمل رسائی فراہم کرتی ہے۔\n\n🔐 رازداری کلید:\n{wallet}\n\n❗ کسی کے ساتھ یہ کلید شیئر نہ کریں\n❗ غیر تصدیق شدہ ویب سائٹس پر کبھی داخل نہ کریں\n❗ اگر محفوظ کرنا ہو تو آف لائن محفوظ رکھیں",
        "dont_have_any_wallet": "<b>آپ کے پاس ابھی کوئی والٹ نہیں ہے۔</b>",
        "select_wallet_header": "<b>اپنا پتہ دیکھنے کے لیے والٹ منتخب کریں:</b>",
        "wallet_not_found": "والٹ نہیں ملا۔",
        "select_wallet_type_header": "براہ کرم والٹ کی قسم منتخب کریں:",
        "enter_wallet_name": "براہ کرم والٹ کا نام درج کریں:",
        "wallet_address_already_in_use": "❌ اس نام کا والٹ پہلے سے موجود ہے۔ براہ کرم کوئی دوسرا نام منتخب کریں۔",
        "dont_have_wallet_to_delete": "<b>حذف کرنے کے لیے کوئی والٹ موجود نہیں ہے۔</b>",
        "yes_delete": "ہاں، حذف کریں",
        "wallet_deleted": "والٹ کامیابی سے حذف کر دیا گیا۔",
        "failed_to_delete_wallet": "والٹ حذف کرنے میں ناکامی۔",
        "delete_wallet_header": "حذف کرنے کے لیے والٹ منتخب کریں:",
        "delete_wallet_confirm_reject": "آپ نے والٹ حذف کرنے کی تصدیق نہیں کی",
    },
}
