WALLET_MENU_CONSTANT = {
    "en": {
        # Buttons
        "refresh_btn": "🔄 Refresh",
        "sol_btn": "🪙 SOL",
        "usdt_btn": "💵 USDT",
        "address_btn": "💼 Show Address",
        "history_btn": "📜 History",
        "create_wallet_btn": "➕ Create Wallet",
        "delete_wallet_btn": "❌ Delete Wallet",
        "welcome_text": "Welcome to the Wallet Menu!",
        "refresh_wallet_text": "Wallets refreshed!",
        "no_wallet": "You don't have any  wallets yet.",
    },
    "zh": {
        "refresh_btn": "🔄 刷新",
        "sol_btn": "🪙 SOL",
        "usdt_btn": "💵 USDT",
        "address_btn": "💼 显示地址",
        "history_btn": "📜 历史记录",
        "create_wallet_btn": "➕ 创建钱包",
        "delete_wallet_btn": "❌ 删除钱包",
        "welcome_text": "欢迎来到钱包菜单!",
        "refresh_wallet_text": "钱包已刷新!",
        "no_wallet": "你还没有  钱包。",
    },
    "ms": {
        # Butang
        "refresh_btn": "🔄 Segar Semula",
        "sol_btn": "🪙 SOL",
        "usdt_btn": "💵 USDT",
        "address_btn": "💼 Tunjukkan Alamat",
        "history_btn": "📜 Sejarah",
        "create_wallet_btn": "➕ Buat Dompet",
        "delete_wallet_btn": "❌ Padam Dompet",
        "welcome_text": "Selamat datang ke Menu Dompet!",
        "refresh_wallet_text": "Dompet telah dikemas kini!",
        "no_wallet": "Anda belum mempunyai dompet  lagi.",
    },
}
