import os
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")
MONGODB_URI = os.getenv("MONGODB_URI")
MONGODB_NAME = os.getenv("MONGODB_NAME")
# TOKEN =  os.getenv("TOKEN")
TOKEN = "7661419997:AAHOquyQJ5M6YgzuQwR8EZoAH163tGLytt4"
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")

SOL_WALLET_PRIVATE_KEY = os.getenv("SOL_WALLET_PRIVATE_KEY")
SOL_WALLET_PUBLIC_KEY = os.getenv("SOL_WALLET_PUBLIC_KEY")
TRON_WALLET_PRIVATE_KEY = os.getenv("TRON_WALLET_PRIVATE_KEY")
TRON_WALLET_PUBLIC_KEY = os.getenv("TRON_WALLET_PUBLIC_KEY")

SOL_COLLECT_PRIVATE_KEY = os.getenv("SOL_COLLECT_PRIVATE_KEY")
SOL_COLLECT_PUBLIC_KEY = os.getenv("SOL_COLLECT_PUBLIC_KEY")
TRON_COLLECT_PRIVATE_KEY = os.getenv("TRON_COLLECT_PRIVATE_KEY")
TRON_COLLECT_PUBLIC_KEY = os.getenv("TRON_COLLECT_PUBLIC_KEY")

CLIENT = os.getenv("CLIENT")
OWNER_TELEGRAM_ID = os.getenv("OWNER_TELEGRAM_ID")
TRON_CLIENT_NETWORK = os.getenv("TRON_CLIENT_NETWORK")

NODE_ENV = os.getenv("NODE_ENV")