from telegram.ext import (
    ConversationHandler,
)

from enum import Enum
from solana.rpc.api import Client
from config.config_manager import CLIENT


class State(Enum):
    LANGUAGE_SELECTED = "LANGUAGE_SELECTED"
    SHOW_DISCLAIMER = "SHOW_DISCLAIMER"
    CHOOSE_COUNTRY = "CHOOSE_COUNTRY"
    START_CHOOSE_PROVINCE = "START_CHOOSE_PROVINCE"
    CHOOSE_PROVINCE = "CHOOSE_PROVINCE"
    CHOOSE_CITY = "CHOOSE_CITY"
    CHOOSE_ACTION = "CHOOSE_ACTION"
    CHOOSE_WALLET_TYPE = "CHOOSE_WALLET_TYPE"
    CHOOSE_OR_CREATE_WALLET= "CHOOSE_OR_CREATE_WALLET"
    NAME_WALLET = "NAME_WALLET"
    HANDLE_REPLY = "HANDLE_REPLY"
    CREATE_CASE_NAME = "CREATE_CASE_NAME"
    CREATE_CASE_MOBILE = "CREATE_CASE_MOBILE"
    CREATE_CASE_TAC = "CREATE_CASE_TAC"
    CREATE_CASE_DISCLAIMER = "CREATE_CASE_DISCLAIMER"
    CREATE_CASE_REWARD_TYPE = "CREATE_CASE_REWARD_TYPE"
    CREATE_CASE_REWARD_AMOUNT = "CREATE_CASE_REWARD_AMOUNT"
    CREATE_CASE_PERSON_NAME = "CREATE_CASE_PERSON_NAME"
    CREATE_CASE_RELATIONSHIP = "CREATE_CASE_RELATIONSHIP"
    CREATE_CASE_PHOTO = "CREATE_CASE_PHOTO"
    CREATE_CASE_LAST_SEEN_LOCATION = "CREATE_CASE_LAST_SEEN_LOCATION"
    CREATE_CASE_SEX = "CREATE_CASE_SEX"
    CREATE_CASE_AGE = "CREATE_CASE_AGE"
    CREATE_CASE_HAIR_COLOR = "CREATE_CASE_HAIR_COLOR"
    CREATE_CASE_EYE_COLOR = "CREATE_CASE_EYE_COLOR"
    CREATE_CASE_HEIGHT = "CREATE_CASE_HEIGHT"
    CREATE_CASE_WEIGHT = "CREATE_CASE_WEIGHT"
    CREATE_CASE_DISTINCTIVE_FEATURES = "CREATE_CASE_DISTINCTIVE_FEATURES"
    CREATE_CASE_SUBMIT = "CREATE_CASE_SUBMIT"

    ENTER_PRIVATE_KEY = "ENTER_PRIVATE_KEY"
    ENTER_PUBLIC_KEY = "ENTER_PUBLIC_KEY"
    CONFIRM_TRANSFER = "CONFIRM_TRANSFER"
    TRANSFER_CONFIRMATION = "TRANSFER_CONFIRMATION"
    CREATE_CASE_WALLET_TRANSFER = "CREATE_CASE_WALLET_TRANSFER"
    CREATE_CASE_CONFIRM_TRANSFER = "CREATE_CASE_CONFIRM_TRANSFER"
    CREATE_CASE_ASK_REWARD = "CREATE_CASE_ASK_REWARD"

    WALLET_MENU = "WALLET_MENU"
    WAITING_FOR_MOBILE = "WAITING_FOR_MOBILE"
    CREATE_WALLET = "CREATE_WALLET"
    SELECT_WALLET = "SELECT_WALLET"

    CASE_LIST = "CASE_LIST"
    CASE_DETAILS = "CASE_DETAILS"
    UPLOAD_PROOF = "UPLOAD_PROOF"
    ENTER_LOCATION = "ENTER_LOCATION"
    ADVERTISER_CONFIRMATION = "ADVERTISER_CONFIRMATION"
    MOBILE_VERIFICATION = "MOBILE_VERIFICATION"

    SETTINGS_MENU = "SETTINGS_MENU"
    MOBILE_MANAGEMENT = "MOBILE_MANAGEMENT"
    HISTORY_MENU = "HISTORY_MENU"

    ENTER_NUMBER = "ENTER_NUMBER"
    VERIFY_OTP = "VERIFY_OTP"

    VIEW_HISTORY = "VIEW_HISTORY"
    DELETE_WALLET = "DELETE_WALLET"
    SHOW_ADDRESS = "SHOW_ADDRESS"
    HANDLER_END = ConversationHandler.END
    END = -1

    EDIT_FIELD = "EDIT_FIELD"
    CREATE_CASE_FINISHED = "CREATE_CASE_FINISHED"
    CREATE_CASE_ASK_REASON = "CREATE_CASE_ASK_REASON"
    REWARD_TRANSFER_PROCESS = "REWARD_TRANSFER_PROCESS"
    FINISHED = "FINISHED"

    EXTEND_REWARD = "EXTEND_REWARD"
    CONFIRM_FOUND = "CONFIRM_FOUND"
    EXTEND_REWARD_AMOUNT = "EXTEND_REWARD_AMOUNT"
    EXTEND_REWARD_CONFIRM = "EXTEND_REWARD_CONFIRM"
    EXTEND_REWARD_FINISHED = "EXTEND_REWARD_FINISHED"
    EXTEND_REWARD_ASK_REASON = "EXTEND_REWARD_ASK_REASON"
    SELECT_WALLET_FOR_EXTEND = "SELECT_WALLET_FOR_EXTEND"
    ADVERTISER_RESPONSE = "ADVERTISER_RESPONSE"
    ENTER_WALLET_NAME = "ENTER_WALLET_NAME"
    SELECT_WALLET_TYPE = "SELECT_WALLET_TYPE"
    CONFIRM_DELETE_WALLET = "CONFIRM_DELETE_WALLET"
    CONFIRM_REWARD = "CONFIRM_REWARD"
    FINDER_CHOOSE_WALLET_TYPE = "FINDER_CHOOSE_WALLET_TYPE"
    FINDER_NAME_WALLET = "FINDER_NAME_WALLET"
    FINDER_CONFIRM_TRANSACTION = "FINDER_CONFIRM_TRANSACTION"
    CONFIRM_EXTEND = "CONFIRM_EXTEND"
    ENTER_COUNTRY = "ENTER_COUNTRY"
    ENTER_CITY = "ENTER_CITY"

    #  For Wallet Conversation
    USDT_WALLET_DETAIL = "USDT_WALLET_DETAIL"
    USDT_WALLET_ACTIONS = "USDT_WALLET_ACTIONS"
    CONFIRM_PRIVATE_KEY = "CONFIRM_PRIVATE_KEY"
    SOL_WALLET_DETAIL = "SOL_WALLET_DETAIL"
    SOL_WALLET_ACTIONS = "SOL_WALLET_ACTIONS"

    # Settings
    SETTINGS_MOBILE_MANAGEMENT = "SETTINGS_MOBILE_MANAGEMENT"
    SETTINGS_CREATE_CASE_TAC = "SETTINGS_CREATE_CASE_TAC"

    # Lodge Case 
    CASE_CANCEL_SELECT_REASON= "CASE_CANCEL_SELECT_REASON"
    CASE_CANCEL_ENTER_REASON = "CASE_CANCEL_ENTER_REASON"
    POST_SUBMISSION_MENU = "POST_SUBMISSION_MENU"

    class FINDER(Enum):
        CREATE_CASE_MOBILE = "FINDER_CREATE_CASE_MOBILE"
        MOBILE_MANAGEMENT = "FINDER_MOBILE_MANAGEMENT"
        CREATE_CASE_TAC = "FINDER_CREATE_CASE_TAC"
        FINDER_DISCLAIMER = "FINDER_DISCLAIMER"
        CHOOSE_COUNTRY = "FINDER_CHOOSE_COUNTRY"
        CHOOSE_PROVINCE = "FINDER_CHOOSE_PROVINCE"
        VIEW_COMPLAINTS = "FINDER_VIEW_COMPLAINTS"
        END = "END"

    class WALLETS(Enum):
        WALLET_MENU = "WALLET_MENU"
        SOL_WALLET_DETAIL = "SOL_WALLET_DETAIL"
        SOL_WALLET_ACTIONS = "SOL_WALLET_ACTIONS"
        USDT_WALLET_DETAIL = "USDT_WALLET_DETAIL"
        USDT_WALLET_ACTIONS = "USDT_WALLET_ACTIONS"
        CONFIRM_PRIVATE_KEY = "CONFIRM_PRIVATE_KEY"
        SHOW_ADDRESS = "SHOW_ADDRESS"
        VIEW_HISTORY = "VIEW_HISTORY"
        SELECT_WALLET_TYPE = "SELECT_WALLET_TYPE"
        ENTER_WALLET_NAME = "ENTER_WALLET_NAME"
        CONFIRM_DELETE_WALLET = "CONFIRM_DELETE_WALLET"
        DELETE_WALLET = "DELETE_WALLET"
        END = "END"
    class SETTINGS(Enum):
        SETTINGS_MENU = "SETTINGS_MENU"
        WAITING_FOR_MOBILE = "WAITING_FOR_MOBILE"
        SETTINGS_MOBILE_MANAGEMENT = "SETTINGS_MOBILE_MANAGEMENT"
        MOBILE_VERIFICATION = "MOBILE_VERIFICATION"
        SETTINGS_CREATE_CASE_TAC = "SETTINGS_CREATE_CASE_TAC"
        END = "END"
    class STATS(Enum):
        SHOW_STATS_MENU = "SHOW_STATS_MENU"
        SHOW_LOCAL_STATS_RESULTS = "SHOW_LOCAL_STATS_RESULTS"
        SHOW_UNSOLVED_COUNTRIES = "SHOW_UNSOLVED_COUNTRIES"
        SHOW_MY_CASES = "SHOW_MY_CASES"
        ASK_LOCAL_PROVINCE_CITY = "ASK_LOCAL_PROVINCE_CITY"
        BACK_TO_STATS = "BACK_TO_STATS"
        END = "END"

# ======================
# Language Data & Constants
# ======================



WALLETS_DIR = "wallets"  # Directory to store user wallets
PHOTOS_DIR = "photos"  # Directory to store uploaded photos
PROOFS_DIR = "proofs"  # Directory to store proof uploads
USDT_CONTRACT = "TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj"

# ====================== Solana ======================

solana_client = Client(CLIENT)
