# State constants for the Telegram bot conversation handlers
from enum import Enum

class State:
    # Main flow states
    LANGUAGE_SELECTED = "LANGUAGE_SELECTED"
    CHOOSE_COUNTRY = "CHOOSE_COUNTRY"
    SHOW_DISCLAIMER = "SHOW_DISCLAIMER"
    START_CHOOSE_PROVINCE = "START_CHOOSE_PROVINCE"
    CHOOSE_CITY = "CHOOSE_CITY"
    CHOOSE_ACTION = "CHOOSE_ACTION"
    
    # Case creation states
    CREATE_CASE_MOBILE = "CREATE_CASE_MOBILE"
    MOBILE_MANAGEMENT = "MOBILE_MANAGEMENT"
    CREATE_CASE_TAC = "CREATE_CASE_TAC"
    CHOOSE_OR_CREATE_WALLET = "CHOOSE_OR_CREATE_WALLET"
    NAME_WALLET = "NAME_WALLET"
    HANDLE_REPLY = "HANDLE_REPLY"
    CREATE_CASE_DISCLAIMER = "CREATE_CASE_DISCLAIMER"
    CREATE_CASE_PERSON_NAME = "CREATE_CASE_PERSON_NAME"
    CREATE_CASE_RELATIONSHIP = "CREATE_CASE_RELATIONSHIP"
    CREATE_CASE_PHOTO = "CREATE_CASE_PHOTO"
    CREATE_CASE_LAST_SEEN_LOCATION = "CREATE_CASE_LAST_SEEN_LOCATION"
    CREATE_CASE_SEX = "CREATE_CASE_SEX"
    CREATE_CASE_AGE = "CREATE_CASE_AGE"
    CREATE_CASE_HAIR_COLOR = "CREATE_CASE_HAIR_COLOR"
    CREATE_CASE_EYE_COLOR = "CREATE_CASE_EYE_COLOR"
    CREATE_CASE_HEIGHT = "CREATE_CASE_HEIGHT"
    CREATE_CASE_WEIGHT = "CREATE_CASE_WEIGHT"
    CREATE_CASE_DISTINCTIVE_FEATURES = "CREATE_CASE_DISTINCTIVE_FEATURES"
    CREATE_CASE_ASK_REASON = "CREATE_CASE_ASK_REASON"
    CREATE_CASE_ASK_REWARD = "CREATE_CASE_ASK_REWARD"
    CREATE_CASE_CONFIRM_TRANSFER = "CREATE_CASE_CONFIRM_TRANSFER"
    
    # Case management states
    CASE_LIST = "CASE_LIST"
    CASE_DETAILS = "CASE_DETAILS"
    UPLOAD_PROOF = "UPLOAD_PROOF"
    ENTER_LOCATION = "ENTER_LOCATION"
    EXTEND_REWARD = "EXTEND_REWARD"
    EXTEND_REWARD_AMOUNT = "EXTEND_REWARD_AMOUNT"
    ADVERTISER_RESPONSE = "ADVERTISER_RESPONSE"
    CONFIRM_FOUND = "CONFIRM_FOUND"
    TRANSFER_CONFIRMATION = "TRANSFER_CONFIRMATION"
    
    # Wallet states
    CHOOSE_WALLET_TYPE = "CHOOSE_WALLET_TYPE"
    CONFIRM_REWARD = "CONFIRM_REWARD"
    REWARD_TRANSFER_PROCESS = "REWARD_TRANSFER_PROCESS"
    SELECT_WALLET_FOR_EXTEND = "SELECT_WALLET_FOR_EXTEND"
    CONFIRM_EXTEND = "CONFIRM_EXTEND"
    
    # Finder states
    FINDER_CHOOSE_WALLET_TYPE = "FINDER_CHOOSE_WALLET_TYPE"
    FINDER_NAME_WALLET = "FINDER_NAME_WALLET"
    FINDER_CONFIRM_TRANSACTION = "FINDER_CONFIRM_TRANSACTION"
    
    # Settings states
    SETTINGS_MENU = "SETTINGS_MENU"
    WAITING_FOR_MOBILE = "WAITING_FOR_MOBILE"
    SETTINGS_MOBILE_MANAGEMENT = "SETTINGS_MOBILE_MANAGEMENT"
    MOBILE_VERIFICATION = "MOBILE_VERIFICATION"
    SETTINGS_CREATE_CASE_TAC = "SETTINGS_CREATE_CASE_TAC"
    
    # End state
    END = "END"
    
    # Nested state classes
    class FINDER:
        CREATE_CASE_MOBILE = "FINDER_CREATE_CASE_MOBILE"
        MOBILE_MANAGEMENT = "FINDER_MOBILE_MANAGEMENT"
        CREATE_CASE_TAC = "FINDER_CREATE_CASE_TAC"
        FINDER_DISCLAIMER = "FINDER_FINDER_DISCLAIMER"
        CHOOSE_COUNTRY = "FINDER_CHOOSE_COUNTRY"
        CHOOSE_PROVINCE = "FINDER_CHOOSE_PROVINCE"
        VIEW_COMPLAINTS = "FINDER_VIEW_COMPLAINTS"
    
    class SETTINGS:
        SETTINGS_MENU = "SETTINGS_SETTINGS_MENU"
        WAITING_FOR_MOBILE = "SETTINGS_WAITING_FOR_MOBILE"
        SETTINGS_MOBILE_MANAGEMENT = "SETTINGS_SETTINGS_MOBILE_MANAGEMENT"
        MOBILE_VERIFICATION = "SETTINGS_MOBILE_VERIFICATION"
        SETTINGS_CREATE_CASE_TAC = "SETTINGS_SETTINGS_CREATE_CASE_TAC"
        END = "SETTINGS_END"
    
    class WALLETS:
        WALLET_MENU = "WALLETS_WALLET_MENU"
        SOL_WALLET_DETAIL = "WALLETS_SOL_WALLET_DETAIL"
        SOL_WALLET_ACTIONS = "WALLETS_SOL_WALLET_ACTIONS"
        USDT_WALLET_DETAIL = "WALLETS_USDT_WALLET_DETAIL"
        USDT_WALLET_ACTIONS = "WALLETS_USDT_WALLET_ACTIONS"
        CONFIRM_PRIVATE_KEY = "WALLETS_CONFIRM_PRIVATE_KEY"
        SHOW_ADDRESS = "WALLETS_SHOW_ADDRESS"
        VIEW_HISTORY = "WALLETS_VIEW_HISTORY"
        SELECT_WALLET_TYPE = "WALLETS_SELECT_WALLET_TYPE"
        ENTER_WALLET_NAME = "WALLETS_ENTER_WALLET_NAME"
        CONFIRM_DELETE_WALLET = "WALLETS_CONFIRM_DELETE_WALLET"
        DELETE_WALLET = "WALLETS_DELETE_WALLET"
        END = "WALLETS_END"